### ISSUE TITLE
Unable to search by displayName

### ISSUE THREAD

**Issue by samir07** [Yvand/LDAPCP#100]
Hi @Yvand 

We are unable to search users by their displayName, if change LDAP class value of "User identifier properties" to some other value.

So, I have added two connection strings - one is of our AD and another one is of LDAP. and there is this "User identifier properties" setting and their defaults values are **user** for class and **mail** for attributes. But in our LDAP there is no such object class as **user** and hence search query on LDAP directory doesn't work.

![image](https://user-images.githubusercontent.com/20821391/65880868-1ce48b80-e3b0-11e9-850b-652e327cb904.png)

In order to make search query work for both AD and LDAP directories, I have to change the object class value to some common value like **person** and then the search query work for both, users from both the connection are shown but as said search by displayName doesn't work for us. Any advice?

**Comment by Yvand** [comment]
Hi @samir07 
I think there are 2 separate topics here:
- The LDAP server (2nd connection) doesn't use class "user" for users, but "person": Assuming class "person" also works for AD (1st connection), then it's perfectly fine to set LDAP class to "person"
- Search users by displayName: it is configured in LDAPCP "Claim types configuration" page: I guess you need to recreate all entries of type "LDAP attribute linked to the main mapping for object User" (especially the displayName), to change LDAP class to "person"

**Comment by samir07** [comment]
Hi @Yvand 
Per you, I have changed the mapping in "Claim types configuration" below is the screen shot of the same -
![image](https://user-images.githubusercontent.com/20821391/66117008-5bb55400-e5f1-11e9-90e5-61e921af2579.png)

After making the above changes., I did iisreset couple of times and SharePoint Timer service restart.
But, its again unable to search users from our second directory i.e LDAP and even user searching got way too poor, takes lots of time to even search users from AD. 

I did check the logs, for AD users in the logs it says - Got results.. but for LDAP user it says - Got 0 results..

Anything else I can check on?

**Comment by Yvand** [comment]
Can you filter SharePoint logs on Product/Area "LDAPCP" to see happens?

**Comment by samir07** [comment]
Hi @Yvand 

I can see below error message in logs -

[LDAPCP] Unexpected error occurred while connecting to LDAP server LDAP://ldap-test.****.com: System.Runtime.InteropServices.COMException: This operation returned because the timeout period expired.  , Callstack:   
 at System.DirectoryServices.SearchResultCollection.ResultsEnumerator.MoveNext()    
 at System.DirectoryServices.SearchResultCollection.get_InnerList()    
 at System.DirectoryServices.SearchResultCollection.get_Count()    
 at ldapcp.LDAPCP.<>c__DisplayClass42_0.<QueryLDAPServers>b__1(LDAPConnection ldapConnection)

**Comment by Yvand** [comment]
Do you have any idea what can cause the timeout?
Do you think the LDAP filter is somehow invalid and would cause it?

**Comment by samir07** [comment]
I'm not so sure, I did telnet on ldap and got connected.
With filter you mean - object class which I have used as **person**. If yes- this seems valid to me as if do not change displayName mapping and just let the **person** object class in mail entry<first entry in the mapping setting> then it did works good for me. So, basically if I change the mapping for displayName it stops working..

**Comment by Yvand** [comment]
In SharePoint logs you can see the LDAP filter used by LDAPCP.
Can you use it in cmdlet below and check if you repro:
`Get-ADUser -LDAPFilter "<filter as is from ldapcp log>" -Server DC`

**Comment by samir07** [comment]
Hi @Yvand 
I ran the Get-AdUser script, with the filter copied from LDAPCP logs, and it did worked, records/users data were returned.

**Comment by Yvand** [comment]
@samir07  this exception occurs on SearchResultCollection.get_Count(), so it looks like LDAPCP got results but cannot parse them.
This time, can you try to replay the query and parse the results using the PowerShell script [located here](https://ldapcp.com/Troubleshoot-LDAPCP.html)?

**Comment by samir07** [comment]
@Yvand  - 
I have been trying a lot to see why am I getting time out error on ldap connection - 
[LDAPCP] Unexpected error occurred while connecting to LDAP server LDAP://ldap-test.****.com: System.Runtime.InteropServices.COMException: This operation returned because the timeout period expired........

My observation is - the about time out issue only happens when displayName claim mapping class is changed, below is highlighted screen-shot of it..
![image](https://user-images.githubusercontent.com/20821391/66564274-3f7b5f00-eb7d-11e9-9df8-b997c19e0857.png)

Do you know why changing of claim mapping causing the ldap time out issue?

Also, we don't have displayName attribute in our LDAP directory, but in AD we have and hence it's utmost important for us that search by displayName works.., 

Thanks.

**Comment by samir07** [comment]
@Yvand basically, if attribute for example displayName is missing from ldap directory - timeout issue occurs.

So, is there any way we can apply filter on our LDAP and AD directory. For example - for partner users we want fetch results form LDAP and if its a internal user fetch it from AD?

**Comment by Yvand** [comment]
@samir07 this is not possible to apply a LDAP filter different for each connection.
What LDAP server are you using? Could it be a known issue with this LDAP server? IMO timing out because a LDAP filter uses an unkwown attribute is a very bad design

**Comment by samir07** [comment]
Hi @Yvand - I have applied the filter in a way that I was able to get internal users form AD and external users from LDAP. Initially things seems to be working good, granting permission, check permission everything but then it got weird - while testing I found that external users access lasts for 5 to 10 mins only after that they get Access Denied Error, When I do check permission for that user it says None permission but I can see that user added in SharePoint Members group. Can you please help, this story is very important for us.

**Comment by Yvand** [comment]
@samir07 due to the cache it relies on, check permissions feature is not reliable so do not use it to validate if the permission you grant is effective or not. Do a real sign in instead and use ULS viewer in real time monitoring on Product/Area "LDAPCP".
Did you find issues after your configuration change?

**Comment by Yvand** [comment]
@samir07 any update on this?

**Comment by samir07** [comment]
Hi @Yvand - Thanks for a follow up.

I'm stuck at one point now on fetching partners' groups.
Here, for partner group - we add it as an attribute to partners account for example for partner account "xyzuser@xyzcompany.com" partner group is added as an attribute to his account like "xyzcompanygroups = partners_group" and now I want to fetch such attributes in our LDAPCP search query for which I had been trying a lot.
Do you have any idea how we can perform such query?
OR
DO we have any setting in LDAPCP where we can, allow sharing permission to such values if its not found through search query? 
I appreciate all your help throughout, many thanks.

**Comment by Yvand** [comment]
@samir07 No, this is not possible, you need to use the standard LDAP way to assign users to groups if you want this to work in LDAPCP.
Why are you using such custom implementation for group membership?
How do you get all members of a group with such implementation?
