### ISSUE TITLE
Unable to filter AD groups by Organization Unit

### ISSUE THREAD

**Issue by kalervojankko** [Yvand/LDAPCP#102]
Is there any filter to show only AD groups from selected OU's ? 

I have done all the user&group filtering based on these syntaxes I found here: https://social.technet.microsoft.com/wiki/contents/articles/5392.active-directory-ldap-syntax-filters.aspx

However I cannot find any solution to filter based by OU.

Temporarily we have added an extensionattribute to all the AD groups we want to show in People Picker and then added this filter to groups in LDAPCP: (&(objectClass=group)(extensionAttribute2=someword*))

One way would be to add all those AD groups to one "master"-AD group and then probaly use the memberof-filter. Unfortunately that's not an option for various reasons according to our client.

Is there any other way?

**Comment by Yvand** [comment]
@kalervojankko in central administration > Security > LDAPCP claims mapping page, you can set an "Additional LDAP filter" that will apply only to the group. 
Would that fit your need?

**Comment by kalervojankko** [comment]
@Yvand yes I have done all the filtering from the claims mapping page and that works well. :)

I was just wondering is it possible to filter AD groups based by OU (or any other suitable workaround) since I don't think anyone wants People Picker to resolve entire AD because it will populate hundreds of redundant AD groups which have no use in Sharepoint and should not be available for granting permissions.

I think I have turned the whole internet upside down and cannot find a suitable LDAP filter for this scenario.

**Comment by Yvand** [comment]
@kalervojankko you can filter on a specific OU if you set the LDAP connection to target it specifically, for example:
`LDAP://corp.domain.com/OU=MyOU,DC=corp,DC=domain,DC=com`
But it will apply to all objects, not only groups.

**Comment by kalervojankko** [comment]
Thanks! That might help.

I already added one extra LDAP connection to AD OU in our TEST farm, but not sure what account I should use. UserProfleSync is the only account that has Replicating Directory Changes permission on AD, but I believe that's not necessary since LDAPCP needs only to read AD and I can use a "general" Sharepoint service account for the LDAP connection.

We have AD Users in three different OUs and AD Groups in two different OUs so I guess I should try to add 5 different LDAP connections straight to those OUs and see if this is right solution.

**Comment by Yvand** [comment]
LDAPCP just needs a basic account with no specific permission, except the right to do LDAP queries (which all accounts have by default)

**Comment by kalervojankko** [comment]
I targeted some OU's with multiple LDAP connections and it seems to work as you described.

However there's still a lot redundant AD groups in those targeted OU's which I cannot filter out because there is no filter based on OUs. :)

So that LDAP connection targeting helps a little, but in the end I have still the same problem. I just have to live with that and suggest the client that they move those redundant AD-groups to some other OU or they can move all the needed AD groups to a new "master" AD-group and then I just include that "master" AD-group with the memberof-filter.

Anyway...thanks a lot!

**Comment by Yvand** [comment]
No worries. One more thing that you can do: set a specific value to a LDAP property of the groups you want to include (or hide), and use it in a filter in "Additional LDAP filter" in LDAPCP claims mapping page
