### ISSUE TITLE
AD Group/Role issue

### ISSUE THREAD

**Issue by schrockmatthew** [Yvand/LDAPCP#103]
We had a peculiar situation happen....before we had ldapcp deployed we had our Federated groups assigned to the site/subsites.....Then an admin renamed a group that was assigned and all those users in that group couldn't see the site....After troubleshooting we added a new group and the that group did not apply the correct security......after retracting ldapcp and adding the correct group/role to the site, users could then access......We redeployed the ldapcp solution after proper role was added and users could then access......My question is:

Is there come config change that is needed to see the correct claim? We are currently using v14.1.20191007.981.

(currently the ldapcp config is as follows: (Attached))

![LDAPCP](https://user-images.githubusercontent.com/20209171/68768843-4f111c00-05f1-11ea-95c7-694d81da1d8f.PNG)

(example: federated picker shows (sharepointadmins) and works LDAPCP shows ((Role) Sharepoint Admins) and does not work.

**Comment by Yvand** [comment]
@schrockmatthew when working with groups you need to be careful with their claim value.
As you can see in LDAPCP claim types mapping page, by default, LDAPCP uses prefix "{fqdn}\" for groups. It means that for each value it gets from LDAP server, it adds "domainFQDN\".
So it LDAP server returns "group1", LDAPCP creates permission "contoso.local\group1"
I don't know if this is the cause of your problem, but you need to compare the value of groups returned by your STS (ADFS) with the value set by LDAPCP. Both must match

**Comment by schrockmatthew** [comment]
It was {fqdn}\ in the prefix removal. Thanks for the reply

________________________________
