### ISSUE TITLE
Restrict people picker to lookup users with attribute

### ISSUE THREAD

**Issue by SaboorQuadri** [Yvand/LDAPCP#105]
Hi Yvand,

is there any possibility in LDAPCP to allow users to be looked up in people pickers from department attribute

**Comment by Yvand** [comment]
@SaboorQuadri yes, you can configure this in LDAPCP Claim types configuration page in central administration

**Comment by SaboorQuadri** [comment]
Hi Yvand, Thank you for your response. I tried to add below filter in "**Additional LDAP filter for user attributes**" and clicked on "Apply to all user attribute". Now, I am unable to get any user.

"(&(!(objectClass=computer))(division=Mydivision))"

I also tried keeping the textbix blank and "Apply to all user attribute" to revert however, that doesn't work. I tried by reset LDAPCP configuration, but no help.

**Comment by SaboorQuadri** [comment]
Hi Yvand,

Please ignore. I have fixed the issues by complete reset. additionally, I would like to add that, if above filter needs to be apply then we need to add a claimtype mapping in SPTrustedIdentityToken issuer as well as a claim rule in ADFS to have this working. I have tested and reached to this solution.
