### ISSUE TITLE
User added permission or to group creates a new account/duplicate account

### ISSUE THREAD

**Issue by fvibas** [Yvand/LDAPCP#106]
I have deployed LDAPCP and below is my configuration.
![image](https://user-images.githubusercontent.com/29219809/70226134-3bd61400-178b-11ea-843e-1063dd910452.png)

When I tried adding an existing user a permission it creates another account in the user information list, and when the user tried to access he is getting error the site is not yet shared.

**Comment by Yvand** [comment]
In the user information list, what is the "account name" of both users?

**Comment by fvibas** [comment]
Both have same account name but the account that is working has the department and position details. When click on the working account it goes to mysite page with url pattern 
/sites/mysite/Person.aspx?accountname=******, while the account that is not working goes to user information page with url pattern /_layouts/15/userdisp.aspx?ID=####
![image](https://user-images.githubusercontent.com/29219809/70303817-7a2b0c00-183b-11ea-96d1-03cc87d77801.png)

**Comment by fvibas** [comment]
I'm also encountering another weird issue  adding a user in site collection administrator getting this error in uls logs [LDAPCP] Validation failed: found 0 entities instead of 1 for incoming claim with value 'user@domain.com.sg' and type 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'

The account has a valid mysite profile and is able to sign in. I tried adding the email information but still the same error.

**Comment by Yvand** [comment]
We need to compare the actual account name of both accounts, which looks like 'i:0e.t|AzureAD|account@tenant.onmicrosoft.com'
Did you change the identifier claim type of Azure AD users?

**Comment by fvibas** [comment]
Hi Yvand,

Thanks for that I noticed that the existing working account has a format of 'i:05.t|adfs for sharepoint|ferdinand@synsgnet.com.sg' while the duplicate has a format of
'i:05.t|adfs for sharepoint|ferdinand@synsg.com.sg'. currently the user profiles are using email @synsg.com.sg but when users sign in they are using synsgnet.com.sq\username. 

Is there a way to update the configuration to change the email domain?

**Comment by fvibas** [comment]
I wanted to change the query to use UPN however it is not showing in green, is there anything I missed? I checked the token issuer for claim types and UPN is there.
![image](https://user-images.githubusercontent.com/29219809/70411505-64ad2080-1a8d-11ea-8943-c14c3bcbabd7.png)

**Comment by Yvand** [comment]
@fvibas sorry for the long delay.
In LDAPCP claims mapping page, the row in green corresponds to the identity claim type configured in the SPTrustedIdentityTokenIssuer. You cannot change the claim type in LDAPCP since it directly depends on the one you set in the SPTrustedIdentityTokenIssuer, but you can change the LDAP attribute if desired.

Regarding the email values, as far as SharePoint is concerned, 'i:05.t|adfs for sharepoint|ferdinand@synsgnet.com.sg' and 'i:05.t|adfs for sharepoint|ferdinand@synsg.com.sg' are 2 completely different users, like "user1" and "user2". You need to determine which one is issued by your STS, and only use that one

**Comment by Yvand** [comment]
Closing issue due to no response, feel free to reopen it if needed
