### ISSUE TITLE
Get Error "Sorry, you are not allowed to share this with external users"

### ISSUE THREAD

**Issue by mja-de** [Yvand/LDAPCP#107]
We installt LDAPCP 14.1 on SharePoint 2013. We connected to a ActiveDirectory Forrest. 

when I search for a user in the People Picker I get the error message "Sorry, you are not allowed to share this with external users"

I search for kxxxx@cos.com this is the value into the field "mail" 
ldapcp does not search in the "mail" field and we get the error messages

if I search for the value "kxxx@one.com", the account is found in the AD. The value is in the field" upn "

If I search vor name, the account is found. 

Only if i search for mail, we get the error. 

Value on AD site: 
mail="kxxxx@cos.com" -> search -> faild
upn="kxxx@one.com" -> search -> passed

on our LDAPCP Config, LDAPCP search only in the field "displayname; cn;sn;givenname and UPN) 

it is possible to configure ldapcp so that the "mail" field can also be searched

![image](https://user-images.githubusercontent.com/59538522/71784814-0033a180-2ff8-11ea-86fd-834ec585a096.png)

Greeting
Mario

**Comment by Yvand** [comment]
@mja-de your scenario is not clear:
Based on the screenshot the identity claim type is the UPN. By default, for this claim type LDAPCP uses LDAP attribute userPrincipalName. If you want to use LDAP attribute mail instead, you can change it in the page.

**Comment by mja-de** [comment]
Yes, the Identiy Claim ist UPN, but the Problem is to search form the attribute "Mail"

Szenarion:
If i type the value "kxxxx@cos.com" into the PeoplePicker, I get the error message. 

in my guess, because LDAPCP cannot find an account in AD. LDAPCP does not use the attribute "Mail" for the search in the AD.

if I enter the value "kxxx@one.com", the account is found and I do not receive an error message.

in my guess, because LDAPCP use the attribute "upn" (userpricipalname) form search and find. 

how can the attribute "mail" be configured for the search in AD?

Greeting
Mario

**Comment by Yvand** [comment]
@mja-de sorry for the late reply.
You need to add a new entry with type "Add a mapping between a LDAP object and the main corresponding object type". The LDAP class would be user and LDAP attribute "mail". The identity claim should remain with the UPN.

**Comment by Yvand** [comment]
Closing issue due to no response, feel free to reopen it if needed
