### ISSUE TITLE
After applying LDAP claim provider I am not able to add users to SharePoint groups.

### ISSUE THREAD

**Issue by GoudGanesh** [Yvand/LDAPCP#108]
Hi Yvand,

I go through the issue #96 reported.

I am also exactly facing same issue after we migrated SharePoint 2013 to SharePoint 2019.
In SharePoint 2013 we used LDAPCP claim provider and it worked perfectly with default ladap connection. We are using ADFS SAML token authentication. 

Where as in SP2019 I tried with newer version LDAP 14.1... but I am getting error while adding users to any SharePoint group after adding LDAP claim provider.

I followed the above conclusion in this thread. But I am still facing this issue. 
Error logs 
"Add" with "4" argument(s): "The user does not exist or is not unique."  
01/03/2020 06:13:28.84 	PowerShell_ISE.exe (AZWEUTBXSPW2019:0x2C40)	0x1CB4	LDAPCP                        	Claims Picking                	1337	Unexpected	[LDAPCP] Validation failed: found 0 entities instead of 1 for incoming claim with value 'ramur9' and type 'http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname'

Could you explain do i missing any thing here?
Thanks,
Ganesh

_Originally posted by @GoudGanesh in https://github.com/Yvand/LDAPCP/issues/96#issuecomment-570800671_

**Comment by Yvand** [comment]
Hi @GoudGanesh are you able to reproduce the same issue in a new site collection?

**Comment by GoudGanesh** [comment]
Hi Yvand,

Yes, we are experiencing the same issue in other site collections. 
We are using ADFS SAML authentication (SPTrustedIdentityTokenIssuer). 

Thanks,
Ganesh

**Comment by Yvand** [comment]
@GoudGanesh I didn't ask if you repro in others, but in a new one.
This is an important test, I suspect you will not repro in a new one

**Comment by GoudGanesh** [comment]
Hi Yvand,

Yes, Now I have created new site collection and trying to add user, there also getting the same error.

**Comment by Yvand** [comment]
Can you set LDAPCP logs in verbose and check the logs to get more details about the issue:
```
"LDAPCP:*"| Set-SPLogLevel -TraceSeverity Verbose
```

**Comment by GoudGanesh** [comment]
below are the log details:

[LDAPCP] Connecting to "LDAP://azweutbxad2019.ipp.local/CN=Uploader,CN=Users,DC=ipp,DC=local" with AuthenticationType "Secure, Signing, Sealing", authenticating with credentials "ipp\azureadmin" and sending a query with filter "(| (&(objectclass=user)(sAMAccountName=extgataa)(!(objectClass=computer))) )"...	55469d33-457d-0000-1777-62b107c5d501

[LDAPCP] Connecting to "LDAP://ipp.local/DC=ipp,DC=local" with AuthenticationType "Secure, Signing, Sealing", authenticating as process identity and sending a query with filter "(| (&(objectclass=user)(sAMAccountName=extgataa)(!(objectClass=computer))) )"...	 
[LDAPCP] Got 0 result(s) in 132ms from all servers with query "(| (&(objectclass=user)(sAMAccountName=extgataa)(!(objectClass=computer))) )"

[LDAPCP] Validation failed: found 0 entities instead of 1 for incoming claim with value 'extgataa' and type 'http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname'

**Comment by Yvand** [comment]
Somehow LDAP server does not return any result from this request:
```
"(| (&(objectclass=user)(sAMAccountName=extgataa)(!(objectClass=computer))) )"
```
Can you replay this query using [this PowerShell script](https://ldapcp.com/Troubleshoot-LDAPCP.html) and the information in the log?

**Comment by Yvand** [comment]
@GoudGanesh did you resolve the issue?
