### ISSUE TITLE
stsadm -o deleteconfigurationobject supportability concern

### ISSUE THREAD

**Issue by RGrizzzz** [Yvand/LDAPCP#109]
As a general FYI, running this command is a BIG RISK, and is UNSUPPORTED without a blessing from Microsoft support. There needs to be a warning on the fix issues page about this command. 
stsadm -o deleteconfigurationobject -id 5D306A02-A262-48AC-8C44-BDB927620227

Example: https://docs.microsoft.com/en-us/archive/blogs/okoestner/how-to-delete-a-timer-job-definition

It looks like the stsadm reference is no longer available.

**Comment by Yvand** [comment]
@RGrizzzz as a general best practice you are absolutely correct, but it does not apply here because '5D306A02-A262-48AC-8C44-BDB927620227' is the ID of the LDAPCP persisted object.
Deleting it only affects LDAPCP, not SharePoint, so it's 100% safe
