### ISSUE TITLE
Help for multiple TokenIssuer needed

### ISSUE THREAD

**Issue by okeol** [Yvand/LDAPCP#110]
Hi everyone, here is a small call for help  ;-)
We have a SharePoint 2019 attached to three active directories via ADFS and with three SPTrustedIdentityTokenIssuer.
Now we want to implement the lookup into all three AD via LDAPCP.
In the section "For developers" on ldapcp.com I found the line
    "Use LDAPCP with multiple SPTrustedIdentityTokenIssuer."
that suggests, it's possible. But the message after that
    "Each class inheriting LDAPCP is a unique claims provider, and only 1 can be installed at a time by the feature event receiver."
is one I dont understand.
In  [Issue#94](https://github.com/Yvand/LDAPCP/issues/94) it seems @tah78 has made it, but how? Has anyone a guidance/example/documentation for me to extend LDAPCP and how to deal with this event receiver line above?

That would be great!

Okeo

PS: And yes, after a long search, I found LDAPCP.Developers.zip (in release v11 and not in "[each release](https://ldapcp.com/For-Developers.html)" ;-)  and I found LDAPCP.custom but I could not find the answer to the event receiver....

@Yvand : Thanks for your project here! Your work is the reason I'm trying at least  ;-)

**Comment by tah78** [comment]
Hi @okeol, I downloaded and use LDAPCP solution without any adjusments to the source code. 

My environment:

- two active directories (intranet and extranet), each with one ADFS server 
- the SharePoint farm is placed in the extranet and only the extranet ADFS server is attached to the SharePoint Farm as SPTrustedIdentityTokenIssuer
- the extranet ADFS server is configured as relying party trust on the intranet ADFS server
- the intranet ADFS server in turn is configured as trusted claims provider at the extranet server

LDAPCP is configured to lookup into both ADs.

If you try to access a SharePoint site you will be redirected to the home realm discovery page on the external ADFS server, where you can choose your favorite ADFS server for logon.

It is working great.

Best regards tah78

**Comment by Yvand** [comment]
Hello,
Indeed, you cannot use LDAPCP with 2 SPTrustedIdentityTokenIssuer, this is actually due to a SharePoint limitation.
The solution is to use 2 flavors of LDAPCP: one is the pure standard one, the other is basically LDAPCP with a different, unique name (e.g. CustomLDAPCP). Each has its unique configuration (persisted object) and name.
I used to provide a zip that contained a sample project to illustrate how to do that, but I did not release it for a while. I will make if for the latest version and update this thread when it is available.

**Comment by okeol** [comment]
Thx, for replying!   I already found the ZIP and the class LDAPCP_Custom in it.
So we will try the flavors - extending to three of them.
But what about the note with the event receiver? 

> "Each class inheriting LDAPCP is a unique claims provider, and only 1 can be installed at a time by the feature event receiver."

What part of LDAPCP is limited by this?

**Comment by Yvand** [comment]
@okeol I just added "LDAPCP.Developers.zip" to [the latest release](https://github.com/Yvand/LDAPCP/releases/tag/14.1.20191007.981).
This goal of this statement is to explain that the sample project has 3 custom claims providers (3 classes), each showing a possible customization, but only one will be deployed by the feature receiver.
The feature receiver uses the values in class "CustomConfiguration" to determine which sample to install. You can check this class to understand how it's used.

**Comment by swinks** [comment]
Hi @Yvand, thank you for providing us your LDAPCP solution.

I created two seperate providers with their own unique GUIDs and configuration (LDAPCP_A.wsp and LDAPCP_B.wsp). After installing them on the server I have two seperatly configurable claims providers. Seems to work fine. 
But as I based my providers on your Developers sample, it seems that the current version of the ldapcp.dll from October 7th 2019 does not match with the configuration pages located in /admin/ldapcp_custom (8/2018) in the LDAPCP.Developers.zip.
The result is, that the property "IdProp" can't be found during databinding when opening the configuration page. Maybe it has been renamed to "Identifier" in the current version? At wich version was it changed and are there more changes in the code like that?
Do you have a best practices hint for me how and where to fix this? Thank you.

Regards,
Stefan

**Comment by Yvand** [comment]
Hi @swinks, indeed, I probably forgot that, thank you for letting me know.
I will check this soon and keep you posted

**Comment by Yvand** [comment]
Hi @swinks, you were right, I forgot to update the .aspx/.ascx files.
I just replaced LDAPCP.Developers.zip and you can download it [here](https://github.com/Yvand/LDAPCP/releases/download/14.1.20191007.981/LDAPCP.Developers.zip).

Note: to fix your custom project, you can simply copy the 4 .aspx/.ascx files (in folder ADMIN\LDAPCP_Custom) to your custom project and redeploy it.
