### ISSUE TITLE
High CPU utilization in LDAPCP module.

### ISSUE THREAD

**Issue by gjmjack** [Yvand/LDAPCP#111]
Recently we launched a new application in our SharePoint 2016 platform with ADFS and LDAPCP installed.
However on the first day we got a very high CPU (83% and above) utilization. After working with MS, they figure out that the application was stuck at the LDAPCP module. And below is the call stack from dump file.
00 ntdll!ZwWaitForMultipleObjects
01 KERNELBASE!WaitForMultipleObjectsEx
02 clr!WaitForMultipleObjectsEx_SO_TOLERANT
03 clr!Thread::DoAppropriateAptStateWait
04 clr!Thread::DoAppropriateWaitWorker
05 clr!Thread::DoAppropriateWait
06 clr!CLREventBase::WaitEx
07 clr!AwareLock::EnterEpilogHelper
08 clr!AwareLock::EnterEpilog
09 clr!AwareLock::Contention
0a clr!JITutil_MonContention
0b ldapcp!ldapcp.LDAPCP.Initialize(System.Uri, System.String[])
0c ldapcp!ldapcp.LDAPCP.GetClaimTypeForUserKey()
0d Microsoft_SharePoint!Microsoft.SharePoint.Administration.Claims.SPClaimUserKeyUtility.GetUserKeyClaimForTrusted(Microsoft.IdentityModel.Claims.IClaimsIdentity, Microsoft.SharePoint.Administration.Claims.SPClaim)
0e Microsoft_SharePoint!Microsoft.SharePoint.Administration.Claims.SPClaimUserKeyUtility.GetUserKeyClaim(Microsoft.IdentityModel.Claims.IClaimsIdentity, Microsoft.SharePoint.Administration.Claims.SPClaim)
0f Microsoft_SharePoint!Microsoft.SharePoint.Administration.Claims.SPClaimUserKeyUtility.GetUserKeyClaim(Microsoft.SharePoint.Administration.Claims.SPClaim)
10 Microsoft_SharePoint!Microsoft.SharePoint.Administration.Claims.SPClaimUserKeyUtility.GetUserKeyString(System.String)
11 Microsoft_SharePoint!Microsoft.SharePoint.Utilities.SPUtility.GetFullUserKeyFromLoginName(System.String)
12 Microsoft_SharePoint!Microsoft.SharePoint.SPSite.InitUserToken(Microsoft.SharePoint.Library.SPRequest)
13 Microsoft_SharePoint!Microsoft.SharePoint.SPSite.SPSiteConstructor(Microsoft.SharePoint.Administration.SPFarm, System.Guid, System.Guid, System.Guid, System.Guid, Microsoft.SharePoint.Administration.SPUrlZone, System.Uri, System.String, Boolean, Microsoft.SharePoint.SPUserToken, Boolean, System.String, System.String, System.String, System.String, System.Uri)
14 Microsoft_SharePoint!Microsoft.SharePoint.SPSite..ctor(Microsoft.SharePoint.Administration.SPFarm, System.Uri, Boolean, Boolean, Microsoft.SharePoint.SPUserToken)
15 Microsoft_SharePoint!Microsoft.SharePoint.Administration.SPSiteCollection.get_Item(System.String)
16 Microsoft_Office_Server_Search!Microsoft.Office.Server.Search.Administration.UrlMapper.GetNewCacheEntry(System.Tuple`3<System.Guid,Microsoft.SharePoint.Administration.SPUrlZone,System.String>)
17 Microsoft_Office_Server_Search!Microsoft.Office.Server.Search.Administration.UrlMapper.GetUrlMapping(Microsoft.Office.Server.Search.Query.QueryProperties, Boolean, Microsoft.Office.Server.Search.Administration.UrlZoneOverride)
18 Microsoft_Office_Server_Search!Microsoft.Office.Server.Search.Administration.SearchServiceApplicationProxy.UpdateQueryProperties(SsaOperationFlags, Microsoft.Office.Server.Search.Query.QueryProperties, Microsoft.SharePoint.Flighting.Runtime.VariantConfigurationSnapshot, Microsoft.SharePoint.SPContext)
19 Microsoft_Office_Server_Search!Microsoft.Office.Server.Search.Administration.SearchServiceApplicationProxy.GetQuerySuggestionsWithResults(Microsoft.Office.Server.Search.Query.QueryProperties, Int32, Int32, Boolean, Boolean, Boolean, Boolean)
1a Microsoft_Office_Server_Search!Microsoft.Office.Server.Search.Query.Query.GetQuerySuggestionsWithResults(Int32, Int32, Boolean, Boolean, Boolean, Boolean)
1b Microsoft_Office_Server_Search_ServerProxy_25e71030000!Microsoft.Office.Server.Search.Query.QueryServerStub.GetQuerySuggestionsWithResults_MethodProxy(Microsoft.Office.Server.Search.Query.Query, System.Xml.XmlNodeList, Microsoft.SharePoint.Client.ProxyContext)
1c Microsoft_SharePoint_Client_ServerRuntime!Microsoft.SharePoint.Client.ServerStub.InvokeMethodWithMonitoredScope(System.Object, System.String, System.Xml.XmlNodeList, Microsoft.SharePoint.Client.ProxyContext, Boolean ByRef)
1d Microsoft_SharePoint_Client_ServerRuntime!Microsoft.SharePoint.Client.ClientMethodsProcessor.InvokeMethod(System.Object, System.String, System.Xml.XmlNodeList, Boolean ByRef)
1e Microsoft_SharePoint_Client_ServerRuntime!Microsoft.SharePoint.Client.ClientMethodsProcessor.ProcessMethod(System.Xml.XmlElement)
1f Microsoft_SharePoint_Client_ServerRuntime!Microsoft.SharePoint.Client.ClientMethodsProcessor.ProcessStatements(System.Xml.XmlNode)
20 Microsoft_SharePoint_Client_ServerRuntime!Microsoft.SharePoint.Client.ClientMethodsProcessor.Process()
21 Microsoft_SharePoint_Client_ServerRuntime!Microsoft.SharePoint.Client.ClientRequestServiceImpl.ProcessQuery(System.IO.Stream, System.Collections.Generic.IList`1<System.IDisposable>)
22 Microsoft_SharePoint_Client_ServerRuntime!Microsoft.SharePoint.Client.ClientRequestService.ProcessQuery(System.IO.Stream)
23 System_ServiceModel!DynamicClass.SyncInvokeProcessQuery(System.Object, System.Object[], System.Object[])

Please help to look this issue. Many thanks.
**Product version:  11.0.0.0**

**Comment by Yvand** [comment]
@gjmjack the callstack shows that LDAPCP is waiting to enter a critical section, so this thread actually hangs, it's not consuming any CPU resources.
The good question would rather be why this thread is waiting. I assume that there is another LDAPCP thread which blocks this section, did you find it?
How did you fix the high CPU issue?

**Comment by gjmjack** [comment]
hi Yvand,
This issue hasn't fixed yet. We roll back the go-live.
Actually this result is come from Microsoft support.

**Comment by Yvand** [comment]
There is no known issue in LDAPCP that can explain either a hang or a 100% CPU.
The only hang I know about is [this one](https://github.com/Yvand/LDAPCP/issues/99) that I introduced in v14 and fixed quickly in v14.1.
I work at Microsoft Support, so you may suggest to the engineer who owns the case that he may contact me if needed.

**Comment by gjmjack** [comment]
hi Yvand
Finally it turns out it's a related code caused that issue. And the LDAPCP module hangs at the same location as well.
After fixing that issue the problem resolved.
Thanks

**Comment by Yvand** [comment]
Thank you for the update
