### ISSUE TITLE
Multiple Entries Found Cannot Add Certain User Objects

### ISSUE THREAD

**Issue by themp3master** [Yvand/LDAPCP#112]
[LDAPCP] Validation failed: found 2 entities instead of 1 for incoming claim with value 'test_user'

This triggers an exception in SharePoint stating that the username does not exist or is not unique.

It appears that my LDAPCP solutions is finding multiple entities on any site we create.

These user objects are not present on the existing site at all.

Any idea what might be causing this issue?

**Note:** we are using custom claims provider via our 3rd party IDP which pulls over user attributes via API call to display in the people picker.

**Note:** this does not happen to all attributes, only to those that look similar for example, test_user, test_usertest could trigger this behavior.

**Note:** We can replicate this on any existing site or newly created site.

**Comment by Yvand** [comment]
Hello, sorry for the so big delay, somehow I missed this issue
When you repro, can you check the SharePoint logs and filter on Product/Area "LDAPCP"?
It will show the users it returned.

**Comment by Yvand** [comment]
Closing issue due to no response, feel free to reopen it if needed
