### ISSUE TITLE
Forms Based Authentication

### ISSUE THREAD

**Issue by jokersplusone** [Yvand/LDAPCP#113]
I'm new to ldapcp and sharepoint 2019 and trying to solve the following.
Use LDAPCP to authenticate via the built in FBA ?
If so can someone help me out with some pointers or an example config

I've read through several write ups on on how to use ldap with FBA,. so i'm :"assuming" i just need to provide the correct values for "ASP.NET Membership provider name" and  "ASP.NET Role manager name"

thanks

**Comment by Yvand** [comment]
LDAPCP cannot be used with Forms Based Authentication, it can be used only with federated authentication, which is completely different.
