### ISSUE TITLE
AD Group MemberShip (Augmentation) with EmployeeID Attribute

### ISSUE THREAD

**Issue by ricorocca** [Yvand/LDAPCP#114]
Hello,

We use Shibboleth (SAML where user identify), adfs for claims and SharePoint 2016.
The claim user identity received in SharePoint is :  **i:0ǵ.t|custom-adfs|EmployeeID(Corresponding to AD User attribute)**
We can add/share user in SharePoint via LDAPC (Mapping to EmployeeID to AD).

But, AD security group augmentation not working with EmployeeID attribute, we can see in the SharPoint's logs that augmentation return 0 groups. (Working if a use SamAccountName or Email with SPWeb.DoesUserHavePermissions() )

My question is: Is there a way to make augmentation work with Employeeid ?

Thanks

**Comment by Yvand** [comment]
Hello,
Did you enable and configure augmentation in LDAPCP global configuration page (in central administration)?
Can you check the SharePoint logs while a user sign-in and filter on Product/Area "LDAPCP"?

**Comment by ricorocca** [comment]
Dear Yvan,

Augmentation is enable and works if my identifierclaim is emailaddress (during SPTrustedIdentityTokenIssuer creation).

**But, for EmployeeID:**

- Main "User" mapping WindowsAccountName (http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname) and LDAP attribute to query: employeeID.

- Main "Group" mapping http://schemas.microsoft.com/ws/2008/06/identity/claims/role , LDAP attribute to query : sAMAccountName,

- Augmentation parameters:
http://schemas.microsoft.com/ws/2008/06/identity/claims/role
LDAP Server "LDAP://domain.local:389"
Check Query this server and Use .NET helper (for Active Directory only)

In this 2nd configuration, i can add user to site Collection Administrator and connect to site...

But if i remove the user from administrator group and connect to site (With AD security group configured in SharePoint Site to authorized user), it didn't work.

LOGS:
[LDAPCP] Got and processed 0 group(s) for user "USER123456" in 6 ms from AD domain "domain.local" (authenticate as "domain\SERVICEACCOUNT" with AuthenticationType "SimpleBind").
[LDAPCP] No group found for user 'USER123456' during augmentation

Thank you for your help!!!!

**Comment by Yvand** [comment]
Ok, to understand what goes wrong, we need to look deeper at the logs:
Between those 2 messages:

```
[LDAPCP] Getting AD groups of user...
[LDAPCP] No group found for user...
```

You should find the following SPMonitoredScope messages (they are verbose messages recorded in product/area "SharePoint Foundation" and category "Monitoring"):

```
Entering monitored scope ([LDAPCP] Get AD Principal of user...
Entering monitored scope ([LDAPCP] Get group membership of...
Entering monitored scope ([LDAPCP] Process XX AD groups returned for user...
```

Can you copy them?

**Comment by ricorocca** [comment]
Dear Yvan,

You will find all the logs from "C:\Program Files\Common Files\microsoft shared\Web Server Extensions\16\LOGS" during the session with sensitive data change:
[LogsYvanD.txt](https://github.com/Yvand/LDAPCP/files/4509188/LogsYvanD.txt)

But i didn't find the exact logs requested. Maybe i have to increase verbosity, how can i do?

Thank you again for your help and product

**Comment by Yvand** [comment]
Category "Monitoring" should be in verbose and product/area "LDAPCP" in verboseEx.

**Comment by ricorocca** [comment]
Please, get logs below:

[LogsYvanD_2.txt](https://github.com/Yvand/LDAPCP/files/4510173/LogsYvanD_2.txt)

During my different test, if a test with:

Main "User" mapping WindowsAccountName (http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname) and LDAP attribute to query: **samaccountName** ---> **OK**
(Attibute value receive by OID 1 Shibboleth, corresponding to samaccountname in ldapcp target AD)

and

Main "User" mapping WindowsAccountName (http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname) and LDAP attribute to query: **employeeID** ---> **NOK**
(Attibute value receive by OID 2 Shibboleth, corresponding to employeeid in ldapcp target AD)

Maybe it's limitation with membership in AD?

Thank you.

**Comment by Yvand** [comment]
With current configuration, LDAPCP calls [UserPrincipal.FindByIdentity()](https://docs.microsoft.com/en-us/dotnet/api/system.directoryservices.accountmanagement.userprincipal.findbyidentity?view=netframework-4.8) to get the identity of the user but it doesn't find it, probably because it doesn't query the employee id attribute.

Instead, in LDAPCP global configuration page > augmentation section: You should uncheck the option "Use .NET helper (for Active Directory only)" next to the LDAP connection.
It should fix the augmentation but it will only get the direct group membership of the users (not netsted groups)

**Comment by ricorocca** [comment]
Dear Yvan,

That's work if a uncheck the option "Use .NET helper (for Active Directory only)".

`LDAPCP] Got 22 group(s) for user "USER123456" in 439 ms from LDAP server "LDAP://domain.local:389" with LDAP filter "(&(ObjectClass=user) (employeeID=USER123456)(!(objectClass=computer)))" (authenticate as "domain.local\userserviceldapcp" with AuthenticationType "None").`

But i have to deal with nested group.

Thank you for your help!!!! You make a great job!!!
