### ISSUE TITLE
Strange Behaviour  with ADFS/LDAPCP

### ISSUE THREAD

**Issue by HubertChomette** [Yvand/LDAPCP#115]
Hi,
We have an Sharepoint 2019 farm on premise. Our main  Webapplication  use ADFS  authentification ( just Windows on Default Zone,  just ADFS on main zone).
We  use ldapcp for people picker and to provide augmentation too.
We have an issue  on email notification. 
If I share an object to 3 persons,  email are sent randomly. For example, 2 persons could have a notification, or 3. There is no logic.
We have  notified than users appears  differently when the notification failed. A user with " a normal icon" will receive the notification. A user with " a group icon " won't.
Do we have make a mistake on our configuration? Does ldapcp can interract on this bug?
Thank's for your help

**Comment by Yvand** [comment]
It can. There are 2 scenarios:
- User is added for the 1st time to the site collection: email used to send invitation is determined by LDAPCP.
- User already exists in the site collection (in UserInfo list): email used to send invitation is determined by his local profile, synchronized by the User Profile Application.

To determine the guilty component, I suggest you try to repro in a new test site collection.
Also, if you set LDAPCP logs to verboseEx like this:

```
"LDAPCP:*"| Set-SPLogLevel -TraceSeverity VerboseEx
```

Then the logs will record the email (relevant only if user is added for the 1st time to the site collection):

```
04/20/2020 17:13:56.21	w3wp.exe (0x1F9C)	0x0D54	LDAPCP	Claims Picking	1337	VerboseEx	[LDAPCP] Set metadata 'Email' of new entity to 'yvand@conto2016.local'	3fa54a9f-99f1-4003-37ac-5e75d7176454
04/20/2020 17:13:56.21	w3wp.exe (0x1F9C)	0x0D54	LDAPCP	Claims Picking	1337	Verbose	[LDAPCP] Added entity: display text: 'yvand@conto2016.local', claim value: 'yvand@conto2016.local', claim type: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'	3fa54a9f-99f1-4003-37ac-5e75d7176454
```

**Comment by HubertChomette** [comment]
Thank’s a lot for this. I will try.
And thank’s a lot for this product.

**Comment by HubertChomette** [comment]
Hi,
The issue was on the User Profile Application. We reconfigure synchronisation and email notifcation seem's to work.
AS a consequence, we have got a new issue.
 - User name seem's to have change. As a consequence, access based on group on site collection are broken. In a new Site collection, it's ok. How do we force sync or reset group on site collection?
Another question, why do a mail notification on an external account (not on our AD) always work even if email aren't  indicated on User profile Application.
Thank's a lot for your help

**Comment by Yvand** [comment]
@HubertChomette If the new issue is still present, can you please open a new issue for it?
