### ISSUE TITLE
SharePoint 2019 - Error Deployng LDAPCP Solution

### ISSUE THREAD

**Issue by robal1968** [Yvand/LDAPCP#116]
I'm trying to deploy the latest LDACP relaese on a new SharePoint 2019 Farm, with two Application servers and two front end servers.
I get always this error:
[machinename]: An update conflict has occurred, and you must re-try this action. The object SPClaimEncodingManager Name=ClaimEncodingManager was updated by [user], in the powershell_ise (12212) process, on machine [machinename].  View the tracing log for more information about the conflict.
--
i run a powershell script like this 
Add-SPSolution -LiteralPath "F:\Data\Dev\LDAPCP.wsp"
Install-SPSolution -Identity "LDAPCP.wsp" -GACDeploymentn

**Comment by Yvand** [comment]
Sorry for the delay. It's very likely that it occurred because you executed those commands on a PowerShell process that was opened a long time ago.
Did you fix the issue?

**Comment by robal1968** [comment]
Yes, thanks. Was exactly that issue.

Regards,
Roberto

Il giorno lun 4 mag 2020 alle ore 18:42 Yvan Duhamel <
notifications@github.com> ha scritto:
