### ISSUE TITLE
SharePoint 2013 - Added Servers To Farm - whole solution stopped working.

### ISSUE THREAD

**Issue by markkjacobs** [Yvand/LDAPCP#117]
Yvan,
Unbeknownst to me, our SP 2013 Farm has your solution installed (ldapcp).  I added 6 new server to the farm and for some reason your solution stopped working anywhere.  Would appreciate any help.  Yes, have looked at ldapcp.com and github.  This is a bit urgent.  Thanks in advance,  Mark

**Comment by Yvand** [comment]
@markkjacobs the first thing to check is the LDAPCP logs: can you filter SharePoint logs on Product/Area "LDAPCP" and check if there are errors?

**Comment by markkjacobs** [comment]
@Yvand Thanks for helping.  I am having my admin take a look right now.
We extracted ldapcp.dll from our current install and added to GAC on Servers but that did not clear up these errors.  We have engaged MS Services also, but that is not going anywhere yet.  

As soon as I get more error info, will attach.

![ldapcp error](https://user-images.githubusercontent.com/20458916/80963200-14d04c80-8dd4-11ea-9dc1-4b9810ff2d90.jpg)

**Comment by markkjacobs** [comment]
I was having filtering issues, so grabbed a whole dump..let me know if not enough info?
[logdump084am05042020.zip](https://github.com/Yvand/LDAPCP/files/4575023/logdump084am05042020.zip)

**Comment by markkjacobs** [comment]
![ldapacp05032020](https://user-images.githubusercontent.com/20458916/80973255-c24b5c00-8de4-11ea-820b-d9ae73ca40ce.png)

**Comment by markkjacobs** [comment]
![image](https://user-images.githubusercontent.com/20458916/80986045-a13f3700-8df5-11ea-9864-0deecaa92aed.png)
current look.

**Comment by Yvand** [comment]
On the servers where the error is thrown, is ldapcp.dll actually present in the GAC, and with the expected version?
If not, you can add it manually using the [PowerShell script here](https://ldapcp.com/Install-LDAPCP.html)

**Comment by markkjacobs** [comment]
We added it to the GAC.  We have stopped being unable to log in to the site on the servers, but the WSP report still looks like the above grab.

**Comment by Yvand** [comment]
Yes the timer job failed and the status won't update unless you try to redeploy the solution, but you shouldn't do it: if the assembly is in the GAC, nothing else is needed (I assume the features were deployed successfully).
Did it happen when you updated or installed LDAPCP?

**Comment by markkjacobs** [comment]
See at the bottom 5 of the 6 new servers say "successfully deployed" though above the dll error persists and the dll has been added to the GAC on each server.

**Comment by Yvand** [comment]
Understood, then there is nothing else to do and the error can be safely ignored, since the DLL was added manually

**Comment by markkjacobs** [comment]
@Yvand 
Here's where I stand:

Success:
SVPEXTSPIEFE1 : The solution was successfully deployed.
SVPEXTSPIEFE3 : The solution was successfully deployed. 
SV**R**EXTSPIEFE1 : The solution was successfully deployed. 
SVPEXTSPIEFE2 : The solution was successfully deployed. 
SVPEXTSPIEAPP2 : The solution was successfully deployed. 
SVPEXTSPIEAPP1 : The solution was successfully deployed. 
SVPEXTSPIEAPP3 : The solution was successfully deployed. 
SV**R**EXTSPIEAPP1 : The solution was successfully deployed.

Error:
Each Listed 2x.
SVREXTSPIEAPP1 : Error: Cannot add the specified assembly to the global assembly cache: ldapcp.dll. 
SVREXTSPIEAPP1 : Error: Cannot add the specified assembly to the global assembly cache: ldapcp.dll. 
SVREXTSPIEFE2 : Error: Cannot add the specified assembly to the global assembly cache: ldapcp.dll. 
SVREXTSPIEFE2 : Error: Cannot add the specified assembly to the global assembly cache: ldapcp.dll. 
SVREXTSPIEAPP2 : Error: Cannot add the specified assembly to the global assembly cache: ldapcp.dll. 
SVREXTSPIEAPP2 : Error: Cannot add the specified assembly to the global assembly cache: ldapcp.dll. 
SVREXTSPIEFE3 : Error: Cannot add the specified assembly to the global assembly cache: ldapcp.dll. 
SVREXTSPIEFE3 : Error: Cannot add the specified assembly to the global assembly cache: ldapcp.dll. 
SVREXTSPIEAPP3 : Error: Cannot add the specified assembly to the global assembly cache: ldapcp.dll. 
SVREXTSPIEAPP3 : Error: Cannot add the specified assembly to the global assembly cache: ldapcp.dll.


As you can see, the errored Servers are listing them selves twice (that might be an 80/443 thing).

Please note third Letter P and **R**.  R's are the added Servers and as you can see, 2 of the 6 say they are successful.

Also, note, SV**R**EXTSPIEAPP1 shows both Error and Successful.

I personally added the .DLL to the GAC this AM on SVREXTSPIEFE2 - restart IIS, and AppPool.  
Cannot Browse to Security Token Service (80 or 443).

So, still need help!

**Comment by Yvand** [comment]
@markkjacobs - what do you see in SharePoint logs when you try to generate a SAML token using the PowerShell script?
You establish a correlation between the error in the solution deployment page and this issue, but I tend to think that the former is a false positive. Indeed, LDAPCP.dll is clearly correctly added to the GAC since you did it and double checked it

**Comment by markkjacobs** [comment]
> @markkjacobs - what do you see in SharePoint logs when you try to generate a SAML token using the PowerShell script?
> You establish a correlation between the error in the solution deployment page and this issue, but I tend to think that the former is a false positive. Indeed, LDAPCP.dll is clearly correctly added to the GAC since you did it and double checked it.
> 
> Side note: LDAPCP.dll should always be added to the GAC of all SharePoint servers members of the farm (except the SQL servers)

I'll have to check logs.  I know the DLL is on all servers except SQL.
Just troubleshooting as best I can.

**Comment by markkjacobs** [comment]
from new server
![image](https://user-images.githubusercontent.com/20458916/81716911-8b59f380-943f-11ea-99fc-17d6461e9de1.png)


from server before add
![image](https://user-images.githubusercontent.com/20458916/81717033-b2182a00-943f-11ea-84d5-f29123a031a9.png)

**Comment by markkjacobs** [comment]
@Yvand 
OK.  Still says error, even though it also says this now
![image](https://user-images.githubusercontent.com/20458916/81721352-5d77ad80-9445-11ea-91af-ce927e40d8a4.png)

**Comment by Yvand** [comment]
Instead of filtering on area LDAPCP, can you filter the SharePoint logs on process PowerShell when you run the PowerShell script?

**Comment by markkjacobs** [comment]
@Yvand 
Finally here after a force redeploy.  I think you can close this as an issue now.  Thank you for your help and responsiveness.

![image](https://user-images.githubusercontent.com/20458916/82455281-633e4600-9a78-11ea-8fdc-ef2041b6dc77.png)
