### ISSUE TITLE
SharePoint 2016 - multiple entries

### ISSUE THREAD

**Issue by pressplej** [Yvand/LDAPCP#118]
I get multiple entries of the same user in People Picker. 
When I hover: I can see that one is from DisplayName and one is from mail. Both coming from ADFS

**Comment by Yvand** [comment]
It probably returns a result per claim type mapping configured in LDAPCP. You can update/remove this mapping in central admin > security > LDAPCP claim type mappings

**Comment by pressplej** [comment]
OK. But the claim types should match those set in SPTrustedIdentityTokenIssuer

**Comment by Yvand** [comment]
Absolutely, in the claims mapping page, the claim types in green do match those set in SPTrustedIdentityTokenIssuer

**Comment by pressplej** [comment]
Ok, but what should i remove?

**Comment by Yvand** [comment]
You can remove the claim types you don't want to see in the people picker.
There is no best practice, it entirely depends on your requirements. The only one to always keep is the identity claim type, which is why LDAPCP won't let you remove it

**Comment by Yvand** [comment]
Closing issue due to no response, feel free to reopen it if needed
