### ISSUE TITLE
Sharepoint 2019 - LDACP strange behaviour with groups

### ISSUE THREAD

**Issue by HubertChomette** [Yvand/LDAPCP#119]
Hi, 
We have a strange behaviour with groups (from augmentation).

Users comes from ADFS and claims provide groups membership (marked as role).
Groups comes from ldapcp which populate this group with role claims.

If I allow a "role group" to modify a document, it works. All users can access and modify. Permission seem's to be ok.

If I purpose to coediting the document with Office online, it fails. User can see the document, begin edition and an error message blocks all edition, random time.
If I check autorisation from Site Collection authorization, users has no authorisation.

Any idea?

I try to run the powershell script (imagine that user Jim has the issue on the Site Collection test) on a user which have issue.

$cs = [Microsoft.SharePoint.Administration.SPWebService]::ContentService
$cs.TokenTimeout = New-TimeSpan -Minutes 1
$cs.Update()
$web = Get-SPWeb "http://spsites/test"
$logon = "i:05.t|contoso.local|jim@contoso.local"
$web.DoesUserHavePermissions($logon, [Microsoft.SharePoint.SPBasePermissions]::EditListItems)

**Comment by Yvand** [comment]
Did you enable and configure augmentation in LDAPCP global configuration page?

**Comment by HubertChomette** [comment]
yes augmentation is enable with 'role'.
Use .NET helper is checked
LDAPCP 14.1.20191007.981

**Comment by Yvand** [comment]
Can you enable LDAPCP logs in verbose:

```
"LDAPCP:*"| Set-SPLogLevel -TraceSeverity Verbose
```

Then you can follow section "Troubleshoot augmentation" in https://ldapcp.com/Troubleshoot-LDAPCP.html to collect data

**Comment by HubertChomette** [comment]
Ok, I will try.
I make a test to understand.
First step:
I have an AD group with two users.
On a SP using standard auth (AD), If I share the site directly to the group, it works for both users.
On this SP using adfs/ldacp, If I share the site directly to the group, it doesn't work. 
On my configuration, should I make the same type of synchronisation (user profile, sync) with groups?

**Comment by HubertChomette** [comment]
Here is a capture of the mapping configuration
<img width="1525" alt="Capture d’écran 2020-06-02 à 09 45 51" src="https://user-images.githubusercontent.com/11505100/83494009-ebc7d800-a4b5-11ea-9060-d3db28bf69b0.png">

**Comment by HubertChomette** [comment]
I try to enable debug

First type of error:

06/01/2020 12:09:24.07 	w3wp.exe (MYSERVER-WEB:0x1EE8)          	0x1330	LDAPCP                        	Augmentation                  	1337	Unexpected	[LDAPCP] Unexpected error occurred while getting AD groups of user "eric.martin@mydomain.fr" using UserPrincipal.GetAuthorizationGroups() from AD domain "ad.mydomain.fr" (authenticate as "process identity" with AuthenticationType "SimpleBind, Signing, Sealing"). This is likely due to a bug in .NET framework in UserPrincipal.GetAuthorizationGroups (as of v4.6.1), especially if user is member (directly or not) of a group either in a child domain that was migrated, or a group that has special (deny) entities.: System.DirectoryServices.AccountManagement.PrincipalOperationException: Une erreur (5) s'est produite lors de la tentative de récupération des groupes d'autorisations., Callstack:    à System.DirectoryServices.AccountManagement.AuthZSet..ctor(Byte[] userSid, NetCred credentials, ContextOptions contextOptions, String flatUserAuthority, StoreCtx userStoreCtx, Object userCtxBase)     à System.DirectoryServices.AccountManagement.ADStoreCtx.GetGroupsMemberOfAZ(Principal p)     à System.DirectoryServices.AccountManagement.UserPrincipal.GetAuthorizationGroupsHelper()     à ldapcp.LDAPCP.GetGroupsFromActiveDirectory(LDAPConnection ldapConnection, OperationContext currentContext, ClaimTypeConfig groupCTConfig)	9893a3e9-f519-4165-b8a8-d7a2cd5981dc

**Comment by HubertChomette** [comment]
Second Type of error:

06/02/2020 10:06:36.69 	w3wp.exe (MYSERVER-WEB:0x0FA0)          	0x1E14	LDAPCP                        	Core                          	1337	Medium	[LDAPCP] Configuration 'LdapcpConfig' version 2581935 was found, but local copy is not fully initialized. Refreshing local copy...	e363589f-e1c6-b0f3-e054-3d7cc7b01a97

06/02/2020 10:06:36.69 	w3wp.exe (MYSERVER-WEB:0x0FA0)          	0x1E14	LDAPCP                        	Configuration                 	1337	Unexpected	[] Unexpected error occurred while getting domain names information for LDAP connection LDAP://ad.mydomain.fr/DC=ad,DC=mydomain,DC=fr (DirectoryServicesCOMException): System.DirectoryServices.DirectoryServicesCOMException: Une erreur d’opération s’est produite.  , Callstack:    à System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)     à System.DirectoryServices.DirectoryEntry.Bind()     à System.DirectoryServices.DirectoryEntry.get_AdsObject()     à System.DirectoryServices.PropertyCollection.Contains(String propertyName)     à ldapcp.OperationContext.GetDomainInformation(DirectoryEntry directory, String& domaindistinguishedName, String& domainName, String& domainFQDN)	e363589f-e1c6-b0f3-e054-3d7cc7b01a97

**Comment by HubertChomette** [comment]
Ok I modify configuration and remove default AD and add a new ldap query

Here is the log 
Connecting to "LDAP://ad.mydomain.fr" with AuthenticationType "None", authenticating with credentials "cn=services,People,dc=ad,dc=mydomain,dc=fr" and sending a query with filter "(| (&(objectclass=group)(sAMAccountName=test debug)) )"...	fa6f589f-f150-b0f3-e054-373849cc500c
06/02/2020 13:38:12.70 	w3wp.exe (MYSERVER-WEB:0x0FA0)          	0x2660	LDAPCP                        	LDAP Lookup                   	1337	Medium	[LDAPCP] Got 1 result(s) in 0ms from 'LDAP://ad.mydomain.fr/DC=ad,DC=mydomain,DC=fr' with filter '(| (&(objectclass=group)(sAMAccountName=test debug)) )'	ff6f589f-216f-b0f3-e054-3a4969c9c8cd
06/02/2020 13:38:12.70 	w3wp.exe (MYSERVER-WEB:0x0FA0)          	0x1420	LDAPCP                        	LDAP Lookup                   	1337	Medium	[LDAPCP] Got 1 result(s) in 1ms from 'LDAP://ad.mydomain.fr' with filter '(| (&(objectclass=group)(sAMAccountName=test debug)) )'	fa6f589f-f150-b0f3-e054-373849cc500c
06/02/2020 13:38:12.70 	w3wp.exe (MYSERVER-WEB:0x0FA0)          	0x2660	LDAPCP                        	LDAP Lookup                   	1337	Verbose	[LDAPCP] Got 2 result(s) in 2ms from all servers with query "(| (&(objectclass=group)(sAMAccountName=test debug)) )"	ff6f589f-216f-b0f3-e054-3a4969c9c8cd
06/02/2020 13:38:12.70 	w3wp.exe (MYSERVER-WEB:0x0FA0)          	0x2660	LDAPCP                        	LDAP Lookup                   	1337	Medium	[LDAPCP] 1 entity(ies) to create after filtering	ff6f589f-216f-b0f3-e054-3a4969c9c8cd
06/02/2020 13:38:12.70 	w3wp.exe (MYSERVER-WEB:0x0FA0)          	0x2660	LDAPCP                        	Claims Picking                	1337	High	[LDAPCP] Validated entity: display text: '(Role) TEST DEBUG', claim value: 'TEST DEBUG', claim type: 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role'	ff6f589f-216f-b0f3-e054-3a4969c9c8cd

it seem's to be ok. But user can't access.

**Comment by Yvand** [comment]
The error message "This is likely due to a bug in .NET framework in UserPrincipal.GetAuthorizationGroups..." may be the correct explanation: On the servers where you get this error, what is the version of "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll"?

In the last comment I guess you unchecked the box "Use .NET helper". In the logs you see the exact value of the claims generated for the roles. Does it match the value you set in the people picker?

**Comment by HubertChomette** [comment]
version 4.7.3620.0

For the last comment I suspect that user running ldacp doesn't have access to the attribute on the directory. So I add a new directory access (define as ldap even if it's an active directory, which can permit the right account to use and byse this .NET
But my user still hasn't access to my site test (authorization are done on a AD group).

**Comment by Yvand** [comment]
The output from the logs suggests that it worked fine. Can you:
- Copy the output of the logs where a group is successfully added to the user token
- Copy the corresponding group permission, which should look like "c:0-.t|contoso.local|contoso.local\administrators"
Comparing the 2 should help to understand the issue

**Comment by HubertChomette** [comment]
Sorry I don t post the end.
My first issue was with .NET fixed with a standard ldap connexion instead of active directory link.
the second one was with the account which wasn t allowed to read member of on our active directory.
All is ok now.
thanks a lot for your help


--
Hubert
