### ISSUE TITLE
Issue of people picker for site collection admin. in Sharepoint Central Administrative System

### ISSUE THREAD

**Issue by a4n0nym0u5** [Yvand/LDAPCP#12]
Since I am using your claim prvoider LDAPCP, after I have installed it, it causes error (cannot pick the role or even pick UPN) when I use people picker to set the site collection administrator of my webapp in  SharePoint Central Administrative site.  However, the people picker works (could pick role) when I set the permission inside site permission inside the web app. But, I can't set the site collection administrator.

So, is it a bug or is it possible to solve it?

**Comment by Yvand** [comment]
Can you check the SharePoint logs and filter on Product/Area "LDAPCP"?
It should give you more insight on what's happening.

**Comment by Yvand** [comment]
@a4n0nym0u5 any update on this?

**Comment by Yvand** [comment]
Closing since author didn't reply
