### ISSUE TITLE
ldapcp, ADFS and Office Online Server

### ISSUE THREAD

**Issue by khalilG** [Yvand/LDAPCP#121]
Hi @Yvand ,

I need your point of view for my case.

We have the following infrastructure and configuration :
- SharePoint 2016 servers
- ADFS server for SSO : ( a custom Trusted Identity Token Issuer )
- Office Online Server

What we did : 
- Create a new web app that have another trusted identity token issuer that has LDAPCP as claimprovider
- Configure the new web app with the new trusted identity provider 
![image](https://user-images.githubusercontent.com/8361028/84051296-37dfb480-a9af-11ea-928e-7eda165003a3.png)

The problem we're facing : 
- In order for the new web app sites to authenticate through the new trusted identity provider, we needed to add the "?trust=LDAPCPConnect" param to the "Custom sign in page url"
![2020-06-08 17_40_29-Window](https://user-images.githubusercontent.com/8361028/84051449-7a08f600-a9af-11ea-9127-b0edf2c6c51a.png)
- Once the param added, the sign is experience works perfectly. However, when we try to open an Excel or Word file on the desktop app, a blank authentication form appears and authentication process is blocked.
- If we remove the "?trust=LDAPCPConnect" param, Excel and Word files opens successfully on desktop apps but web app sites won't authenticate through "LDAPCPConnect" trusted identity provider.

Any idea on how to fix this problem ? If not, do you have any workaround ?

Thanks in advance.

**Comment by Yvand** [comment]
@khalilG indeed, you should not use this approach to force the login mode, it has side effects like the one you noticed.
Instead, you should add a custom login page to bypasse the default one and force users to use the authN mode of your choice. You can take a look at https://github.com/Yvand/SPBypassLoginPage, which deploys such page

**Comment by salagula** [comment]
If you just enable the "Trusted identity provider" as seen in your screenshot you can select the "default sign in page". Or do you need to support additionally Forms / Windows-integrated authentication on the same web application? We normally use: web app only with SAML + a extended web app with Windows-integrated (e.g. for search crawling)

**Comment by khalilG** [comment]
> If you just enable the "Trusted identity provider" as seen in your screenshot you can select the "default sign in page". Or do you need to support additionally Forms / Windows-integrated authentication on the same web application? We normally use: web app only with SAML (with default signin page) + a extended web app with Windows-integrated (e.g. for search crawling)

@salagula : Thanks for the reply, I'm testing this solution now and try to validate that there are no side effects.

**Comment by khalilG** [comment]
> @khalilG indeed, you should not use this approach to force the login mode, it has side effects like the one you noticed.
> Instead, you should add a custom login page to bypasse the default one and force users to use the authN mode of your choice. You can take a look at https://github.com/Yvand/SPBypassLoginPage, which deploys such page

Hi @Yvand ,
We've decided to install your custom solution. Everything seemed to be working fine and we had no issue with Office Online Server. However, after setting up the custom sign in page to "/_login/Bypass/BypassLogin.aspx" and configuring the "CustomBypassLogin" farm property (as descried at [https://github.com/Yvand/SPBypassLoginPage](https://github.com/Yvand/SPBypassLoginPage) , search crawl stopped working correctly with the following error : 

> Access is denied. Verify that either the Default Content Access Account has access to this repository, or add a crawl rule to crawl this repository. If the repository being crawled is a SharePoint repository, verify that the account you are using has "Full Read" permissions on the SharePoint Web Application being crawled.

Any idea how to fix this ?

Thanks.

**Comment by Yvand** [comment]
@khalilG this custom page should have no effect at all on the search crawler access.
Can you confirm that crawler starts working immediately after you revert to default page?
