### ISSUE TITLE
Custom Solution Inheriting LDAPCP not being recognized in Central Admin SharePoint 2019

### ISSUE THREAD

**Issue by ktodd1** [Yvand/LDAPCP#122]
We have a custom solution inheriting LDACP that works correctly in SharePoint 2013. When deploying to SharePoint 2019, the solution appears to install and deploy correctly and can associate with Trusted Provider in Powershell. However, when going to Central Admin, it shows only LDAPCP being registered, missing our custom extension. It also states that LDAPCP is not associated with a trusted provider, which is correct, because our custom extension is associated with the trusted provider.

**Comment by Yvand** [comment]
@ktodd1 is the corresponding farm feature for your custom claims provider activated?
Is the custom claims provider returned when you run `Get-SPClaimProvider`?

**Comment by ktodd1** [comment]
@Yvand Yes it shows as activated and is returned. I can associate it with the trusted provider, but in Central Admin it is looking for LDAPCP to associated and not our custom extension. See screen shots please. Thanks!
![image](https://user-images.githubusercontent.com/8646873/84930315-ece83000-b085-11ea-823d-e322a7028e03.png)
![image](https://user-images.githubusercontent.com/8646873/84930393-0c7f5880-b086-11ea-87a8-37d593d36962.png)
![image](https://user-images.githubusercontent.com/8646873/84930435-202abf00-b086-11ea-8401-00fc7fdc3eb2.png)
![image](https://user-images.githubusercontent.com/8646873/84930489-38024300-b086-11ea-9179-0981268b5a70.png)
![image](https://user-images.githubusercontent.com/8646873/84930551-57996b80-b086-11ea-939e-3dfffbf84f85.png)

**Comment by Yvand** [comment]
As shown in [LDAPCP.Developers](https://github.com/Yvand/LDAPCP/releases/download/14.1.20191007.981/LDAPCP.Developers.zip), the LDAPCP administration pages must contain the information about the custom claims provider.
For example, in LdapcpSettings.aspx:

```
<Ldapcp:GlobalSettings ID="LdapcpGlobalSettings" Runat="server" ClaimsProviderName="<%# CustomConfiguration.ClaimsProviderName %>" PersistedObjectName="<%# CustomConfiguration.CONFIG_NAME %>" PersistedObjectID="<%# CustomConfiguration.CONFIG_ID %>" />
```

Do they have this information in your environment?

**Comment by ktodd1** [comment]
@Yvand that was the issue! The value for ClaimsProviderName was incorrect. Thanks!
