### ISSUE TITLE
UserAccountDirectoryPath is ignored?

### ISSUE THREAD

**Issue by larkoize** [Yvand/LDAPCP#123]
Hi Yvand!
I need users only from a specific OU for a site collection and OU varies between site collections. It seems that LDAPCP is ignoring an SPSite's _UserAccountDirectoryPath_ property. Is this true? If yes, is there any other way to set a specific OU for site collection. I'm using LDAPCP 14.1.20191007.981 and SharePoint 2019.

Set-SPSite -Identity http://portal.contoso.com/sites/US -UserAccountDirectoryPath "OU=US,OU=SharePoint,DC=Contoso,DC=com"

**Comment by Yvand** [comment]
@larkoize you are correct, LDAPCP does not rely on property UserAccountDirectoryPath.
Due to limitations of SharePoint API, LDAPCP has no reliable way to determine the current site collection fore sure in all scenarios, so unfortunately, there is no solution for your issue...
