### ISSUE TITLE
Connect to other domain

### ISSUE THREAD

**Issue by arzusah** [Yvand/LDAPCP#124]
Hi there,
I have the following setup:
A SharePoint 2019 farm with a colab-portal and a mysite-portal.
It has two User Profile Service connections setup. Both uses Trusted Identity Claim Provider to sync users from different domain.
Lets call them:
- SharePoint.local
- External.com

After installing LDAPCP I get results from sharepoint.local domain which the SharePoint servers are connected to.
I then added ldap://external.com domain in hope that the people picker would resolve external users awell, but unfortunately not. People picker only shows the sharepoint.local domain users.

When I try to invite a user from external.com, I am presented with the errormessage:
"This site cannot be shared with external users" even tho I have activated the functionality to share the site from "site settings -> users and groups -> settings for access requests"
I removing LDAPCP from the trustedidentityprovider to verify that this functionality works, and it does.

The user profile service works fine tho. I can see that all the users are synched fine. 
Do you have any pointers for me to go on? 

Also: Is there a way to get LDAPCP to only show users from the OU that the UPA is synchronizing? 
Grateful for any input on this issue :) (and sorry if this question seems stupid, Im a ldap novice...)

Best regards Mathias

**Comment by Yvand** [comment]
Hi @arzusah
- User Profile service does not play any role in the user authorization flow. You can actually remove it and it will not change anything to the way you grant permissions.
- By default, LDAPCP queries the AD the SharePoint server belongs to, but this can be customized in central admin > security > LDAPCP global config page. From here you can define a new LDAP connection and restrict its path to a specific OU.
- You should always assign LDAPCP to only 1 trustedidentityprovider. If you assign it to 0 or several, it will not work.

**Comment by arzusah** [comment]
Thanks for the reply!

So if I understand you correctly, peopleplicker will only resolve users from one domain when using ldapcp?
If thats the case, I will only be able to invite users from one of the two domains :/

Can you guide me to how I can filter to a specific OU?

**Comment by Yvand** [comment]
No, you can add as many LDAP domains as you need in LDAPCP.
To filter to a specific OU, you just need to include the OU to the path, for example: `LDAP://XXXX.YYY/OU=Users,DC=XXXX,DC=YYY`

**Comment by arzusah** [comment]
aaah sweet, thanks :) I will try it out.

Something seems to be missing tho. None of the users in external.com domain is searchable in peopleplicker.
There is no trust between the domains. I have only opened port 389 and 636 between the SharePoint servers and the external domain controllers. "Test LDAP connection" works fine. Could there be other ports involved here, or have I configured ldapcp wrong somehow? Both connections are identical, just pointing to different domains.

Im also very intrested in using role claims for giving access to my site.
Say for example: "If user belongs to group "SharePoint Access", then grant user access. I imagine I could add "SharePoint Access (role claim) to the visitors-group. But role-claim is not showing in peoplepicker. I suppose I have to activate augmentation? If so - how do I go about solving the problem? :)
Thanks for helping me out!!

**Comment by Yvand** [comment]
LDAPCP records all its activity in SharePoint logs and looking at them will probably give you a lot of insight about what is going on.
Filter the logs on product/area "LDAPCP" and let me know if it helps.

**Comment by arzusah** [comment]
Hello Yvand! 
I had a look in the logs and discovered the following error:

[LDAPCP] Unexpected error occurred while connecting to LDAP server LDAP://company.com/OU=users,DC=company,DC=com: System.Runtime.InteropServices.COMException: The server is not operational.  , Callstack:   
 at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)    
 at System.DirectoryServices.DirectoryEntry.Bind()    
 at System.DirectoryServices.DirectoryEntry.get_AdsObject()    
 at System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne)    
 at ldapcp.LDAPCP.<>c__DisplayClass43_0.<QueryLDAPServers>b__1(LDAPConnection ldapConnection)

I solved the problem by checking the following in the ldap connection: "secure", "signing" and "sealing" :) Didn't know the two last one was needed.

Peoplepicker now shows users from both domain <3 Thank you!

**Comment by ShivaCharan20** [comment]
Hi Yvan’s,
thanks for your reply. Before firewall open to external domain AD connection was not successful. We opened firewall and in central admin I try to test connection with external LDAP., connection is successful. 
however when I try to search users in people picker getting below error in SharePoint logs.

LDAPCP
LDAP Lookup
1337
Unexpected
TLDAPCP1 Unexpected error occurred while connecting to
LDAP server LDAP://external domain.com: System.Runtime.InteropServices.COMException: The server is not operational.
Callstack:
at
System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
at System.DirectoryServices.DirectorvEntrv.Bind()
at
System.DirectoryServices.DirectoryEntry.get_Adsobject()
at System.DirectoryServices.DirectorySearcher.FindAll(BooleanfindMoreThanone)
at ldapcp.LDAPCP.<›c_ DisplayClass43 _0. ‹QueryLDAPServers›b_ 1 (LDAPConnection ldapConnection)
4bb201a0-1163-605a-e996-e39c2e6cf885

could you please help what could be the issue.
Thanks

**Comment by Yvand** [comment]
@ShivaCharan20 can you use [this PowerShell script](https://www.ldapcp.com/docs/help/troubleshooting/#replay-ldap-queries) to check if it reproduces the same error, or if it is able to return results?
Please not that to do a good test, you must use the same parameters as the connection you set in LDAPCP

**Comment by ShivaCharan20** [comment]
Hi Yvand,
I try given powershell script in one of our APP01 server it is returning the results for which fw is open, where as when I execute the script in wfe02 server., it’s giving “The server is not operational”. WFE02 server firewall is not open to external domain server.
When I check SP logs LAPCP logs are only getting captured in WFE02 server. 
Do I need to open firewall in all the servers?
And can I configure UPS with trusted identity provider.
Please let me know.
Thanks,
Shiva

**Comment by Yvand** [comment]
Hi @ShivaCharan20, yes, all SharePoint servers must be allowed to communicate with the external LDAP server.
Yes, you can configure UPS with your trusted identity provider, but that is not related to this discussion and not related to LDAPCP

**Comment by ShivaCharan20** [comment]
Hi Yvan Dhuamel,
Thanks for your reply., let me try and update you. Just checking any possibility on UPS (I will try on that as well).
Thanks,
Shiva
