### ISSUE TITLE
LDAPS path not working

### ISSUE THREAD

**Issue by khalilG** [Yvand/LDAPCP#125]
Hi Yvan,
This is more a question than an issue.
We are trying to connect LDAPCP a remote AD that's not on the same domain as SharePoint.
We're using the LDAPS protocol. 

We've tried the possible combination, none of them worked. The combinations are as follows : 
- LDAP**S**://<remote_server_ip>
- LDAP**S**://<remote_server_ip>/DC=<domain1>,DC=<domain2>
- LDAP**S**://<remote_server_ip>**:636**
- LDAP**S**://<remote_server_ip>**:636**/DC=<domain1>,DC=<domain2>
Removing the 'S' from LDAP : 
- LDAP://<remote_server_ip>:**636**
- LDAP://<remote_server_ip>:**636**/DC=<domain1>,DC=<domain2>

We also tried these combinations with the check-boxes "Secure", "Sealed", "Encryption" and "Signing".
Only the following path worked : 
LDAP://<remote_server_ip> or LDAP://<remote_server_ip>:389

The questions is : does LDAPCP supports LDAPS protocol ?

Thanks.
Khalil.

**Comment by Yvand** [comment]
It's a good question, I don't think I ever formally tested it but I think it should work:
LDAPCP fully relies on .NET DirectoryServices API to connect to the LDAP server, which I hope supports LDAPS

**Comment by khalilG** [comment]
> It's a good question, I don't think I ever formally tested it but I think it should work:
> LDAPCP fully relies on .NET DirectoryServices API to connect to the LDAP server, which I hope supports LDAPS

Thank you @Yvand for your answer. I'll let you know if it worked for us or not.

**Comment by khalilG** [comment]
Hi @Yvand .

We've tried everything (at least I hope) and LDAPCP seems to be incompatible with LDAPS.
Can you or someone else try to test the LDAPS protocol with LDAPCP ? This may be related to our infrastructure.

Thank you in advance.

**Comment by Yvand** [comment]
hi @khalilG, I trust your tests are correct, so indeed it seems that LDAPCP doesn't work with LDAPS.
LDAPCP relies entirely on .NET DirectoryServices API, so the limitation is probably on this API.
[This page](https://ldapcp.com/Troubleshoot-LDAPCP.html) is a PowerShell version of what LDAPCP does. If you can get LDAPS to work with PowerShell, I may do the necessary changes in LDAPCP.

**Comment by khalilG** [comment]
Hu @Yvand , thank you for the reply. I'll try with the PowerShell version of LDAPCP and let you know if it worked or not.
