### ISSUE TITLE
Question: Role claim configuration

### ISSUE THREAD

**Issue by arzusah** [Yvand/LDAPCP#126]
Dear Ywan,
I reach out to you once again for your input.
Building on the scenario I described in #124 

The SharePoint farm and external users are in Domain 1
The internal users are in Domain 2

I want to give read access for all internal users in Domain 2 by adding a Role Claim to the SharePoint visitors-group.
If user have role-claim "R-App-SharePoint" then grant permission.

ADFS is currently configured
ADFS server “adfs-domain2.com”, have a rule that adds role-claim with value "R-App-SharePoint" if user is member of "DOMAIN2\R-App-Sharepoint" on relying party "fs.domain2.com"

On relying party “fs.domain2.com” the following is configured:
1. Added rule on claim providers to "adfs.domain2.com" that all role-claims that starts with "R-App-SharePoint" shall be forwarded.
2. Added rule on relying party "sharepoint.domain2.com" that it shall forward all role-claims with value "R-App-SharePoint" (This is the RP that is used as URN in SharePoint)

The reason for this configuration is because we do not want to send all groups as claims, as external users could see them.

I have activated Augmentation in global configuration, but peopepicker does not resolve role claim "R-App-SharePoint". I was hoping to add this claim to the visitors-group. 

Augmetation activated: (not sure what .net-helper is but activated it just in case...)
![image](https://user-images.githubusercontent.com/67652786/89396953-825f8200-d70f-11ea-86ef-460014a705dc.png)

Trying to add role claim to visitors gorup (Norwegian:)
![image](https://user-images.githubusercontent.com/67652786/89397497-36f9a380-d710-11ea-9ddc-74e409058808.png)

Would this setup work? :/ 
Really appreciate your help. I'm a ldap noob!

**Comment by Yvand** [comment]
Hi @arzusah, can you check the SharePoint logs and filter on Product/Area “LDAPCP" while you reproduce the issue?
It will show you what goes wrong in LDAPCP

**Comment by arzusah** [comment]
I get two entries when reproducing

Leaving Monitored Scope: ([LDAPCP] Connecting to "LDAP://domain2.com/OU=employees=domain2,DC=domain2,DC=com" with AuthenticationType "Secure, Signing, Sealing", authenticating with credentials "sa-sp-sync" and sending a query with filter "(&(!(userAccountControl:1.2.840.113556.1.4.803:=2))(| (&(objectclass=user)(mail=R-App-Sha*)) (&(objectclass=group)(sAMAccountName=R-App-Sha*)(groupType:1.2.840.113556.1.4.803:=2147483648)) (&(objectclass=user)(displayName=R-App-Sha*)) (&(objectclass=user)(cn=R-App-Sha*)(!(objectClass=computer))) (&(objectclass=user)(sn=R-App-Sha*)) (&(objectclass=user)(givenName=R-App-Sha*)) (&(objectclass=group)(displayName=R-App-Sha*)(groupType:1.2.840.113556.1.4.803:=2147483648)) ))"...) Execution Time=14998.9654; CPU Milliseconds=2; SQL Query Count=0; Parent=None

Leaving Monitored Scope: ([LDAPCP] Total time spent in all LDAP server(s)) Execution Time=14999.4012; CPU Milliseconds=1; SQL Query Count=0; Parent=SPClaimProvider.FillSearch()

**Comment by arzusah** [comment]
Without LDAPCP installed I get all the claims in peoplepicker that is forwarded from ADFS. UPN, Email and Role claims.
The Peoplepicker now only seems to be searching for objects in AD? 

As described earlier, ADFS rule basically says:
"IF you belong to group R-App-SharePoint THEN send string "R-App-SharePoint" as roleclaim

Do you have any idea how I can add that roleclaim to a SharePoint group?
Thanks :)

**Comment by Yvand** [comment]
@arzusah you're not viewing the messages you should, I'm not sure if you did a mistake with the filtering or if logs are decativated.
Just in case, can you run this command and check the logs again:
`"LDAPCP:*"| Set-SPLogLevel -TraceSeverity Verbose`

You should see messages that look like the ones [in this page](https://ldapcp.com/Troubleshoot-LDAPCP.html)

**Comment by arzusah** [comment]
Tried logging out and in and got the logs now

[LDAPCP] User 'arzusah@domain2.com' was augmented with 16 groups

**Comment by arzusah** [comment]
Here are the complete logs

`08/06/2020 10:53:02.25	w3wp.exe (0x19BC)	0x1FC8	SharePoint Foundation	Monitoring	b4ly	High	Leaving Monitored Scope: ([LDAPCP] Get AD Principal of user arzusah@domain2.no from AD domain "domain2.local" (authenticate as "sa-sp-profile" with AuthenticationType "SimpleBind, Signing, Sealing").) Execution Time=15126.5866; CPU Milliseconds=3; SQL Query Count=0; Parent=[LDAPCP] Get AD groups of user "arzusah@domain2.no" from AD domain "domain2.local" (authenticate as "sa-sp-profile" with AuthenticationType "SimpleBind, Signing, Sealing").	5d526d9f-bdf8-0091-7d3d-29c33fd42e63
08/06/2020 10:53:02.25	w3wp.exe (0x19BC)	0x1FC8	LDAPCP	Augmentation	1337	Unexpected	[LDAPCP] Unexpected error occurred while getting AD groups of user "arzusah@domain2.no" using UserPrincipal.GetAuthorizationGroups() from AD domain "domain2.local" (authenticate as "sa-sp-profile" with AuthenticationType "SimpleBind, Signing, Sealing"). This is likely due to a bug in .NET framework in UserPrincipal.GetAuthorizationGroups (as of v4.6.1), especially if user is member (directly or not) of a group either in a child domain that was migrated, or a group that has special (deny) entities.: System.DirectoryServices.DirectoryServicesCOMException: A more secure authentication method is required for this server.  , Callstack:    at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)     at System.DirectoryServices.DirectoryEntry.Bind()     at System.DirectoryServices.DirectoryEntry.get_SchemaEntry()     at System.DirectoryServices.AccountManagement.ADStoreCtx.IsContainer(DirectoryEntry de)     at System.DirectoryServices.AccountManagement.ADStoreCtx..ctor(DirectoryEntry ctxBase, Boolean ownCtxBase, String username, String password, ContextOptions options)     at System.DirectoryServices.AccountManagement.PrincipalContext.CreateContextFromDirectoryEntry(DirectoryEntry entry)     at System.DirectoryServices.AccountManagement.PrincipalContext.DoLDAPDirectoryInit()	5d526d9f-bdf8-0091-7d3d-29c33fd42e63
08/06/2020 10:53:02.27	w3wp.exe (0x19BC)	0x1FC8	LDAPCP	Augmentation	1337	Medium	[LDAPCP] Got 16 group(s) for user "arzusah@domain2.no" in 12 ms from LDAP server "LDAP://domain2.local/OU=Cloud Synced,OU=Ansatte,OU=domain2,DC=domain2,DC=local" with LDAP filter "(&(ObjectClass=user) (mail=arzusah@domain2.no))" (authenticate as "sa-sp-profile" with AuthenticationType "Secure, Signing, Sealing").	5d526d9f-bdf8-0091-7d3d-29c33fd42e63
08/06/2020 10:53:02.27	w3wp.exe (0x19BC)	0x1FC8	LDAPCP	Augmentation	1337	Medium	[LDAPCP] Got and processed 0 group(s) for user "arzusah@domain2.no" in 15139 ms from AD domain "domain2.local" (authenticate as "sa-sp-profile" with AuthenticationType "SimpleBind, Signing, Sealing").	5d526d9f-bdf8-0091-7d3d-29c33fd42e63
08/06/2020 10:53:02.27	w3wp.exe (0x19BC)	0x1FC8	SharePoint Foundation	Monitoring	b4ly	High	Leaving Monitored Scope: ([LDAPCP] Get AD groups of user "arzusah@domain2.no" from AD domain "domain2.local" (authenticate as "sa-sp-profile" with AuthenticationType "SimpleBind, Signing, Sealing").) Execution Time=15139.996; CPU Milliseconds=5; SQL Query Count=0; Parent=None	5d526d9f-bdf8-0091-7d3d-29c33fd42e63
08/06/2020 10:53:02.27	w3wp.exe (0x19BC)	0x1FC8	LDAPCP	Augmentation	1337	Medium	[LDAPCP] User 'arzusah@domain2.no' was augmented with 16 groups	5d526d9f-bdf8-0091-7d3d-29c33fd42e63
08/06/2020 10:54:10.64	w3wp.exe (0x1888)	0x1550	SharePoint Foundation	Monitoring	b4ly	High	Leaving Monitored Scope: ([LDAPCP] Connecting to "LDAP://domain2.local/OU=Cloud Synced,OU=Employees,OU=domain2,DC=domain2,DC=local" with AuthenticationType "Secure, Signing, Sealing", authenticating with credentials "sa-sp-profile" and sending a query with filter "(&(!(userAccountControl:1.2.840.113556.1.4.803:=2))(| (&(objectclass=user)(mail=r-app*)) (&(objectclass=group)(sAMAccountName=r-app*)(groupType:1.2.840.113556.1.4.803:=2147483648)) (&(objectclass=user)(displayName=r-app*)) (&(objectclass=user)(cn=r-app*)(!(objectClass=computer))) (&(objectclass=user)(sn=r-app*)) (&(objectclass=user)(givenName=r-app*)) (&(objectclass=group)(displayName=r-app*)(groupType:1.2.840.113556.1.4.803:=2147483648)) ))"...) Execution Time=15017.1269; CPU Milliseconds=3; SQL Query Count=0; Parent=None	61526d9f-5dc8-0091-7d3d-256c46ce77d5
08/06/2020 10:54:10.64	w3wp.exe (0x1888)	0x06D0	SharePoint Foundation	Monitoring	b4ly	High	Leaving Monitored Scope: ([LDAPCP] Total time spent in all LDAP server(s)) Execution Time=15017.6141; CPU Milliseconds=4; SQL Query Count=0; Parent=SPClaimProvider.FillSearch()	6e526d9f-1daf-0091-7d3d-2f84dde1b75a
08/06/2020 10:54:11.12	w3wp.exe (0x1888)	0x116C	SharePoint Foundation	Monitoring	b4ly	High	Leaving Monitored Scope: ([LDAPCP] Connecting to "LDAP://domain2.local/OU=Cloud Synced,OU=Employees,OU=domain2,DC=domain2,DC=local" with AuthenticationType "Secure, Signing, Sealing", authenticating with credentials "sa-sp-profile" and sending a query with filter "(&(!(userAccountControl:1.2.840.113556.1.4.803:=2))(| (&(objectclass=user)(mail=r-app-*)) (&(objectclass=group)(sAMAccountName=r-app-*)(groupType:1.2.840.113556.1.4.803:=2147483648)) (&(objectclass=user)(displayName=r-app-*)) (&(objectclass=user)(cn=r-app-*)(!(objectClass=computer))) (&(objectclass=user)(sn=r-app-*)) (&(objectclass=user)(givenName=r-app-*)) (&(objectclass=group)(displayName=r-app-*)(groupType:1.2.840.113556.1.4.803:=2147483648)) ))"...) Execution Time=15001.4488; CPU Milliseconds=2; SQL Query Count=0; Parent=None	6d526d9f-cda0-0091-7d3d-203f24e4be41
08/06/2020 10:54:11.12	w3wp.exe (0x1888)	0x05AC	SharePoint Foundation	Monitoring	b4ly	High	Leaving Monitored Scope: ([LDAPCP] Total time spent in all LDAP server(s)) Execution Time=15001.8705; CPU Milliseconds=1; SQL Query Count=0; Parent=SPClaimProvider.FillSearch()	6e526d9f-4dcc-0091-7d3d-28ed02c3e38a
08/06/2020 10:54:13.35	w3wp.exe (0x1888)	0x02AC	SharePoint Foundation	Monitoring	b4ly	High	Leaving Monitored Scope: ([LDAPCP] Connecting to "LDAP://domain2.local/OU=Cloud Synced,OU=Employees,OU=domain2,DC=domain2,DC=local" with AuthenticationType "Secure, Signing, Sealing", authenticating with credentials "sa-sp-profile" and sending a query with filter "(&(!(userAccountControl:1.2.840.113556.1.4.803:=2))(| (&(objectclass=user)(mail=r-app-domain2-sharepoint*)) (&(objectclass=group)(sAMAccountName=r-app-domain2-sharepoint*)(groupType:1.2.840.113556.1.4.803:=2147483648)) (&(objectclass=user)(displayName=r-app-domain2-sharepoint*)) (&(objectclass=user)(cn=r-app-domain2-sharepoint*)(!(objectClass=computer))) (&(objectclass=user)(sn=r-app-domain2-sharepoint*)) (&(objectclass=user)(givenName=r-app-domain2-sharepoint*)) (&(objectclass=group)(displayName=r-app-domain2-sharepoint*)(groupType:1.2.840.113556.1.4.803:=2147483648)) ))"...) Execution Time=14987.1902; CPU Milliseconds=2; SQL Query Count=0; Parent=None	5d526d9f-add0-0091-7d3d-2818f6383fa2
08/06/2020 10:54:13.35	w3wp.exe (0x1888)	0x1C24	SharePoint Foundation	Monitoring	b4ly	High	Leaving Monitored Scope: ([LDAPCP] Total time spent in all LDAP server(s)) Execution Time=14987.676; CPU Milliseconds=2; SQL Query Count=0; Parent=SPClaimProvider.FillResolve()	6f526d9f-0d5a-0091-7d3d-23394b04eaf1
`

**Comment by Yvand** [comment]
w3wp.exe (0x1888) doesn't show any LDAPCP logging message (and its the one we want to see), and this log shows that you didn't set the filter correctly: I thnk you set message contains LDAPCP instead of product/area contains LDAPCP.

Can you recycle this app pool and double check your filter?

**Comment by arzusah** [comment]
Ok, here we go :)
Verbose logs when logging in to SharePoint filtered to "category" in ULSviewer

08/06/2020 11:24:13.94	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Core	1337	Medium	[LDAPCP] Configuration 'LdapcpConfig' changed to version 1116225, refreshing local copy	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:13.94	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Core	1337	Verbose	[LDAPCP] Refreshing local copy of configuration 'LdapcpConfig'	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.12	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] Starting augmentation for user 'arzusah@domain.no'.	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.12	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] Getting AD groups of user "arzusah@domain.no" from AD domain "domain.local" (authenticate as "sa-sp-profile" with AuthenticationType "SimpleBind, Signing, Sealing").	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.13	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Unexpected	[LDAPCP] Unexpected error occurred while getting AD groups of user "arzusah@domain.no" using UserPrincipal.GetAuthorizationGroups() from AD domain "domain.local" (authenticate as "sa-sp-profile" with AuthenticationType "SimpleBind, Signing, Sealing"). This is likely due to a bug in .NET framework in UserPrincipal.GetAuthorizationGroups (as of v4.6.1), especially if user is member (directly or not) of a group either in a child domain that was migrated, or a group that has special (deny) entities.: System.DirectoryServices.DirectoryServicesCOMException: A more secure authentication method is required for this server.  , Callstack:    at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)     at System.DirectoryServices.DirectoryEntry.Bind()     at System.DirectoryServices.DirectoryEntry.get_SchemaEntry()     at System.DirectoryServices.AccountManagement.ADStoreCtx.IsContainer(DirectoryEntry de)     at System.DirectoryServices.AccountManagement.ADStoreCtx..ctor(DirectoryEntry ctxBase, Boolean ownCtxBase, String username, String password, ContextOptions options)     at System.DirectoryServices.AccountManagement.PrincipalContext.CreateContextFromDirectoryEntry(DirectoryEntry entry)     at System.DirectoryServices.AccountManagement.PrincipalContext.DoLDAPDirectoryInit()	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.13	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] Getting LDAP groups of user "arzusah@domain.no" from LDAP server "LDAP://domain.local/OU=Cloud Synced,OU=Ansatte,OU=domain,DC=domain,DC=local" with LDAP filter "(&(ObjectClass=user) (mail=arzusah@domain.no))" (authenticate as "sa-sp-profile" with AuthenticationType "Secure, Signing, Sealing").	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.15	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Medium	[LDAPCP] Got 16 group(s) for user "arzusah@domain.no" in 5 ms from LDAP server "LDAP://domain.local/OU=Cloud Synced,OU=Ansatte,OU=domain,DC=domain,DC=local" with LDAP filter "(&(ObjectClass=user) (mail=arzusah@domain.no))" (authenticate as "sa-sp-profile" with AuthenticationType "Secure, Signing, Sealing").	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.15	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Medium	[LDAPCP] Got and processed 0 group(s) for user "arzusah@domain.no" in 25 ms from AD domain "domain.local" (authenticate as "sa-sp-profile" with AuthenticationType "SimpleBind, Signing, Sealing").	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.15	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] LDAP queries to get group membership on all servers completed in 32ms	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.15	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] Added group 'domain.local\Group1', claim type 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' to user 'arzusah@domain.no'	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.15	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] Added group 'domain.local\Group2', claim type 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' to user 'arzusah@domain.no'	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.15	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] Added group 'domain.local\R-App-Sharepoint', claim type 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' to user 'arzusah@domain.no'	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.15	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] Added group 'domain.local\Group4', claim type 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' to user 'arzusah@domain.no'	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.15	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] Added group 'domain.local\Group5', claim type 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' to user 'arzusah@domain.no'	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.15	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] Added group 'domain.local\Group6', claim type 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' to user 'arzusah@domain.no'	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.15	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] Added group 'domain.local\Group7', claim type 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' to user 'arzusah@domain.no'	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.15	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] Added group 'domain.local\Group8', claim type 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' to user 'arzusah@domain.no'	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.15	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] Added group 'domain.local\Group9', claim type 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' to user 'arzusah@domain.no'	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.15	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] Added group 'domain.local\Group10', claim type 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' to user 'arzusah@domain.no'	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.15	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] Added group 'domain.local\Group11', claim type 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' to user 'arzusah@domain.no'	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.15	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] Added group 'domain.local\Group12', claim type 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' to user 'arzusah@domain.no'	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.15	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] Added group 'domain.local\Group13', claim type 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' to user 'arzusah@domain.no'	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.15	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] Added group 'domain.local\Group14', claim type 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' to user 'arzusah@domain.no'	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.15	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] Added group 'domain.local\Group15', claim type 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' to user 'arzusah@domain.no'	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.15	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] Added group 'domain.local\Group16', claim type 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' to user 'arzusah@domain.no'	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.15	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Augmentation	1337	Medium	[LDAPCP] User 'arzusah@domain.no' was augmented with 16 groups	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.16	w3wp.exe (0x1B60)	0x1B34	LDAPCP	Rehydration	1337	Verbose	[LDAPCP] Return user key for user "0e.t|adfs domain|arzusah@domain.no"	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.44	w3wp.exe (0x0FA8)	0x269C	LDAPCP	Core	1337	Medium	[LDAPCP] Configuration 'LdapcpConfig' changed to version 1116225, refreshing local copy	29546d9f-5d39-0091-7d3d-2d5dc81a245d
08/06/2020 11:24:29.44	w3wp.exe (0x0FA8)	0x269C	LDAPCP	Core	1337	Verbose	[LDAPCP] Refreshing local copy of configuration 'LdapcpConfig'	29546d9f-5d39-0091-7d3d-2d5dc81a245d

**Comment by arzusah** [comment]
And when searching for role claim:

[LDAPCP] Connecting to "LDAP://domain.local/OU=Employees=Domain,DC=domain,DC=local" with AuthenticationType "Secure, Signing, Sealing", authenticating with credentials "sa-sp-profile" and sending a query with filter "(&(!(userAccountControl:1.2.840.113556.1.4.803:=2))(| (&(objectclass=user)(mail=R-App-SharePoint*)) (&(objectclass=group)(sAMAccountName=R-App-SharePoint*)(groupType:1.2.840.113556.1.4.803:=2147483648)) (&(objectclass=user)(displayName=R-App-SharePoint*)) (&(objectclass=user)(cn=R-App-SharePoint*)(!(objectClass=computer))) (&(objectclass=user)(sn=R-App-NHN-SharePoint*)) (&(objectclass=user)(givenName=R-App-NHN-SharePoint*)) (&(objectclass=group)(displayName=R-App-SharePoint*)(groupType:1.2.840.113556.1.4.803:=2147483648)) ))"

[LDAPCP] Got 0 result(s) in 15020ms from all servers with query "(&(!(userAccountControl:1.2.840.113556.1.4.803:=2))(| (&(objectclass=user)(mail=R-App-SharePoint*)) (&(objectclass=group)(sAMAccountName=R-App-SharePoint*)(groupType:1.2.840.113556.1.4.803:=2147483648)) (&(objectclass=user)(displayName=R-App-SharePoint*)) (&(objectclass=user)(cn=R-App-SharePoint*)(!(objectClass=computer))) (&(objectclass=user)(sn=R-App-SharePoint*)) (&(objectclass=user)(givenName=R-App-SharePoint*)) (&(objectclass=group)(displayName=R-App-SharePoint*)(groupType:1.2.840.113556.1.4.803:=2147483648)) ))"

**Comment by Yvand** [comment]
So there is no error, but LDAP server took 15 seconds (this is huge) to respond, and returned no result.
I guess you expected some replies, so you can replay the LDAP query outside of SharePoint / LDAPCP to troubleshoot it using the script [in this page](https://ldapcp.com/Troubleshoot-LDAPCP.html).

**Comment by arzusah** [comment]
Hello Yvand,
Yeah, 15 sec is very long... Not sure why it takes so long, but I'll have to look at it.

Regarding "I guess you expected some replies". Yes and no.
As I said earlier, I have only connected the OU with users. No groups should be searchable.
I do not want to add a AD group to the SharePoint group. I want to add a role claim with the same name as a SharePoint group.

According to the logs, the group "R-App-SharePoint" was augmented to my profile. Shouldn't it therefore be searchable as a claim in peoplepicker? Sorry for my stupid questions and thanks for your help :-)

**Comment by arzusah** [comment]
Ok, so I have solved the problem by adding the role claim via PowerShell

`$web = Get-SPWeb "https://sharepoint.com"
$claim = New-SPClaimsPrincipal -TrustedIdentityTokenIssuer “ADFS” -ClaimValue “R-App-SharePoint" -ClaimType “http://schemas.microsoft.com/ws/2008/06/identity/claims/role“
$group = $web.Groups[“Visitors“]
$group.AddUser($claim.ToEncodedString(), “”, “R-App-SharePoint", “”)`

But I still wonder if the claim should be searchable via peoplepicker. Would be practical to be able to search for roles via peoplepicker. E.g. "managers" "superusers". 
But if its not possible, then everything is OK.

**Comment by Yvand** [comment]
It's absolutely possible to search roles for this claim type in the people picker.
Do you see the claim type you added (http://schemas.microsoft.com/ws/2008/06/identity/claims/role) listed in central admin > Security > LDAPCP Claim types configuration page?
