### ISSUE TITLE
PeoplePicker not showing ADFS identities

### ISSUE THREAD

**Issue by bfran00** [Yvand/LDAPCP#127]
Hey,
I configured a SP2019 Farm for ADFS. Without LDAPCP the peoplepicker will show the AD itentity, UPN, EMail and Role, which is expected.
So I wanted to get rid of some things and installed LDAPCP, like in other server farms.
But after the configuration with the PowerShell script, the peoplepicker will only show AD identities.
`$trust = Get-SPTrustedIdentityTokenIssuer "ADFS"
$trust.ClaimProviderName = "LDAPCP"
$trust.Update()`

I did not change any settings, it's the default configuration

**Comment by Yvand** [comment]
Can you check if the claim types in your SPTrustedIdentityTokenIssuer match the claim types configured by default by LDAPCP?
You can see them at central admin > security > LDAPCP Claim types configuration.
If they don't match you need to add them here

**Comment by bfran00** [comment]
Well, I found the issue and I was a bit stupid.
I forgot that our SharePoint Servers are in a different domain than our user accounts. After I added the LDAP connection in the global settings, it started working.
