### ISSUE TITLE
Extend PeoplePicker Information

### ISSUE THREAD

**Issue by camel028** [Yvand/LDAPCP#128]
Hi @Yvand 
I would like to extend a main claim (DisplayName) with an email underneath so I would like to get the results to be as follows after the search:

user_name
mail
user2_name
mail2
user3_name
mail3

So far I've achieved as below:
user_name
user2_name
user3_name
...

Is it possible to extend a main claim with some extra information within LDAPCP configuration?

Is it related to ShowClaimNameInDisplayText attribute? How can I define how exactly a search result entry is presented to the user as in my case I need e.g. 

camel028 user - **this is taken from displayName attribute**
mymail@gmail.com - **this is taken from emailaddress attribute**

Thanks in advance.

**Comment by Yvand** [comment]
You can configure this in central admin > security > LDAPCP Claim types configuration page:
Basically, the 2nd line will show whatever is set with the "PickerEntity metadata" column set with the "Title" property

**Comment by camel028** [comment]
Hi,

Thanks for reply.

I have something as below:

![image](https://user-images.githubusercontent.com/3504518/90397082-9bfdb380-e097-11ea-8918-4ab1bbbfea8b.png)

and when I am trying to add JobTitle then I got the error:

![image](https://user-images.githubusercontent.com/3504518/90397025-86888980-e097-11ea-86ff-26912fb70129.png)

Could you please write how it should be configured correctly?
Many thanks!

**Comment by Yvand** [comment]
You need to remove the last entry in green (that is bound to Email "PickerEntity metadata") before you can add this new one.

**Comment by camel028** [comment]
Now I have like this:
![image](https://user-images.githubusercontent.com/3504518/90403302-11ba4d00-e0a1-11ea-8ae0-c9a3751d076d.png)

Unfortunately it caused that I do not have mail text once the entry is highlighted (earlier was over 'Users' text) and still do not see mail in the search entry but names only.

![image](https://user-images.githubusercontent.com/3504518/90403537-6d84d600-e0a1-11ea-8ff7-d54379e4bc91.png)

**Comment by Yvand** [comment]
hmm I think I know why it didn't work: there is a problem with the SharePoint enum type for the "PickerEntity metadata" values, and it selected "JobTitle" instead of "Title".
What you can try is reset the claim types configuration (at the bottom of the page) and to do the config through PowerShell (check [this page](https://yvand.github.io/AzureCP/Configure-AzureCP.html) for the details):
Instead of deleting the entry and adding your own, try to edit the existing one. It should preserve the "Title" property

**Comment by camel028** [comment]
LDAPCP.wsp is deployed on sharepoint on-premise (SP 2016) so I assume AzureCP.wsp is sth different here?
So should I modify the existing configuration via PowerShell and try to set "Title" property instead of JobTitle?

**Comment by camel028** [comment]
Hi,
It's seems to be working fine now - I've changed "JobTitle" to "Title" via PowerShell.

One more question.
Is it possible to add "PickerEntity metadata" value equals to "DisplayName" for attributes as cn, sn, givenName?  cCurrently DisplayName is assigned to main identity as presented of the picture.
I want to show on the highlighted tooltip value like "camel028 user" and not "sn=camel028".

Thanks!

**Comment by Yvand** [comment]
A given "PickerEntity metadata" can be associated to only 1 LDAP attribute (per LDAP class).
You may clear the "PickerEntity metadata" for the windowsaccountname claim type and use PowerShell to set it to either "cn" or "sn", but it don't think it will affect the test in the tooltip

**Comment by camel028** [comment]
As I understood, there is rather no such functionality that sn or cn will be replaced by the "DisplayName" value and the search will only follow these attributes but will be displayed something else?

**Comment by Yvand** [comment]
There is no direct way to control the value shown in the tooltip, but the order of the list may matter: if you put the displayName on top of the cs/sn, I think it will show the displayName in the tooltip

**Comment by camel028** [comment]
Hi,
It depends on what word was found via cn, sn or givenName but I would always want to have full name in tooltip, i.e. DisplayName without this prefix cn or sn as below:
![image](https://user-images.githubusercontent.com/3504518/92216762-0afc4a00-ee97-11ea-8786-7f5ccb87c2a6.png)
but just "Marcin Mandziej"

Is it possible to format like this?

**Comment by camel028** [comment]
Hi @Yvand ,

Could you please help with presenting the same mail attribute on the tooltip as for "PickerEntity metadata" attribute "Title"?
So in other words I would like to use the same attribute on pickerentity and tooltip at the top. Is it possible?

Thank you.

**Comment by Yvand** [comment]
@camel028 there is no way to control the value displayed in the tool tip, LDAPCP chooses the first attribute that matches the input, and formats it as you mentioned...

**Comment by camel028** [comment]
@Yvand ok it is clear but what about email address which is always presented at the top of the tooltip? Can I display the same address as defined in the "PickerEntity metadata" as Title field?

**Comment by Yvand** [comment]
The top value in the tooltip cannot be controlled.
I checked in the code, and it seems that it's SharePoint which decides what to show here, not LDAPCP.

**Comment by camel028** [comment]
Hi,
![image](https://user-images.githubusercontent.com/3504518/92485297-06af9400-f1eb-11ea-871a-ee48db34edf9.png)
I am think it is controlled by LDAPCP because the row marked with red defines mail (Email) value which is displayed at the top of the tooltip.
However I would like to present the same value which is already presented in the previous row so value under "pwcPreferredMail" but as I understand we cannot set the same LDAP attribute twice?

**Comment by Yvand** [comment]
Ah ok, yes that makes sense now.
So, as you suggested, the top value that SharePoint shows in the tooltip is the one that has PickerEntity metadata Email.
I confirm it wouldn't make sense to set the same PickerEntity metadata twice, it can match only 1 LDAP attribute

**Comment by camel028** [comment]
Hi @Yvand ,
OK but is it possible to set the same LDAP attribute ("pwcPreferredMail") at the last line so instead of pwcCloudMail.
I would like to have the same EMAIL value for PickerEntity metadata as well as for the last line.
As you can see now I have 2 different LDAP attributes for the mail (pwcPreferredMail & pwcCloudMail)

Thanks.

**Comment by Yvand** [comment]
@camel028 there is no direct control on the last line, it's really LDAPCP displaying basically the first value that matches the input...
