### ISSUE TITLE
No Results in OOTB People Pickers (SP2016)

### ISSUE THREAD

**Issue by jshenderson** [Yvand/LDAPCP#13]
I just installed LDAPCP on a fresh SP2016 installation. I'm using ADFS as a trusted provider. Sync is working and pulling in profiles. I'm able to login. However, now that the LDAPCP is installed I am not getting any results in my people picker. 

I have installed your solution on a 2013 farm and had good results so I'm wondering if maybe I missed a step.

Thanks in advance for your assistance.

**Comment by Yvand** [comment]
Can you check the SharePoint logs and filter on Product/Area "LDAPCP"?
It should give you more insight on what's happening.

**Comment by jshenderson** [comment]
I turned on Verbose logging for LDAPCP and get no results from it in logs. 

![image](https://user-images.githubusercontent.com/6308291/27697242-4a3712f4-5cb9-11e7-8b1d-c8a19f9b41db.png)

**Comment by jshenderson** [comment]
This is a good example. I'm logged in as spadmin, but when I type it in to the people picker there no results. (I do have a couple of users that were previously NTLM and noticed they show up in the people picker, but no ADFS profiles)

![image](https://user-images.githubusercontent.com/6308291/27697399-c2063666-5cb9-11e7-9cca-ae507b37dd35.png)

**Comment by Yvand** [comment]
Can you access LDAPCP administration page in central administration > security and confirm that there is nothing wrong (no error message in red)?
Then, in LDAPCP claims mapping page (same location), is the identity claim type (bold green line) present, with valid LDAP attribute/class?

**Comment by jshenderson** [comment]
**Central Admin > Security**
![image](https://user-images.githubusercontent.com/6308291/27735054-3f0d9114-5d63-11e7-8cfe-01eb17c22730.png)

**LDAP Claims Mapping Page**
![image](https://user-images.githubusercontent.com/6308291/27735116-8fe1e16c-5d63-11e7-8669-275b77d21933.png)

NOTE: when i installed this on 2013, I was able to choose the attribute from a drop down list on the User Profile Property, but with 2016 There was nothing populating the drop down so I had to type it in ("mail").

**Comment by jshenderson** [comment]
NOTE: I'm using this on an extend web application. Where the default is NTLM for search results, and the actual domain is using the extranet zone for ADFS authentication. I'm not sure if this would make a difference do I wanted to throw that out there.

**Comment by Yvand** [comment]
It makes no sense that you don't see any LDAPCP activity in the logs, it should log something, especially in verbose.
Can you run that to double check logs:
```powershell
Merge-SPLogFile -Path "C:\Temp\LDAPCP_logging.log" -Overwrite -Area "LDAPCP" -StartTime (Get-Date).AddDays(-1)
```

Can you also run this and confirm LDAPCP is displayed:
```powershell
Get-SPClaimProvider "LDAPCP"
```

**Comment by jshenderson** [comment]
Thank you for your responses. 
The logs are producing now. 
I can see "Add AD Server" > "Connecting to..." and where I'm getting "Get 0 Results"
but no errors.

There are a few entries throughout the logs that are "Monitorable" and say "[LDAPCP] Entry with LDAP class group is defined but it doesn't match any entry with the same LDAP class and a claim type defined. Add an entry with same LDAP object class and a claim type to fix this issue."

![image](https://user-images.githubusercontent.com/6308291/27741740-bb888632-5d7b-11e7-8e88-3c01b60a7057.png)

**Comment by Yvand** [comment]
So LDAPCP is connecting and does LDAP queries, but they return nothing.
Then the question is if LDAP server should actually return results, or if the LDAP query is invalid.
You can replay LDAP queries with PowerShell to investigate this further, you can use the script in http://ldapcp.com/Troubleshoot-LDAPCP.html

**Comment by Yvand** [comment]
@jshenderson any update on this?

**Comment by jshenderson** [comment]
not yet. due to building the farm with the daggum port in the DB connection. I was unable to update the farm. So I am in the process of rebuilding, but I'm about done. I should have an answer very soon. Again, I really appreciate your tool, and your assistance. BTW, you're tool was suggested to me by a MS PFE .

**Comment by Yvand** [comment]
Awesome, thanks for your feedback!
Please keep updating this thread with your progress

**Comment by jshenderson** [comment]
Thank you for your patience. I have rebuild the farm successfully and had good success with ADFS. However, I'm having the same issue with LDAPCP and the people picker having no results returned. 

I have replayed the queries I found in the logs and they do bring back results in powershell, but say "Got 0 results..." in the logs.

Do you know what I could be missing?

**Comment by Yvand** [comment]
Hi @jshenderson , you should pay attention about the LDAP filter, there must be something wrong with it that explains why LDAP server returns no result.
You can try to replay the LDAP query with PowerShell using the script available in http://ldapcp.com/Troubleshoot-LDAPCP.html
Hopefully you'll find what's wrong.

**Comment by jshenderson** [comment]
You can make this complete. I have found the issue, and now need to figure out how to fix it.
The LDAP query the server is running is on a subdomain hence the 0 results. But my user profile sync is running on the actual domain and pulling everything correctly. I'm not sure why this happening maybe because the server is in the subdomain?
