### ISSUE TITLE
Could not load file or assembly 'ldapcp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=80be731bc1a1a740' or one of its dependencies. The system cannot find the file specified. issue

### ISSUE THREAD

**Issue by AbuZeinab1987** [Yvand/LDAPCP#131]
Dears,

once deploy on 2 SharePoint 2016 web-front end servers  one of the servers give me the below error once open the site

Could not load file or assembly 'ldapcp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=80be731bc1a1a740' or one of its dependencies. The system cannot find the file specified.

i need to ask how to add ldapcp.dll to assemblies by gacutil it not added, is there any way to add the assembly under GAC_MLS

after investigation i found the below
server 1
C:\Windows\Microsoft.NET\assembly\GAC_MSIL\ldapcp\v4.0_1.0.0.0__80be731bc1a1a740

server 2
there is no folder for ldapcp

any idea?

Thanks in Advance

**Comment by Yvand** [comment]
Please check the "Important" section in https://ldapcp.com/Install-LDAPCP.html

**Comment by AbuZeinab1987** [comment]
i did it now but i got the same issue its now deployed on GAC on both WFE Servers
should i deploy the dll on Apps servers?

**Comment by Yvand** [comment]
LDAPCP.dll assembly must be present in all SharePoint servers of the farm.
Normally SharePoint should deploy it by itself to application servers, but if not, you definitely need to add it.

**Comment by AbuZeinab1987** [comment]
Many Thanks
