### ISSUE TITLE
Adding SPTrustedIdentityTokenIssuer

### ISSUE THREAD

**Issue by blackbasket** [Yvand/LDAPCP#132]
Hi,

I want to use LDAPCP, because I have to authenticate users from two ADs. I think, I understand the install procedure, but I do not know how to configure the Token Issuer.

I deployed ADFS in the past and understood how to do it in that case. But how do I deloy a Token Issuer for LDAPCP. I do not have i.e. any certificate. Or do I have to deploy ADFS to be able to use LDAPCP?

Thanks,
Marcel

**Comment by Yvand** [comment]
LDAPCP can be used only in federated authentication, so with a 3rd party STS, whether it's ADFS or another one.
Does that answer your questions?

**Comment by blackbasket** [comment]
Yes, thank you
