### ISSUE TITLE
Nested groups in AD, and .NET helper slowness

### ISSUE THREAD

**Issue by bgefrich** [Yvand/LDAPCP#133]
Hello, 

We have an ADFS solution with LDAPCP installed on SharePoint 2016. Group augmentation with the .NET Helper to the SharePoint AD domain is working as expected with nested groups. However, the augmentation queries are taking on average 8-9 seconds. When running workflows against items on a list, we may see many of these group augmentation calls, which can extend steps that should be nearly instantaneous out to minutes.

When we uncheck the .NET Helper option, the LDAP failover query takes ~45ms on average, but does not return the nested security groups.

The relevant (redacted) output from the logs for each query:
[LDAPCP] Got 23 group(s) for user "--------" in 45 ms from LDAP server "LDAP://---.----.---/DC=---,DC=----,DC=---" with LDAP filter "(&(ObjectClass=user) (sAMAccountName=--------)(!(objectClass=computer)))" (authenticate as "process identity" with AuthenticationType "Secure, Signing, Sealing").

[LDAPCP] Got and processed 31 group(s) for user "--------" in 8158 ms from AD domain "---.----.---" (authenticate as "process identity" with AuthenticationType "SimpleBind, Signing, Sealing").

**Comment by Yvand** [comment]
@bgefrich can you set LDAPCP logs to verbose and extract the logs when the augmentation is slow:

```powershell
"LDAPCP:*"| Set-SPLogLevel -TraceSeverity Verbose
```
