### ISSUE TITLE
When user matches on Windows Account Name user permission is written as a 'domain group'

### ISSUE THREAD

**Issue by jason-lochan** [Yvand/LDAPCP#137]
Hi,

We have an issue where if the user matches on Windows User Name the permission is stored as a 'Domain Group'
![image](https://user-images.githubusercontent.com/78814661/107406940-04719e80-6ad7-11eb-967d-0b62d6b0ff41.png)

Here is our trusted provider configuration:
![image](https://user-images.githubusercontent.com/78814661/107407354-8feb2f80-6ad7-11eb-97fd-7dc00909ed11.png)

Here is our LDACPCP Configuration:
Global:
![image](https://user-images.githubusercontent.com/78814661/107406169-2585bf80-6ad6-11eb-97dc-2005673417a8.png)
![image](https://user-images.githubusercontent.com/78814661/107406217-30d8eb00-6ad6-11eb-90c1-a513959559dd.png)
![image](https://user-images.githubusercontent.com/78814661/107406232-359d9f00-6ad6-11eb-9d6a-727228b15284.png)
![image](https://user-images.githubusercontent.com/78814661/107406239-38988f80-6ad6-11eb-935b-7e0314b5086f.png)

Claims:
![image](https://user-images.githubusercontent.com/78814661/107406486-7ac1d100-6ad6-11eb-89a1-6413b2b26e5f.png)

Here is what we see in People Picker
![image](https://user-images.githubusercontent.com/78814661/107406533-87462980-6ad6-11eb-803b-9dbba7dc21b9.png)

Here is what is stored
![image](https://user-images.githubusercontent.com/78814661/107407518-c0cb6480-6ad7-11eb-977e-5c21892a8006.png)

I can send the logs, but don't want to post them publicly

Do you have any idea why users who match on Windows Account Name are being written as a domain group?

**Comment by jason-lochan** [comment]
We've resolved this issue.

The problem was SamAccountName and Email were both configured as primary claims vs as secondary mappings (Like how  DisplayName is configured by default)

The solution was to delete the email & samAcountName configurations and add them back in using 'New Item' in the Claims configuration page, then using the 'add a mapping between a LDAP object and the main corresponding object type' 

Now when the user is selected they are added with the primary identifier claims as a User object.

Thanks!

Jason

**Comment by jason-lochan** [comment]
Spent a bit of time researching to get this configuration right.  Our primary identifier is UPN.

Here is our final configuration for anyone else who may be running into this issue:
![image](https://user-images.githubusercontent.com/78814661/107425387-e878f780-6aec-11eb-908b-f9121546519a.png)

**Comment by Yvand** [comment]
Thank you for taking the time to share your feedback
