### ISSUE TITLE
Is it possible to filter out specific users via LDAPCP with an LDAPFILTER

### ISSUE THREAD

**Issue by k4ntj3** [Yvand/LDAPCP#138]
I'm not sure this is the right place to ask this question, if not let me know.

I want to ask if it's possible and how to filter out specific users via LDAP filter
Our company want's to hide users for example in the People Picker which have the AD attribute extensionAttribute11 set to 1.

We have SharePoint 2016 with ADFS and LDAPCP 14.1.20191007.981 and I've created an LDAP filter that is working via PowerShell, but I don't know how te set this in LDAPCP, I've tried to set this LDAP filter in the claims type configuration from the UPN claim, but this is probable not correct and it is also not working.

I've tried to find different forums, but I haven't found anything helpful. So that is way I'm asking here.

Can anyone tell me if it's possible to use such a LDAP filter in LDAPCP?
This is the LDAP filter that I want to use:  (&(objectClass=user)(extensionAttribute11=0))

We also have a SharePoint farm with NTLM authentication and there I was able to put the filter on the WebApp and that is working fine, because we use ADFS authentication and LDAPCP on this farm I'm supposed I have to set the filter someway via LDAPCP.

I hope some can help me in the right direction, thanks in advance!

**Comment by Yvand** [comment]
@k4ntj3 LDAPCP lets you set custom LDAP filters per claim type.
You can do it in central admin > Security > LDAPCP claim types configuration.
In the table, you can set your custom LDAP filter in column "Additional LDAP filter"

**Comment by k4ntj3** [comment]
Thanks for the quick reply and for the great product!

Yes that is what I thought and I've already tried to add the filter to the UPN claim (not sure if this is the correct one) but when I use the PeoplePicker I still see users that I didn't expect to see.

I've also checked the hidden user list and the user that I've checked is also not in the hidden user list.

**Comment by Yvand** [comment]
Bear in mind that the results in the people picker may come from the local browser cache. To clear the cache, run this in the console: `localStorage.clear();` and refresh the page

**Comment by k4ntj3** [comment]
I'm not sure how to that via the console but I've reset my browser settings and tried inprivate navigation but both results are the same.

I've also attached a screenshot of my claim type configuration, maybe you can see if there is something wrong :)
![ldpacp](https://user-images.githubusercontent.com/43210993/108522791-7adb8100-72cd-11eb-8886-a6b0b4089a89.png)

**Comment by Yvand** [comment]
In your web browser: hit F12 and click on console tab. Here you can run the command `localStorage.clear();` and refresh the page.
In the screenshot I can see that you set the LDAP filter for the upn claim type specifically, but you probably want to apply it to the other rows in green too.
If you want to see the actual LDAP query done by LDAPCP, you can find it in the SharePoint logs. Filter the logs on product/area "LDAPCP" to find the relevant messages.

**Comment by k4ntj3** [comment]
Allright, ill check your tips next week.
Thanks for your help!

**Comment by k4ntj3** [comment]
I finally have time again for this issue.

When I run localstorage.clear(); the console response with undefined, not sure if that is correct. Never the less I cleared the cache via UI, but I still see users that I shouldn't see.

I've set the claims type configuration as below, do you know if that is correct?

![ldapcp2](https://user-images.githubusercontent.com/43210993/109942658-b403f000-7cd4-11eb-9341-ee748788058f.png)

**Comment by k4ntj3** [comment]
I forgot about this one:

If you want to see the actual LDAP query done by LDAPCP, you can find it in the SharePoint logs. Filter the logs on product/area "LDAPCP" to find the relevant messages.

I'm going to check the ULS logs.

**Comment by k4ntj3** [comment]
I found the actual LDAP filter in the ULS log and I've run the LDAP query from the ULS log step by step and noticed that the unwanted results came from the displayname part "(&(objectclass=user)(displayName=jeroen d*))"

When I checked the claim types page in Central Admin it isn't possible to add a additional LDAP filter, because I don't have an edit button there.

What would you suggest? Remove the displayname claim type? Or do you have other suggestions?
We are using the latest version at the moment.

Thanks in advance!

**Comment by k4ntj3** [comment]
I found the option to "apply the filter to all user attributes" and added the filter "(extensionAttribute11=0)" after that I tested with another user and that is working fine, so it appears that user that I tested before wasn't a good test case, not sure why yet.

**Comment by Yvand** [comment]
@k4ntj3 in any case, you can always extract the actual LDAP request executed by LDAPCP and reply it on your side to troubleshoot the unexpected results
