### ISSUE TITLE
LDAPCP not retriving user using Process Account

### ISSUE THREAD

**Issue by cmaneiro** [Yvand/LDAPCP#139]
Hi,

We have seen in some customer that the **Process Account** fails to show users in people picker. If the App pool is recycled the works again, but eventually the problem persist.

We've been able to resolve this situation configuring LDAP connection.

Kind regards

**Comment by Yvand** [comment]
Thank you for reporting this.
Do you mean that you deleted the default connection and created your own on the same domain instead?

**Comment by cmaneiro** [comment]
Hi,

I have tested both scenarios, removing default connection and having
default and LDAP

**Comment by Yvand** [comment]
So it works fine with a custom connection, but randomly fails with the default connection?

**Comment by cmaneiro** [comment]
Exactly!!!

My customer report me this problem and I was able to reproduce it in my lab.

The workaround seems to be working

**Comment by Yvand** [comment]
Understood. It was already reported a few times and it always worked to switch to a custom connection, but I have no idea why it happened. It's really a rare scenario.
