### ISSUE TITLE
Reflect user permission from security group

### ISSUE THREAD

**Issue by ychen803** [Yvand/LDAPCP#140]
Hi

We encountered with following issue for you to advice:
1. We have two domains for SharePoint farm
    - Sharepoint service accounts are at domain A
    - Normal user account are at domain B
2. We notice that permission granted via security group from domain B are not reflected
3. We notice that permission granted via security group from domain A are reflected

Can advice how we could configure so that the permission granted via security group from Domain B also reflected?

**Comment by Yvand** [comment]
hi @ychen803, here is what you can check:
- Does your identity provider include groups in its SAML token?
- Did you enable augmentation in LDAPCP?
- You can set LDAPCP logs in verbose to see what groups are added to the token of the user when he signs-in:
`"LDAPCP:*"| Set-SPLogLevel -TraceSeverity Verbose`

**Comment by ychen803** [comment]
Hi Yvand

Thanks for the reply. The command to enable log is very useful. I am able to see the groups for the user, looks alright. I have tested one user, it seems to be working. I will get my customer to verify use other accounts.

Regards
Chen Yue

**Comment by Yvand** [comment]
Sure, please update/close the issue when you have news on this

**Comment by ychen803** [comment]
Hi Yvand

Now we notice following symptoms related to parent security group, not sure whether it is due to the limitation of LDAPCP.
1. User belong to one child security group, e.g. SGC1 and this child security group belong a parent security group SGP1
2. We grant the permission to SGP1, user could have the necessary rights from SGP1
3. When we check the permission, the permission granted to SGP1 could not be reflected.
4. User's permission could only be reflected unless we grant the access directly to SGC1.

User mentioned that their SharePoint Online using the same ADFS server, could reflect the permission granted from parent security group.

Regards
Chen Yue

**Comment by Yvand** [comment]
@ychen803 when you configured the augmentation in LDAPCP settings page, did you enable option "Use .NET helper (for Active Directory only)"?
Only if it is set can LDAPCP get nested groups

**Comment by ychen803** [comment]
Hi Yvand

Yes, you are right. We did not check the 'Use .NET helper (for Active Directory only)'. We can see the nested group after we set the option. We are just waiting for user's final confirmation to close this case.

Regards
Chen Yue

**Comment by Yvand** [comment]
Please update/close the issue when you finished your verifications

**Comment by ychen803** [comment]
Yes, user confirmed the nested group are reflected in the UAT environment. Although we do encountered with similar issue on production, but we shall open a new case if needed. We will close this issue now.
