### ISSUE TITLE
Cannot Check Users Permissions and more

### ISSUE THREAD

**Issue by reveratt** [Yvand/LDAPCP#141]
Hi,

We've found a few issues related to ADFS account in our environment and using LDAPCP I hope you can help. We cannot check for permissions which I have seen was an issue in the past but cannot find a soluton for our environemnt. I have added Verbose for LDAPCP in our logs and we get different results depending on the user:
1) 
> 03/23/2021 14:32:00.65	w3wp.exe (0x1680)	0x169C	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] Starting augmentation for user 'mpat***@****ln.ac.uk'.	cb1ab79f-bed5-f017-bfc2-09465f0ee8e3'
03/23/2021 14:32:00.65	w3wp.exe (0x1680)	0x169C	LDAPCP	Augmentation	1337	Verbose	[LDAPCP] LDAP queries to get group membership on all servers completed in 0ms	cb1ab79f-bed5-f017-bfc2-09465f0ee8e3
03/23/2021 14:32:00.65	w3wp.exe (0x1680)	0x169C	LDAPCP	Augmentation	1337	Medium	[LDAPCP] No group found for user 'mpat***@****ln.ac.uk' during augmentation	cb1ab79f-bed5-f017-bfc2-09465f0ee8e3

2) 
`03/23/2021 14:31:35.41	w3wp.exe (0x1680)	0x2110	LDAPCP	LDAP Lookup	1337	Verbose	[LDAPCP] Connecting to "LDAP://network.uni/DC=network,DC=uni" with AuthenticationType "Secure, Signing, Sealing", authenticating as process identity and sending a query with filter "(| (&(objectclass=user)(userPrincipalName=al*****)) (&(objectclass=group)(sAMAccountName=a*****)) (&(objectclass=user)(displayName=al****)) (&(objectclass=user)(cn=a*****)(!(objectClass=computer))) (&(objectclass=user)(sn=a****)) (&(objectclass=user)(givenName=al*****)) (&(objectclass=group)(displayName=a*****)) )"	c51ab79f-eeab-f017-bfc2-0bf3d9883f51`

`03/23/2021 14:31:35.43	w3wp.exe (0x1680)	0x2110	LDAPCP	LDAP Lookup	1337	Medium	[LDAPCP] Got 1 result(s) in 9ms from 'LDAP://network.uni/DC=network,DC=uni' with filter '(| (&(objectclass=user)(userPrincipalName=ald****)) (&(objectclass=group)(sAMAccountName=ald****)) (&(objectclass=user)(displayName=al****)) (&(objectclass=user)(cn=al****)(!(objectClass=computer))) (&(objectclass=user)(sn=al****)) (&(objectclass=user)(givenName=a*****)) (&(objectclass=group)(displayName=ald****)) )'	c51ab79f-eeab-f017-bfc2-0bf3d9883f51`

`03/23/2021 14:31:35.43	w3wp.exe (0x1680)	0x2110	LDAPCP	LDAP Lookup	1337	Verbose	[LDAPCP] Got 1 result(s) in 19ms from all servers with query "(| (&(objectclass=user)(userPrincipalName=a****)) (&(objectclass=group)(sAMAccountName=al****)) (&(objectclass=user)(displayName=al****)) (&(objectclass=user)(cn=a*****)(!(objectClass=computer))) (&(objectclass=user)(sn=ald****)) (&(objectclass=user)(givenName=al*****)) (&(objectclass=group)(displayName=al****)) )"	c51ab79f-eeab-f017-bfc2-0bf3d9883f51`

`03/23/2021 14:31:35.43	w3wp.exe (0x1680)	0x2110	LDAPCP	LDAP Lookup	1337	Medium	[LDAPCP] 1 entity(ies) to create after filtering	c51ab79f-eeab-f017-bfc2-0bf3d9883f51`

`03/23/2021 14:31:35.43	w3wp.exe (0x1680)	0x2110	LDAPCP	Claims Picking	1337	Verbose	[LDAPCP] Added entity: display text: 'AlD****@****c.uk', claim value: 'AlD****@****c.uk', claim type: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn'	c51ab79f-eeab-f017-bfc2-0bf3d9883f51`

`03/23/2021 14:31:35.43	w3wp.exe (0x1680)	0x2110	LDAPCP	Claims Picking	1337	Medium	[LDAPCP] Returned 1 entities from input 'al****'	c51ab79f-eeab-f017-bfc2-0bf3d9883f51`

Here are my LDAPCP settings 

![image](https://user-images.githubusercontent.com/1033032/112166933-fb9cde00-8be7-11eb-8194-3f2806b7750c.png)
![image](https://user-images.githubusercontent.com/1033032/112166971-022b5580-8be8-11eb-9e3e-b2496e0fcb95.png)

Any help would be very much appreciated.

Kind regards
Robert Everatt
[log1.txt](https://github.com/Yvand/LDAPCP/files/6191302/log1.txt)
[log2.txt](https://github.com/Yvand/LDAPCP/files/6191303/log2.txt)

**Comment by NaveenKanukuntla** [comment]
@reveratt FYI, I would suggest you to replace the sensitive information like email id or network information from your post. To keep it a little anonymous.

**Comment by reveratt** [comment]
@NaveenKanukuntla Thanks for that, you are correct and a silly mistake for me to make. I've updated that, many thanks.

**Comment by Yvand** [comment]
@reveratt in the LDAPCP settings, you did not check the box "Query this server" in the augmentation section.
Can you please check it and try again (look at the log to ensure that LDAPCP is called again for augmentation) ?

**Comment by reveratt** [comment]
That appears to solve that issue thank you very much however we are also having another issue. When sending an email address to a user in a workflow (seleted from a people picker and setting the 'To' field to Email Address) The workflow throws and erorr saying the email cannot be sent. After looking in the log it's says the user cannot be found and a similar LDAPCP query. I have included a relevant selection from the logs. 

The line 'Discarding found match in user info list because it's not on the account name or mobile phone' suggests the synchronization between the User Profile Service and the User Information List is not working but this user can be found in the UIL with all his information includin the prefix 'i:0e.t|adfs|' which I would expect.

Your help is very much appreciated.

Kind regards
Robert Everatt

[log3.txt](https://github.com/Yvand/LDAPCP/files/6200406/log3.txt)

**Comment by Yvand** [comment]
@reveratt the log file looks somehow broken so it's difficult to see what is wrong.
Could it be that 2 users (Windows + trusted) have the same email in the UPA?
