### ISSUE TITLE
Question about installing LDAPCP on a new server in Sharepoint 2016 FARM

### ISSUE THREAD

**Issue by DanGillott** [Yvand/LDAPCP#142]
I have a server in a Sharepoint 2016 and I basically need to reinstall LDAPCP on it locally.  I wanted to know if I can use
a "-local" switch similar to "Install-SPSolution-Identity LDAPCP.wsp –GACDeployment -local"
The solution is installed through out the farm and is working.
When I run "get-spsolution"  deployed is "true"

get-spsolution

Name                           SolutionId                           Deployed
----                           ----------                           --------
ldapcp.wsp                     6ff99767-b95a-4143-8cd8-3978aa01fb80 True

When I run "Get-SPFeature" the Scope is missing.

Get-SPFeature| ?{$_.DisplayName -like 'LDAPCP*'}| fl DisplayName, Scope, Id, RootDirectory

DisplayName   : LDAPCP
Scope         :
Id            : b37e0696-f48c-47ab-aa30-xxxxxxxxxxxxx
RootDirectory : C:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\16\Template\Features\LDAPCP

DisplayName   : LDAPCP.Administration
Scope         :
Id            : f8ebe160-61e5-4e90-8759-xxxxxxxxxxxx
RootDirectory : C:\Program Files\Common Files\Microsoft Shared\Web Server
                Extensions\16\Template\Features\LDAPCP.Administration

I am guessing the install should be something similar to the below?

"Add-SPSolution -LiteralPath "C:\LAPCP\LDAPCP.wsp" "
"Install-SPSolution -Identity "LDAPCP.wsp" -GACDeployment -local"

Thanks for any information.

Regards Dan

**Comment by Yvand** [comment]
hi @DanGillott, can you confirm that you ran `Get-SPFeature| ?{$_.DisplayName -like 'LDAPCP*'}| fl DisplayName, Scope, Id, RootDirectory` on the same server that does NOT actually contain those features in the 16\TEMPLATE\FEATURES folder?
Is LDAPCP,dll present in the GAC of this server?

**Comment by DanGillott** [comment]
@Yvand , Thanks for the quick response.  Yes I can confirm that the Get-SPFeature is on the server and I cannot locate the LDAPCP.DLL in the GAC.  I only spot checked the GAC, GAC_64 and GAC_32 directories.

**Comment by Yvand** [comment]
@DanGillott then I have a little doubt regarding the fact that I'm not sure if  `Get-SPFeature| ?{$_.DisplayName -like 'LDAPCP*'}| fl DisplayName, Scope, Id, RootDirectory` considers that feature IS installed despite files are missing.

In theory, you could run just `Install-SPSolution -Identity "LDAPCP.wsp" -GACDeployment -local` on the server, but I would not do it.
LDAPCP is a simple solution. To avoid any problem, I would:

* Manually copy the features from the WSP (or another server) to 16\TEMPLATE\FEATURES
* Manually install ldapcp.dll in the GAC using the script at the end of [this page](https://ldapcp.com/Install-LDAPCP.html)

**Comment by DanGillott** [comment]
@Yvand Thank you.  I will do the manual copy as suggested.  Can I ask why not run the "Install-SPsolution"  I had done that early on when first deploying on a few servers.  Due to a timer job issue we experienced at the time the install was not pushed out.  Although it did work.  Again I am grateful for the information.  I will let you know if I can resolve it.

**Comment by Yvand** [comment]
@DanGillott I am a little bit afraid that `Install-SPsolution` fails. If this happens, fixing it [is possible](https://ldapcp.com/Fix-setup-issues.html) but it's a pain.
But well, thinking about it, using the `-Local` switch is quite safe, so in fact maybe I would use it instead of doing it manually.
It would make later updates more reliable (as SP will have the actual knowledge where solution binaries are deployed).
But copying files manually is really not a big deal and is totally safe...

**Comment by DanGillott** [comment]
@Yvand  - Always good to know as I am on the only one of two engineers here who actually installed it.  We are moving to a federated authentication and I am working on our second farm and the first farm went very well with this solution.  So Thank you,  as far as the fix is concerned.  I am reviewing some correspondence I had with MS support and they had suggested the -local which did work early on. You are correct it is safe.  I do like the solution you provided.  I can confirm it did work.  
Thank you again!!!

**Comment by DanGillott** [comment]
Can I ask a follow up question.  We are checking the existing assembly and we do not see the LDAPCP.  We are just looking for any correlation.  Does this make any sense to you.

$existingAssembly = [System.Reflection.Assembly]::Load("ldapcp, Version=1.0.0.0, Culture=neut
ral, PublicKeyToken=80be731bc1a1a740").Location
Exception calling "Load" with "1" argument(s): "Could not load file or assembly 'ldapcp, Version=1.0.0.0,
Culture=neutral, PublicKeyToken=80be731bc1a1a740' or one of its dependencies. The system cannot find the file
specified."
At line:1 char:1
+ $existingAssembly = [System.Reflection.Assembly]::Load("ldapcp, Versi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException

and In the logs we noticed that it is failing to load a custom DLL

04-06-2021 09:25:26.33 w3wp.exe (0x3C48) 0x32C4 SharePoint Foundation Claims Authentication b280 High Error loading the claim provider assembly 'ldapcp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=80be731bc1a1a740' with type 'ldapcp.LDAPCP'. 478abb9f-6181-a0bf-8819-89466b849570

**Comment by Yvand** [comment]
It's completely related. ldapcp,dll must be present on all the servers of the SharePoint farm, since as you mentioned, it may be called by SPTimer service on any server in the farm.

Just to be sure, finally did you deploy the files manually or did you run `Install-SPSolution -Identity "LDAPCP.wsp" -GACDeployment -local`?

**Comment by DanGillott** [comment]
We have run it manually yet we will be doing so shortly.  I was asked to verify.  Thanks for the update.

**Comment by DanGillott** [comment]
We re-ran from the CA server "update-solution" successfully.  No errors are reported in the solution properties for LDAPCP  
We get an error running a manual local install with "add-spsolution" and "install-spsolution - force" saying the solution with the same name exists and the ID (which is correct).  I think the solution has to be removed and re-added. but I am not sure of the proper command would "remove-SPSolution -Identity "LDAPCP.wsp" -GACDeployment -local" work?  I am not looking to remove the solution entirely from the Farm just individual servers 

 When the check the assembly I keep getting an error : 

$existingAssembly = [System.Reflection.Assembly]::Load("ldapcp, Version=1.0.0.0, Culture=neut
ral, PublicKeyToken=80be731bc1a1a740").Location
Exception calling "Load" with "1" argument(s): "Could not load file or assembly 'ldapcp, Version=1.0.0.0,
Culture=neutral, PublicKeyToken=80be731bc1a1a740' or one of its dependencies. The system cannot find the file
specified."
At line:1 char:1
+ $existingAssembly = [System.Reflection.Assembly]::Load("ldapcp, Versi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException

Thanks for the assistance

**Comment by DanGillott** [comment]
We were able to correct the issue with the existing assembly and updating the solution through CA.
I will post the steps once I get them from the other engineer.

Thanks for your help
