### ISSUE TITLE
User missing in Peoplepicker

### ISSUE THREAD

**Issue by fvibas** [Yvand/LDAPCP#143]
We are using LDAPCP v14.1.20191007.981 and we are encountering some users missing in the people picker but when we run the Replay LDAP queries the accounts is actually returned. The account is also there in the User Profile service. May I know what other things to troubleshoot this issue?

**Comment by Yvand** [comment]
Can you check the SharePoint logs and filter on product/area "LDAPCP" to double check if the LDAP server returned results on the LDAP query ?

**Comment by fvibas** [comment]
Hi Yvand,

I checked the logs and it thows unexpected [ LDAPCP] Validation failed: found 0 entities instead of 1 for incoming claim with value 'accountname@domain.com' and type 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'	

what could be an issue with this?

**Comment by Yvand** [comment]
It seems that the LDAP query did not return any result. The LDAP query should be recorded just before this message, can you copy it and replay it as [documented here](https://ldapcp.com/Troubleshoot-LDAPCP.html) to confirm/check if it returns the user/group?
