### ISSUE TITLE
Configuration issues after LDAPCP installation

### ISSUE THREAD

**Issue by gancil** [Yvand/LDAPCP#144]
We just installed LDAPCP on our SharePoint 2019 environment.  Once installed, we went to Security, clicked on Global configuration under LDAPCP Configuration and immediately get the following error: 
**_Sorry, something went wrong 
Identity claim type must be configured with EntityType 'User'_** 

Apologies, we're new to using LDAP.  Can someone please help us get passed this error?

Thank you!

**Comment by Yvand** [comment]
@gancil can you copy the output of `Get-SPTrustedIdentityTokenIssuer` and `(Get-SPTrustedIdentityTokenIssuer).IdentityClaimTypeInformation` ?
