### ISSUE TITLE
People picker not resolving users

### ISSUE THREAD

**Issue by BalakrishnaDuggireddy** [Yvand/LDAPCP#145]
Suddenly people picker stopped working and can't resolve the users.

in the LDAP Global Configuration page see this error. 
There is no claim type associated with an entity type 'FormsRole' or 'SecurityGroup'.
   
 
 how can i fix this error or can this error can be ignored

![LDApError](https://user-images.githubusercontent.com/87300179/127227860-40f3fbde-d035-4ae5-9631-45fedffff2dd.JPG)

**Comment by Yvand** [comment]
@BalakrishnaDuggireddy is this error still present? If so, can you send a screenshot of the LDAPCP claim types configuration page?

**Comment by BalakrishnaDuggireddy** [comment]
Hi Yvan, The error disappeared after adding the role claim type.
However the people picker not resolving the users. if we search for user 'No results Found'.
![PeoplePickererror1](https://user-images.githubusercontent.com/87300179/128249859-2d07719f-9489-4263-8006-878995321672.JPG)

If we copy full mailid and try to add the user, the error message is 'the site can't be shared with external users' though we try to add internal users.
![PeoplePickererror2](https://user-images.githubusercontent.com/87300179/128249894-9c25a971-bbf1-45a3-9d81-e88a07054b9e.JPG)

**Comment by Yvand** [comment]
hi @BalakrishnaDuggireddy , you can check the SharePoint logs and filter on product/area "LDAPCP" to see what is wrong.
I also recommend that you update to the latest version, as v10 is quite old.

**Comment by BalakrishnaDuggireddy** [comment]
Hi @Yvand , i see these errors in the logs.
[LDAPCP] Add LDAP server "LDAP://path" with AuthenticationType "None" and credentials "accountName".

[LDAPCP] Connecting to 'LDAP://path' with AuthenticationType 'None' and filter '(| (&(objectclass=Person)(mail=zhan-*)(|(UserType=EMP)(UserType=SC))) (&(objectclass=Person)(sn=zhan-*)) (&(objectclass=Person)(FullName=zhan-*)) )'

[LDAPCP] Unexpected error occurred during connection to LDAP server LDAP://path: System.Runtime.InteropServices.COMException: The server is not operational.  , Callstack:   
 at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)    
 at System.DirectoryServices.DirectoryEntry.Bind()    
 at System.DirectoryServices.DirectoryEntry.get_AdsObject()    
 at System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne)    
 at ldapcp.LDAPCP.<>c__DisplayClass42_0.<QueryLDAPServers>b__1(LDAPConnection ldapConnection)

[LDAPCP] Got 0 result(s) in 100ms from all servers with query "(| (&(objectclass=Person)(mail=zhan-*)(|(UserType=EMP)(UserType=SC))) (&(objectclass=Person)(sn=zhan-*)) (&(objectclass=Person)(FullName=zhan-*)) )"
-------------------
Note: i'm able to connect to LDAP server from Softerra LDAP browser without any error.

Also what would be the authentication type in LDAP Global configuration page should be selected?
![image](https://user-images.githubusercontent.com/87300179/128564853-ee152744-c95a-4317-94e8-cf531cd9ab73.png)
