### ISSUE TITLE
Slow queries to LDAP

### ISSUE THREAD

**Issue by 863piotr** [Yvand/LDAPCP#146]
I have the problem with performance of LDAPCP. I have few people pickers on our custom page in SP 2013 and everytime LDAPCP ask LDAP about the user instead of checking user/claims directly in SP or take from cache. Is it possible to implement the cache? Or maybe it's already implemented but I need to adjust the configuration for such behaviour?

**Comment by Yvand** [comment]
@863piotr you can check the SharePoint logs and filter on Message contains "LDAPCP" to see what exactly is slow. It will include SPMonitoredScope that will be helpful to identify the problem
