### ISSUE TITLE
case-sensitive get domain name by distinguished name

### ISSUE THREAD

**Issue by lehuspohus** [Yvand/LDAPCP#147]
Hi! 
We have an openLDAP server with custom schema and already successfully configured LDAPCP for lookup from this server.

The only thing we needed to change in LDAPCP code to make it work was to **replace case sensivity Contains method** from lines like `if (distinguishedName.Contains("DC="))` with something case insensitive.
This was needed because our schema contains distinguished names in lower case (i.e. _dc=domain,dc=com_ instead of _DC=domain,DC=com_).
I think it will be better to remove case sensivity from your official build because 

> distinguished name case sensitivity is not consistent across LDAP Server implementations

according to different documentation like https://ldapwiki.com/wiki/Distinguished%20Name%20Case%20Sensitivity

**Comment by Yvand** [comment]
@lehuspohus thank you for reporting this.
Indeed, the string operations on the distinguished name should not be case sensitive, I'll change this soon
