### ISSUE TITLE
Getting Site Can't be reached

### ISSUE THREAD

**Issue by AmitW02** [Yvand/LDAPCP#149]
Hi Yvand,

Greetings! 

Got wired issue, after attaching LDAPCP with trusted identity provider, I am getting:

![image](https://user-images.githubusercontent.com/90429964/132906414-bd9a37e7-d4a2-44c9-aa0c-5138ab4bc73b.png)

Even, I have uninstalled and installed LDAPCP again. 

If I am removing LDAPCP from Trusted identity provider, then it's working as expected. 

Also, I don't see nay issue in ULS logs. Any insights would be highly appreciated.

**Comment by Yvand** [comment]
hi @AmitW02, did you enable augmentation in LDAPCP configuration?
If so, can you try to disable it and check if it also throws this error?

**Comment by AmitW02** [comment]
Thanks Yvand for your response. 

After disabling  augmentation, getting same error.

here is our configuration:

![image](https://user-images.githubusercontent.com/90429964/133303296-22193cb0-0343-4769-bb35-f2dc3ec053ed.png)

![image](https://user-images.githubusercontent.com/90429964/133303356-e09d0e24-928f-4fbc-a6fd-cf31afbd0d6e.png)

**Comment by AmitW02** [comment]
Attaching uls logs.

**Comment by AmitW02** [comment]
[SVRSP16WFES01-20210914-1021 - VerboseLog.log](https://github.com/Yvand/LDAPCP/files/7164106/SVRSP16WFES01-20210914-1021.-.VerboseLog.log)

**Comment by AmitW02** [comment]
[SVRSP16WFES01-20210914-1021 - VerboseLog.log](https://github.com/Yvand/LDAPCP/files/7164125/SVRSP16WFES01-20210914-1021.-.VerboseLog.log)

**Comment by Yvand** [comment]
@AmitW02 just to be clear, any log that you upload here is accessible to everyone.
I had a look at the log and the only interesting thing I saw is a gap of 10 seconds during authN:

```
09/14/2021 10:22:08.11	w3wp.exe (0x40A0)	0x3B30	SharePoint Foundation	Claims Authentication	arhor	Medium	STS Call: Creating Claims Operations Scope for Applies To Uri: 'https://<site>/'	1678ef9f-0d05-90d5-3212-5ed768b3a25b
09/14/2021 10:22:08.11	w3wp.exe (0x40A0)	0x3B30	SharePoint Foundation	Claims Authentication	arhon	Medium	Not creating SPClaimsOperationContext since there is one on the thread already. Uri: 'https://<site>/'	1678ef9f-0d05-90d5-3212-5ed768b3a25b
09/14/2021 10:22:08.13	w3wp.exe (0x40A0)	0x3B30	SharePoint Portal Server	User Profiles	ae0ry	Verbose	Profile Store Claim Provider: Entity does not need Windows augmentation.	1678ef9f-0d05-90d5-3212-5ed768b3a25b
09/14/2021 10:22:18.44	w3wp.exe (0x40A0)	0x3B30	SharePoint Foundation	Monitoring	b4ly	High	Leaving Monitored Scope: (SPClaimProvider.FillClaimsForEntity()) Execution Time=10326.1092; CPU Milliseconds=30; SQL Query Count=0; Parent=SPClaimProviderOperations.ClaimsForEntity()	1678ef9f-0d05-90d5-3212-5ed768b3a25b
```

But it is not caused by LDAPCP: augmentation is disabled and it did not record anything at that moment in the logs.
I bet you have the same gap without LDAPCP.
The connection reset may be done by a network component between SP and the browser because it considers 10 secs as too long, but again, LDAPCP is not causing this delay.

**Comment by AmitW02** [comment]
sure, let me check with network guys.

**Comment by AmitW02** [comment]
There is no issue with Network team. While debugging the LDAPCP code, I am getting below error:

![image](https://user-images.githubusercontent.com/90429964/136469127-5cc0eb0f-841a-4d1f-a9e4-ef48330b6f9e.png)

Also, It's not point to braking point. Even I have tried with Visual Studio -> Debug -> Options ->  uncheck "Enable just my code"

**Comment by AmitW02** [comment]
Root cause - Due to another custom claim (not LDAPCP). Added few more conditions in custom claim provider.

**Comment by Yvand** [comment]
thanks for sharing the outcome !
