### ISSUE TITLE
What to expect updating from v5.1

### ISSUE THREAD

**Issue by k4ntj3** [Yvand/LDAPCP#150]
I've seen that updating LDAPCP from v5.1 to version >10 is a major update and that the claim type configuration will be reset.

"Version 10 is a major update that has breaking changes. Updating to v10 (or newer) will reset claim type configuration list, and all customization made to that list will be lost."

What does this exactly mean? Will the providerrealms be reset or more?
Will it be enough when I export my current providerrealm settings and create a commandlet that will recreate these?

We already updated our test environments, so badly I can't test this myself and It was a long time ago and I don't remember what exactly happened.

Thanks in advance!

**Comment by k4ntj3** [comment]
After some research I guess below site will be cleared and none of the above.

https://CA/_admin/Ldapcp/ClaimsTable.aspx

Can this be confirmed? :D

**Comment by Yvand** [comment]
@k4ntj3 exactly, that's what is reset.
It does not reset/change anything to SharePoint configuration itself

**Comment by k4ntj3** [comment]
Great Thx for the feedback!
