### ISSUE TITLE
Issue with LDAP group augmentation and interactive sign in

### ISSUE THREAD

**Issue by bryanhart73** [Yvand/LDAPCP#151]
Running 14.1.20191007.981 and SharePoint 2019 using non-AD LDAP.  Running into an issue where group permissions are not working correctly on sign in.  Augmentation is enabled and I see it happening without any errors in the ULS log (most of the users are members of ~100 groups and the list in the log appears to be correct). A permissions check in the SharePoint UI says the users have access via one of the groups as expected.  The issue is on interactive login - all users with access via a group are getting "Sorry, you don't have access."  The troubleshooting section doesn't really cover this scenario, not sure what else to check.

**Comment by Yvand** [comment]
@bryanhart73 a possible explanation is a mismatch between:
- The value of the group permission you set in the site
- The value of the group claim added by LDAPCP.

By default, LDAPCP creates group claims using format "DomainFADN\groupname".
So you need to double check if the group permission in the SharePoint site also has the format "DomainFADN\groupname" (which it should if it was created through LDAPCP).

**Comment by bryanhart73** [comment]
The group permissions were set using LDAPCP via people picker.  This is a non-AD claims environment so the group looks like "c:0-.t|trustrealm|groupname" instead.

**Comment by bryanhart73** [comment]
I should also probably say that this same basic configuration (same LDAP server and claims mappings) works fine with SharePoint 2013 and LDAPCP v5.1.  The only modification we had to make there were some minor code changes to LDAPCP to change how the LDAP filters handled case sensitivity.

**Comment by Yvand** [comment]
@bryanhart73 you really need to compare the group value added by LDAPCP during augmentation with the actual value of the permission.
You mention that group permission looks like `c:0-.t|trustrealm|groupname`.
Can you check if, during augmentation (sign-in), LDAPDP adds groups in the format `groupname` (instead of maybe `domainfqdn\groupname`) ?

**Comment by bryanhart73** [comment]
The ULS log show saugmentation adding "groupname", not "domain\groupname".  Case matches as well.

**Comment by Yvand** [comment]
As a simple test, can you create a new temp site collection, grant permission to a group and test to access as a trusted user member of this group?

**Comment by bryanhart73** [comment]
Sorry for the slow response - we ultimately tracked this down to a non-LDAPCP issue.  Someone incorrectly changed permissions on the Site Pages library.  You can close this and thanks for your responses.

**Comment by Yvand** [comment]
No worries, thank you for your feedback
