### ISSUE TITLE
No result in Select People or Group dialog

### ISSUE THREAD

**Issue by hanspeham** [Yvand/LDAPCP#155]
Dear Yvand!
I am using LDAPCP in a SharePoint 2019 farm and changed to ADFS authentication recently. I use the mail attribute as identity claim and also group claims which are working fine. The LDAPCP configuration is standard (automatic setting), only that I removed the {fqdn} suffix for the role claim.  I have an issue but maybe it is only a misconfiguration.
When I use the Select People or Group dialog (the dialog used to configure an OOB workflow, or select people in an InfoPath form) , there are no results under the custom claim provider "ADFS" (see attached image)
![NoResult](https://user-images.githubusercontent.com/39927808/144469854-800aa329-4c24-4887-8852-80c24af3958e.png)
I am also having trouble selecting users in an Nintex form and I suspect that this is also linked to the above problem.
Am I missing something in the configuration? 
Thanks in advance and best regards,
 Hans

**Comment by Yvand** [comment]
hi @hanspeham, can you check the SharePoint logs when you do this search, and filter them on product/area "LDAPCP"?
It should show some information that can explain why it displays no result

**Comment by hanspeham** [comment]
Hi Yvand! 
This is what I get when I click on the search button of the dialog:
12/03/2021 15:14:11.82    w3wp.exe (0x2B8C)    0x2B60    LDAPCP    LDAP Lookup    1337    Unexpected    [LDAPCP] Unexpected error occurred while connecting to LDAP server LDAP://[DOMAIN].com/DC=[DOMAIN],DC=com: System.DirectoryServices.DirectoryServicesCOMException: An operations error occurred.  , Callstack:    at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)     at System.DirectoryServices.DirectoryEntry.Bind()     at System.DirectoryServices.DirectoryEntry.get_AdsObject()     at System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne)     at ldapcp.LDAPCP.<>c__DisplayClass43_0.<QueryLDAPServers>b__1(LDAPConnection ldapConnection)    212d09a0-2e15-a0c6-12f4-fedc87ab5181

**Comment by Yvand** [comment]
It looks like somehow, the default LDAP connection does not work fine in all processes.
To fix it, instead of using the default connetion, can you try to create the LDAP connection manually? You can do that from central administration > LDAPCP global configuration > Add a new LDAP connection ? (and of course do not forget to remove the default one)

**Comment by hanspeham** [comment]
Hi Yvand! You were right. The automatic configuration was working only partly, I suspect due to security hardening. Manual configuration works. 
Kind regards,
 Hans
