### ISSUE TITLE
ldaps

### ISSUE THREAD

**Issue by dssbegj** [Yvand/LDAPCP#156]
Hello, my company has decided to switch our ldap server to ldaps and i cannot get ladpcp to work.

i see there is an old issue that is closed from 2020 that says its not compatible with ldaps, is this still the case?
https://github.com/Yvand/LDAPCP/issues/125

i havent seen any info in the changelog of ldapcp that mentions ldaps.

**Comment by Yvand** [comment]
LDAPDP uses the standard .NET directory services API and it should be able to connect to any LDAP server which this API supports.
I suggest you use the script in https://www.ldapcp.com/docs/help/troubleshooting/#replay-ldap-queries to try to connect to your LDAPS server. If it works, LDAPCP will also be able to connect
