### ISSUE TITLE
How to populate second line in results

### ISSUE THREAD

**Issue by helderem** [Yvand/LDAPCP#158]
We've implemented LDAPCP in our Extranet project and it works very nicely. However my client has the wish to also show the Company from LDAP (LDS) field in the People Picker. In our Intranet environment there is a second line in the People Picker where the JobTitle is shown, I would also like to populate that in our Extranet. No sure if it is at all possible.

This is our internal environment, the second line says "Inhuur algemeen"
![pp_internal](https://user-images.githubusercontent.com/16709595/154668703-41ca36ab-b398-4dc6-bf38-c94c18a1441e.png)

This is my LDAPCP setup, we want to display the company field:
![claimtypes](https://user-images.githubusercontent.com/16709595/154668918-8fde0668-4e1a-4746-b680-2d405f5812cd.PNG)

This is how results show up in our People Picker that uses LDAPCP:
![peoplepicker](https://user-images.githubusercontent.com/16709595/154669215-399e95d1-e772-45a6-adb7-d757e8505886.PNG)

I've also tried making swapping the DisplayName value with Company, that works and the Company is displayed as result.

**Comment by Yvand** [comment]
@helderem what matters is where the PickerEntity metadata "JobTitle" is set.
But from an old memory I think I remember there is a problem with the [JobTitle member](https://docs.microsoft.com/fr-fr/dotnet/api/microsoft.sharepoint.webcontrols.peopleeditorentitydatakeys?view=sharepoint-server). I will test it next week and come back to you with more details

**Comment by Yvand** [comment]
@helderem it was actually a very old bug in LDAPCP, which I just fixed in https://github.com/Yvand/LDAPCP/commit/b5ce4b104872fcb226038f33e978f7b7cac92584
If you don't want to wait for the hotfix, you could set it through PowerShell instead of the admin page. You can use [this example ](https://www.ldapcp.com/docs/usage/configuration/#add-a-claim-type-to-ldapcp) as a starter.

**Comment by Yvand** [comment]
@helderem ok, I will check on my side and come back to you with my findings

**Comment by helderem** [comment]
@Yvand , this works perfectly! Thank you for the support.
