### ISSUE TITLE
Is it possible to hide "Everyone" -group from People Picker?

### ISSUE THREAD

**Issue by kalervojankko** [Yvand/LDAPCP#159]
Hi,

Our client asked if it is possible to hide the "Everyone" (All authenticated users) -group from People Picker?

From time to time, users inadvertently grant permissions to that group to site collections, libraries and files and we check with custom ps script few times a year where those permissions are granted and then remove them.

I know that you can hide that group from People Picker in SPO, but is there anyway to do this with SharePoint Server and LDAPCP?

I found that in SP Server it is possible to disable the whole identity with powershell: 

$claimMgr = Get-SPClaimProviderManager

$allUser = get-spclaimprovider –identity "AllUsers"

$allUser.IsEnabled = $false

$claimMgr.Update()

...but unfortunately that breaks our custom sitecollection provisioning solution so that's not an option.

I am also familiar with the LDAP filters and we are currently usign multiple filters with LDAPCP to hide all the reduntant users and groups from People Picker. I haven't found any LDAP filters that would work with "Everyone" -group e.g. c:0(.s|true.

**Comment by Yvand** [comment]
Hi @kalervojankko, permissions "Everyone" and "All Users (authenticationMode)" are created by out of the box claims provider "SPAllUserClaimProvider" and there is no way to configure it (and PeoplePickerSettings have no effect on it).
You can deactivate it as you did with your script, but then it has side effects.
LDAPCP cannot do anything about this, as it does not create those permissions.

**Comment by kalervojankko** [comment]
Thanks! That's all I needed. :)
