### ISSUE TITLE
People Picker Filtering

### ISSUE THREAD

**Issue by Darnould56** [Yvand/LDAPCP#161]
Hello,

We have a SharePoint 2013 farm with multiple webapplications all using ADFS.
For one of them (and only this one), we want to filter the users shown in people picker to the membership of a specific group and/or to a specific OU in Active Directory.

We tried filtering with the "peoplepicker-searchadcustomfilter" property for the sitecollection.
We also tried to use the "UserAccountDirectoryPath" property.
It looks like the LDAPCP is not using those filter.

Is there a way to make it work?

Thanks

Regards

**Comment by Yvand** [comment]
@Darnould56 I confirm that LDAPCP does not use this property as it is specific to Windows users, and indeed, LDAPCP does not allow you to customize the LDAP filter per web application
