### ISSUE TITLE
Force LDAPCP to USE Port 636

### ISSUE THREAD

**Issue by mpatrick210** [Yvand/LDAPCP#163]
Is there a way to force a LDAPCP connect to user port 636 vs 389?

**Comment by Yvand** [comment]
You can replace the default connection with your own LDAP connection and set the port to 636 in central admin > Security > LDAPCP global configuration.
If LDAPS is correctly configured on the LDAP server, then the connection should use SSL encryption.

**Comment by mpatrick210** [comment]
Hey Yvand - I currently use LDAPCP v2017.10, and do not see a place to set the port. Do we need to update LDAPCP to a new version to see that option? I tried to add the port to the actual LDAP path - LDAP://xx.xx.xx.xx:636 - but that didn't work.

**Comment by Yvand** [comment]
@mpatrick210 yes it should work, although you should update LDAPCP
The LDAP path is correct, but I forgot that you should also check [SecureSocketsLayer](https://docs.microsoft.com/en-us/dotnet/api/system.directoryservices.authenticationtypes) in the authentication type options

**Comment by Yvand** [comment]
@mpatrick210 based on the [enum type values](https://docs.microsoft.com/en-us/dotnet/api/system.directoryservices.authenticationtypes?view=dotnet-plat-ext-6.0), you can use `Encryption`, which has the same value as `SecureSocketsLayer`

**Comment by mpatrick210** [comment]
@Yvand tried the "Encryption" type, and it fails with:

Unable to connect to LDAP for following reason: The server is not operations. It may be expected if w3wp process of central admin has intentionally no access to LDAP server.

**Comment by Yvand** [comment]
@mpatrick210 can you try to connect to your LDAP using LDAPS on the SharePoint machine, as the SharePoint farm/apppool account, using ldp.exe as [documented here](https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/enable-ldap-over-ssl-3rd-certification-authority#verify-an-ldaps-connection) ?

**Comment by Yvand** [comment]
I did some tests and I think it works if you use the following settings:
LDAP path: `LDAP://dc.contoso.local:636/CN=Users,DC=contoso,DC=local`
[Authentication type](https://docs.microsoft.com/en-us/dotnet/api/system.directoryservices.authenticationtypes?view=netframework-4.8): `Encryption, Secure`

Can you give this a try?
Note that, according to my tests, the path is case sensitive: Make sure to type `LDAP://` and not `ldap://`

**Comment by Yvand** [comment]
@mpatrick210 were you able to validate if it works using the settings above?

**Comment by mpatrick210** [comment]
Hey @Yvand I was able to use our domain LDAP://domain.com:636 - but it would not allow us to add new users to sites via the People Picker on our production farm...tested same on our Test and Stage farms, and it seemed to work. FYI - I did not select Encryption or Secure, and did not put the entire path to the domain/containers - so trying to play with that a little bit to see what I may have missed...

**Comment by mpatrick210** [comment]
@Yvand  Thank you for the further details...I will test these on my test environment and let you know what I find. Thanks!

**Comment by Yvand** [comment]
@mpatrick210 I tried again and now both scripts fully use LDAPS over SSL.
I'm not sure why I observed differently previously.
But the outcome is that LDAPCP can use LDAPS over SSL if the path looks like this:
`LDAP://contoso.local:636/CN=Users,DC=contoso,DC=local"`
According to my tests the enum AuthenticationTypes does not even matter.
Can you confirm this on your end?

**Comment by mpatrick210** [comment]
hey @Yvand I will test this approach...my last tests seemed to work on my dev/test farms, but for the production farm, it seemed to break...it would allow "some" users, but not all...it was very odd behavior

**Comment by mpatrick210** [comment]
Hey @Yvand just a quick follow up....I was able to get this to work, turns out it was an issue with cert chain...the reason it worked on lower tiers was that it only had 1 WFE, where as Prod had 6...thought I had update the cert on all of them, but missed a few, and caused the intermittent issues on some of teh WFEs. I appreciate your assistance and support on helping me try and figure this all out. :-) Have a great weekend!

**Comment by Yvand** [comment]
@mpatrick210 very good news, thanks for the update!
