### ISSUE TITLE
Augmentation does not work with OpenDJ

### ISSUE THREAD

**Issue by Odi81** [Yvand/LDAPCP#164]
We are using SharePoint with OpenDJ. Augmentation does not work, because group membership attribute is "isMemberOf". 
https://backstage.forgerock.com/docs/opendj/2.6/configref/is-member-of-virtual-attribute.html

LDAP query only includes attributes "memberOf" and "uniquememberof". Result in Log message:
[LDAPCP] Got 0 group(s) for user "###" in 568 ms from LDAP server "LDAP://###.com:636"

We need an option to change attributes used for augmentation or this there a way to configure?

**Comment by Yvand** [comment]
@Odi81 I will be away this week but I will come back to you next week on this topic
Thank you for your patience

**Comment by Odi81** [comment]
@Yvand Yes, we need group based authorization. We have tested the claims provider after extending the GroupMembershipAttributes variable and it worked.

![unnamed](https://user-images.githubusercontent.com/112546549/189837512-6fd8080b-7fd3-4c13-ac26-af4b0a363689.png)

If this can be included in a future release, the issue will be solved.

**Comment by Yvand** [comment]
Noted. Indeed, for the time being you can manually edit this property to include your LDAP property, which is exactly what the code change would do anyway.
Thanks for reporting this
