### ISSUE TITLE
Augmentation and workflow permissions

### ISSUE THREAD

**Issue by Jo311** [Yvand/LDAPCP#165]
Hi,

We are using LDAPCP in a SP16 and SP19 environment and we have an issue with augmentation and AD group membership based permissions when starting Sp2013 workflows.
The error we get when starting a workflow is "_Access denied. You do not have permission to perform this action or access this resource._"

In the LDAPCP settings we have the “Use .Net helper” option activated only, so “Query this server” is not activated.
In this scenario a user cannot start Workflows if he/she is assigned permission via an AD group. 
In the ULS logs we get this message: _[LDAPCP] No group found for user <username> during augmentation_

Note: Assigning direct permission in SP to the user works fine.

If we **also** enable “Query this server”, users are able to start WFs based on AD group membership.
Same story if we **only** enable “Query this server” : they can start WFs
In the ULS logs we can see that claims are resolved now.

A side effect we have though when we also enable “Query this server” is this:
We have put filters in our ADFS config to only forward group claims starting with sp_ and additionally added a filter in the LDAPCP Role claim type to only show groups starting with sp_. This was done as we have  a huge number of groups being used historically for all kinds of purposes and we want SharePoint to only use these sp_ groups

This works nicely with only “Use .Net helper” selected.

If “Query this server” is selected however, all AD groups the user is member of are retrieved. A user only having permissions via such an unwanted group would also have access to a site then. This is nit what we want.

Can you tell us how to fix this?

Kind regards,
Jo

**Comment by Yvand** [comment]
@Jo311 your observations are basically correct, let me add some precisions:
- option "query this server" determines if this connection is used to get group membership. If it is not set, then this connection is skipped
- when “Use .Net helper” is set: LDAPCP [gets group membership](https://github.com/Yvand/LDAPCP/blob/43b7723c032bf2d0a5cbe8a80e87f3a618a02d9e/LDAPCP/LDAPCP.cs#L1356) using [UserPrincipal.GetAuthorizationGroups()](https://learn.microsoft.com/en-us/dotnet/api/system.directoryservices.accountmanagement.userprincipal.getauthorizationgroups?view=netframework-4.8), which does not accept any LDAP filter, so applying the LDAP filter set on the group claim type would be impossible/challenging.
- when “Use .Net helper” is NOT set: LDAPCP [gets group membership](https://github.com/Yvand/LDAPCP/blob/43b7723c032bf2d0a5cbe8a80e87f3a618a02d9e/LDAPCP/LDAPCP.cs#L1476) by reading the value of the LDAP property that stores the group names in user object. Here it would also be impossible/challenging to use a LDAP filter.

So I don't see an easy solution for your scenario. Is it that bad to return all the groups?

**Comment by Jo311** [comment]
@Yvand
Thanks for the info.
The way I understand this is that it makes no sense in selecting “Use .Net helper” or not, as long as "query this server" is not selected?

So, as a solution to our initial problem that WFs cannot be started if permissions are given with AD groups, "query this server" must be selected. Selecting “Use .Net helper” or not does not have an influence on this.

I did some extra tests, it looks like if “Use .Net helper” is  NOT selected (but "query this server" is), besides the groups sent by ADFS starting with sp_, LDAPCP will also find AD groups not starting with sp_ where the user is directly member of.
If “Use .Net helper” is  also selected, LDAPCP will find a whole bunch of additional parent (nested) groups. Not selecting “Use .Net helper” seems like the better approach.

In our case these additional groups in both scenarios are a possible issue because we are migrating sites from SP16 (where PP is showing all groups) to SP19 (where PP is only showing sp_ groups). 
If permissions were given on a site to a group not starting with sp_ in SP16, that user will still be able to get access to the migrated SP19 site – which is not what we want.
If "query this server" would not be activated, that specific group claim would not be present and therefore the user would not be able to access the site.

On the other hand, thinking on it now, there are probably ways around this for us to handle as part of the migration scenario. E.g. get a list of these “non-sp_” groups and get rid of them in a proper way.

**Comment by Jo311** [comment]
@Yvand 
Ok thx you can clos
