### ISSUE TITLE
Unable to remove email address from people picker popup without breaking quickedit on 2019/SE.

### ISSUE THREAD

**Issue by renzska** [Yvand/LDAPCP#166]
Thanks for your work on LDAPCP. It's been a life saver.

My main goal is to get rid of the "(Email Address)" people picker choices and have both the regular form people picker and the list quick edit people picker work. I want the displayName in the People Picker choices with Title below the displayName. Unfortunately, I cannot get this working correctly.

I'm trying to resolve an issue with the list quick edit people picker breaking when removing the emailaddress claim type and mail attribute claim. I'm doing this to remove results from the people picker showing up as "(EmailAddress) user@domain.com" as we want the only items to show in the people picker as their displayName.

The default my site is showing is both the email address picker choices in addition to the displayName options depending on what I type. Here are my modified settings:

![image](https://user-images.githubusercontent.com/13021263/195948246-28f3d83b-4e36-4ec7-b0eb-5872db8f8d28.png)

Here are the claims configuration properties when the people picker shows "(EmailAddress) user@domain.com":

![image](https://user-images.githubusercontent.com/13021263/195948306-a7c25b33-5f11-46cc-988c-8f0c4f6139a6.png)

The first image below is showing his upn in () which is an email address in the following format: id@domain.edu. The second image is showing the ad mail property which first.last@domain.edu for the (EmailAddress) entry I'm trying to remove.

![image](https://user-images.githubusercontent.com/13021263/195947914-f0afe693-dc9c-4ddf-b152-3b3142a43a6e.png)

I can get the email address removed from the people picker if I delete the following claim settings, but then the List Quick Edit People Picker is broken:

![image](https://user-images.githubusercontent.com/13021263/195948449-4100c586-0b0a-43f2-adb7-d569c8b078d3.png)

Once I do that, however, then the List Quick Edit for the People Picker breaks and gives the following error when trying to save a new record: "The user does not exist or is not unique." I'm assuming it needs the mail property. However, the regular form people picker works fine at this point.

Any help in getting this resolved would be appreciated.

Thanks,

John

**Comment by renzska** [comment]
Forgot to include this before:

Get-SPTrustedIdentityTokenIssuer Output:

UseStateToRedirect            : False
ProviderUri                   : 
ProviderSignOutUri            : 
DefaultProviderRealm          :
ProviderRealms                : {}
ClaimTypes                    : {http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress, http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn, 
                                http://schemas.microsoft.com/ws/2008/06/identity/claims/role, http://schemas.microsoft.com/ws/2008/06/identity/claims/primarysid}
HasClaimTypeInformation       : True
ClaimTypeInformation          : {UPN, EmailAddress, Role, SID}
ClaimProviderName             : LDAPCP
UseWReplyParameter            : True
UseWHomeRealmParameter        : False
GroupClaimType                : 
RegisteredIssuerName          : 
DefaultClientIdentifier       : 
ScopedClientIdentifier        : 
AuthorizationEndPointUri      : 
TrustedLoginMethod            : None
ResponseTypesSupported        : 
Scope                         : 
IdentityClaimTypeInformation  : Microsoft.SharePoint.Administration.Claims.SPTrustedClaimTypeInformation
Description                   : ADFS 3.0 Provider
SigningCertificate            : [Subject]
                                  CN=
                                
                                [Issuer]
                                  CN=
                                
                                [Serial Number]
                                  
                                
                                [Not Before]
                                  1/31/2017 8:05:20 PM
                                
                                [Not After]
                                  1/29/2027 8:05:20 PM
                                
                                [Thumbprint]
                                  
                                
AdditionalSigningCertificates : {}
MetadataEndPoint              : 
IsAutomaticallyUpdated        : False
Name                          : ADFS
TypeName                      : Microsoft.SharePoint.Administration.Claims.SPTrustedLoginProvider
DisplayName                   : ADFS
Id                            : 3034d275-35a6-4234-ae19-f6bf16aa6726
Status                        : Online
Parent                        : SPSecurityTokenServiceManager Name=SecurityTokenServiceManager
Version                       : 206573
DeploymentLocked              : False
Properties                    : {}
Farm                          : SPFarm Name=SPSE_Config
UpgradedPersistedProperties   : {}

-------------

(Get-SPTrustedIdentityTokenIssuer).IdentityClaimTypeInformation


DisplayName                    : UPN
InputClaimType                 : http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn
MappedClaimType                : http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn
IsIdentityClaim                : True
AcceptOnlyKnownClaimValues     : False
ClaimValueModificationAction   : None
ClaimValueModificationArgument : 
KnownClaimValues               : {}
UpgradedPersistedProperties    :

**Comment by renzska** [comment]
And this:

Get-SPClaimProvider 


DisplayName                 : System
Description                 : Provides system claim data.
IsEnabled                   : True
IsUsedByDefault             : True
IsVisible                   : True
AssemblyName                : Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c
TypeName                    : Microsoft.SharePoint.Administration.Claims.SPSystemClaimProvider
ClaimProvider               : Microsoft.SharePoint.Administration.Claims.SPSystemClaimProvider
ClaimProviderType           : Microsoft.SharePoint.Administration.Claims.SPSystemClaimProvider
IsValid                     : True
UpgradedPersistedProperties : {}

DisplayName                 : Active Directory
Description                 : Active Directory claim data.
IsEnabled                   : True
IsUsedByDefault             : False
IsVisible                   : False
AssemblyName                : Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c
TypeName                    : Microsoft.SharePoint.Administration.Claims.SPActiveDirectoryClaimProvider
ClaimProvider               : Microsoft.SharePoint.Administration.Claims.SPActiveDirectoryClaimProvider
ClaimProviderType           : Microsoft.SharePoint.Administration.Claims.SPActiveDirectoryClaimProvider
IsValid                     : True
UpgradedPersistedProperties : {}

DisplayName                 : All Users
Description                 : Provides identity provider claim data.
IsEnabled                   : True
IsUsedByDefault             : True
IsVisible                   : True
AssemblyName                : Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c
TypeName                    : Microsoft.SharePoint.Administration.Claims.SPAllUserClaimProvider
ClaimProvider               : Microsoft.SharePoint.Administration.Claims.SPAllUserClaimProvider
ClaimProviderType           : Microsoft.SharePoint.Administration.Claims.SPAllUserClaimProvider
IsValid                     : True
UpgradedPersistedProperties : {}

DisplayName                 : Forms Auth
Description                 : Forms Based Authentication claim data.
IsEnabled                   : True
IsUsedByDefault             : False
IsVisible                   : True
AssemblyName                : Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c
TypeName                    : Microsoft.SharePoint.Administration.Claims.SPFormsClaimProvider
ClaimProvider               : Microsoft.SharePoint.Administration.Claims.SPFormsClaimProvider
ClaimProviderType           : Microsoft.SharePoint.Administration.Claims.SPFormsClaimProvider
IsValid                     : True
UpgradedPersistedProperties : {}

DisplayName                 : User Profile Claim Provider
Description                 : User Profile Claim Provider
IsEnabled                   : True
IsUsedByDefault             : True
IsVisible                   : True
AssemblyName                : Microsoft.Office.Server.UserProfiles, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c
TypeName                    : Microsoft.Office.Server.Security.UserProfileClaimProvider
ClaimProvider               : Microsoft.Office.Server.Security.UserProfileClaimProvider
ClaimProviderType           : Microsoft.Office.Server.Security.UserProfileClaimProvider
IsValid                     : True
UpgradedPersistedProperties : {}

DisplayName                 : LDAPCP
Description                 : LDAPCP
IsEnabled                   : True
IsUsedByDefault             : True
IsVisible                   : True
AssemblyName                : ldapcp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=80be731bc1a1a740
TypeName                    : ldapcp.LDAPCP
ClaimProvider               : ldapcp.LDAPCP
ClaimProviderType           : ldapcp.LDAPCP
IsValid                     : True
UpgradedPersistedProperties : {}

**Comment by renzska** [comment]
Here are the settings we used on SharePoint 2013 with LDAPCP v3.7.0.0 that worked the way I'm hoping we can get to work on SharePoint 2019 and SharePoint Subscription Edition:

![image](https://user-images.githubusercontent.com/13021263/195963214-0a0c01fb-1b8c-4094-9875-53f62321b352.png)

**Comment by Yvand** [comment]
@renzska deleting the email address claim type in LDAPCP claims list is the correct approach to get rid of entries like "(EmailAddress) user@domain.com" in the people picker.
The error you got in the quick edit view is because a permission on this claim type already exists, so you need to delete it and recreated under the UPN claim type first

**Comment by renzska** [comment]
Thanks for the reply. The 3.7.0.0 is from an old environment that I was using to compare against the new environment running the latest v15, which is where we are having the issue. 

I’m not sure what you mean when you say:

> The error you got in the quick edit view is because a permission on this claim type already exists, so you need to delete it and recreated under the UPN claim type first

I’d appreciate it if you could give me more detail on what you meant.

**Comment by Yvand** [comment]
This issue won't repro in a new list. But if you add a people column and add a user like "(EmailAddress) user@domain.com" you will reproduce it.
You'll need to first delete this user and re-add it in UPN claim format

**Comment by renzska** [comment]
We have opened a ticket with Microsoft and they have been able replicate
the issue in their environment and it is not related to LDAPCP. They will
keep us updated on the issue as they work through it.

Thanks,

John
