### ISSUE TITLE
Default logging level triggers Health Analyzer rule

### ISSUE THREAD

**Issue by ykuijs** [Yvand/LDAPCP#167]
The default logging level of the LDAPCP\Debug category triggers the Health Analyzer rule "One or more categories are configured with Verbose trace logging". It might be better to set the logging level to Medium for that category as well, so users can set this to VerboseEx when necessary.

![image](https://user-images.githubusercontent.com/15103891/200286106-529de78a-90a2-4b41-b107-2b8f18993e70.png)

**Comment by Yvand** [comment]
Thank you for reporting this! This is a dumb mistake: It should be verbose(ex) by default only in the DLL compiled in debug mode, but it was also verbose in release mode...
I just changed it in https://github.com/Yvand/LDAPCP/commit/fee51aa81cfbeff338ed4771c3184539f4cda09b
