### ISSUE TITLE
Additional LDAP filter for user attributes applies to group

### ISSUE THREAD

**Issue by lehuspohus** [Yvand/LDAPCP#171]
Hi! I'm trying to understand, how this settings works. 
1) When I just fill the field "Additional LDAP filter" and save the LDAPCP settings by pressing OK, this field clears and nothing being updated at LDAPCP settings in ConfigDB.
As I understand, I have to fill this field and click _Apply to all user attributes_ every time I am making changes? So Apply to all user attibutes is the only purpose of this field in _Global configuration_? 
I mean the value of this field is not saved anywhere unless i click _Apply to all user attributes_, right?

2) It says: _Additional LDAP filter for entries with SPClaimEntityTypes set to "User"_ but when I'm clicking _Apply to all user attributes_ it applies also to group attributes. Is it correct?
![image](https://user-images.githubusercontent.com/15194209/215888484-28518eca-8544-4b84-8b42-2bf741c28daa.png)

3) Given this settings, I can only apply this additional filter either to only editable "main" claim types or to the whole bunch of all claim types? But not to specified set of claim types?

**Comment by Yvand** [comment]
Hi @lehuspohus 
About 1: You are correct
About 2: I repro the same behavior, and it is a bug, only entries with Entity type "User" should be updated. I will fix this
About 3: You can do it on a specific entry only using PowerShell, using [this sample](https://www.ldapcp.com/docs/usage/configuration/#show-the-current-configuration) as a starter.
