### ISSUE TITLE
"Check Permissions" token cache

### ISSUE THREAD

**Issue by StefanPlizga** [Yvand/LDAPCP#174]
Hi @Yvand 

In the troubleshooting section for LDAPCP, you wrote:
“Check permissions” feature is not working 
This usually means that the non-interactive token does not contain the group membership.
**This token is per site collection and cached for 1 day.**

We have a case where the Check Permissions is not making any request to LDAP to check the user permissions for a given user, I think it is related to that. It worked after we deleted the user account from the Site Collection (people.aspx?MembershipGroupId=0), then LDAPCP did a proper LDAP query.

If there a way to clear the cached token that you mention in your troubleshooting notes?

**Comment by Yvand** [comment]
There is no supported way to clear this cache, but it is possible to lower its lifetime to force its expiration (farm wide setting):

```powershell
$cs = [Microsoft.SharePoint.Administration.SPWebService]::ContentService
# Default value:   New-TimeSpan -Days 1
$cs.TokenTimeout = New-TimeSpan -Minutes 1
$cs.Update() 
```

Be careful when setting a low value such as 1 min, this impacts some accounts like the superuser / superreader and SharePoint can no longer use them, resulting in access denieds on publishing sites.

**Comment by StefanPlizga** [comment]
Thank you for the answer!
