### ISSUE TITLE
Filtering on Custom ldapcp

### ISSUE THREAD

**Issue by weswilliams901** [Yvand/LDAPCP#182]
With LDAPCP we see that the LDAP filters can be configured via Powershell. Can the same powershell commands be used to configure the custom solution or it can only be the actual LDAPCP solution.

Is it possible to add the filters directly to the custom solution

**Comment by Yvand** [comment]
It can be configured also on a custom solution, what matters is the name of the configuration which you call the method `[ldapcp.LDAPCPConfig]::GetConfiguration("<LDAPCPConfigName>")`
