### ISSUE TITLE
LDAPCP not being queried when assigning targeted audiences (navigation, list items, etc)

### ISSUE THREAD

**Issue by WEIGLBRC-Taylor** [Yvand/LDAPCP#184]
We have LDAPCP set up on our single server sharepoint 2019 farm with augmentation turned on.

I have found that LDAPCP is not being queried when attempting to assign targeted audiences to navigation, list items, or anyone targeted audiences are selected.

I realized that LDAPCP might not be working because the search wasn't returning any groups with "(Role)" prepended.  I then ran thru the troubleshooting steps [here](https://www.ldapcp.com/docs/help/troubleshooting/) to collect the LDAPCP logs.  I set the verbosity of the logs to VerboseEx, attempted to set a targeted audience on my navigation items, pulled the LDAPCP logs for the last 5 minutes, and didn't see my search anywhere in the logs.

Is there any way we can get LDAPCP to perform searches and return groups for targeted audiences?

**Comment by WEIGLBRC-Taylor** [comment]
I appreciate the prompt reply!  I ended up making sharepoint groups and adding roles from LDAPCP to those groups.  I then used the sharepoint groups as my target audiences.  Not an ideal solution, but it works :D

Also, thanks for making LDAPCP, it's really great!

**Comment by Yvand** [comment]
@WEIGLBRC-Taylor it is actually a pretty elegant solution, I forgot that audiences can use SP groups, thanks for sharing!
