### ISSUE TITLE
Target Audience not working for LDAPCP groups added to sharepoint groups

### ISSUE THREAD

**Issue by WEIGLBRC-Taylor** [Yvand/LDAPCP#188]
I initially put in [this issue](https://github.com/Yvand/LDAPCP/issues/184) re: targeted navigation and LDAPCP groups.
I found that if I added LDAPCP users to a sharepoint group, and assigned the sharepoint group as a target audience for the navigation (structured current or structured global) the end result was success!  I assumed the same would be true re: adding LDAPCP groups to a sharepoint group.

Unfortunately, I tested this out yesterday and when I added an LDAPCP group that my AD user is a member of to a sharepoint group that was the target audience of a navigation item, I was still not able to see the navigation item.

I'm hoping you can provide me with some insight or troubleshooting suggestions, as I'm not really sure how to move forward...

TIA!

Taylor

**Comment by WEIGLBRC-Taylor** [comment]
That is one type of an audience, a compiled audience.
Apologies for not being more specific.  The type of audience I am using is the audience for Navigation items.
I have attached a screenshot.
<img width="638" alt="Screenshot 2023-09-19 at 10 49 45 AM" src="https://github.com/Yvand/LDAPCP/assets/114699323/1f4f52d2-fdbb-4de2-a216-60d69449c034">

**Comment by Yvand** [comment]
@WEIGLBRC-Taylor sorry for the late reply.
I'm not sure how this particular configuration is supposed to work. Did you enable the augmentation in LDAPCP configuration?

**Comment by Yvand** [comment]
It could be a limitation, yes. In any case, I really don't see anything to do in LDAPCP side to fix this, sorry...
