### ISSUE TITLE
Results Not showing - 2016

### ISSUE THREAD

**Issue by barnabus86** [Yvand/LDAPCP#19]
We have installed LDAPCP on our SP2016 Farm, but when we attempt to add a user via their display name, we are told that there is 1 result, but nothing is returned

![image](https://user-images.githubusercontent.com/8266512/30066467-e0a1f058-924f-11e7-91ba-b442a4b112de.png)

It works fine if you add the user via their SAMAccountName.

**Comment by Yvand** [comment]
Can you check SharePoint logs and filter on Product/Area LDAPCP ?

**Comment by barnabus86** [comment]
Thanks for the quick response.

I've had a look in the logs on both of our WFE Servers and can only see the following with a Area of LDAPCP

[LDAPCP] LdapcpConfig PersistedObject changed, refreshing configuration	af4b169e-bcb8-905a-1330-573c79e468af

Looking further in to the logs, i can see the following


[LDAPCP] Got 3 result(s) in 0ms from <ldap Server>


[LDAPCP] Added permission: claim value: "<Users Display Name>", claim type: "http://schemas.microsoft.com/2012/01/devicecontext/claims/isregistereduser"	d54b169e-bc92-905a-3b7c-676cf146b6da

because Name is a protected Claim, i have mapped display name from Adfs (Adfs v4/2016) as "isregistereduser" (this is only a test environment).

Some of our users have a normal user account and a domain admin account. If i search for any of these users by name, it shows 2 results, but only displays the Domain Admin account (we wouldn't want to give these accounts permissions).

To add, we are running LDAPCP v2017.06

**Comment by Yvand** [comment]
It's a bit weird
Can you show the claims mapping configuration in central admin > security > LDAPCP claims mapping page?

**Comment by barnabus86** [comment]
![image](https://user-images.githubusercontent.com/8266512/30103523-d2617482-92ea-11e7-9e1f-0a9fbbd03a4a.png)

We were previously mapping the UPN against the LDAP attribute UPN, but decided to use sAMAccountName instead. I haven't updated the ADFS claim type to "windows account name" as i already had UPN mapped as a  claim type in my trusted token issuer. I'm happy to change this if you think it makes a difference.

**Comment by Yvand** [comment]
The last row may be the cause of this: it duplicates the displayName attribute on the previous row (the "linked to identity claim" one).
But do you really need the claim type isregistereduser? I don't think it makes sense to bind a claim type to the attribute displayName: it's not unique and 2 users may have the same.

Can you try to remove isregistereduser row and see if results are returned correctly?
Otherwise, if you really need isregistereduser claim type, you may remove the displayName row "linked to identity claim"

**Comment by barnabus86** [comment]
Hi Yvand,

Removing the isregistereduser has resolved the issue.

Thanks for the help.

LDAPCP has really saved us a lot of time in our move to ADFS Authentication.

**Comment by Yvand** [comment]
Awesome, thank you for your feedback :)
