### ISSUE TITLE
Domain groups can't be added after resolving it in people picker

### ISSUE THREAD

**Issue by shaimaafarouk9** [Yvand/LDAPCP#190]
Hi Yvand,
Could you please advice on why the domain groups with "role" prefix is resolved in people picker but after click share to add it to SharePoint i got the below error.

![SharingError](https://github.com/Yvand/LDAPCP/assets/106921416/4e24bc2d-f04b-45d1-987a-b3b87b372eb9)

**Comment by Yvand** [comment]
Can you check the SharePoint logs and filter on product/area LDAPCP, to see exactly what is happening?

**Comment by shaimaafarouk9** [comment]
i checked the logs but didn't find errors related to this issue could you please advice why this happened for the groups only and working fine with the users?

**Comment by shaimaafarouk9** [comment]
i found the below error : 


[] Unexpected error occurred while getting domain names information for LDAP connection LDAP://utcapp.com/DC=utcapp,DC=com (DirectoryServicesCOMException): System.DirectoryServices.DirectoryServicesCOMException: An operations error occurred.  , Callstack:   
at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)    
at System.DirectoryServices.DirectoryEntry.Bind()    
at System.DirectoryServices.DirectoryEntry.get_AdsObject()    
at System.DirectoryServices.PropertyCollection.Contains(String propertyName)

**Comment by Yvand** [comment]
@shaimaafarouk9 this error typically happens when you use the default connection to AD, and can be fixed by deleting it, and creating one explicitly with a dedicated service account.
