### ISSUE TITLE
need to remove the users with (role) prefix

### ISSUE THREAD

**Issue by shaimaafarouk9** [Yvand/LDAPCP#192]
Hi Yvand,
Here are the claims types configuration i use for ldapcp and when matching a user in people picker i got 2 entitles one for the user itself and other with the user that has prefix (role).
![LDAPClaims](https://github.com/Yvand/LDAPCP/assets/106921416/5c5e7071-c5da-431a-9bb0-216fca3794a7)

Is there any customization i need to do in the ldapcp code or from the configuration to remove the record of the user that has (role) prefix?

![Role](https://github.com/Yvand/LDAPCP/assets/106921416/5a2ee79f-b210-43bb-aee9-d18621c18623)

**Comment by Yvand** [comment]
Hi @shaimaafarouk9, if you really do not want the people picker to return groups, in LDAPCP claim types mapping page you can delete the role claim type (the bold blue one in your screenshot).
But after that, you won't be able to create permissions based on trusted groups
