### ISSUE TITLE
LDAP Filter for Two Classes

### ISSUE THREAD

**Issue by weswilliams901** [Yvand/LDAPCP#194]
We have two classes, User and Contact. Long story we have to find users and contacts in our AD. With LDAPCP, is possible to filter for both using one Claim Provider, or we can only filter for one or the other?

**Comment by Yvand** [comment]
I assume you want to search both classes User and Contact for the identity claim type permission.
If so, it should be possible if you do the following:
- Go to central admin > Security > LDAPCP Claim types configuration
- Add a new item with:
  - Set "Add a mapping between a LDAP object and the main corresponding object type"
  - Set "LDAP object class" to Contact
  - Set "LDAP object attribute" to whatever you need
- Click Create

Please let me know if it does what you need

**Comment by weswilliams901** [comment]
That work great. Thanks so much for that.

But we see the display name shows when searching but when the user is selected, it is still displaying the lan id. See the attachment. Is there a way to have jsmith look like Smith, Joe. (FYI- Joe Smith is a windows user.
![group](https://github.com/Yvand/LDAPCP/assets/138236731/89ee9d77-fffd-4916-99fa-9a3e8eeb6593)
)

**Comment by Yvand** [comment]
The short answer is that this is the job of the user profile service to sync the display name to the sites.
With that said, claims providers have a chance to set the display name if, and only if, the user is added for the very 1st time to the site collection. If user is re-added after it was deleted from a site, it won't work
