### ISSUE TITLE
Augmentation does not work with Nintex Workflow and Other third party

### ISSUE THREAD

**Issue by EliNsr** [Yvand/LDAPCP#195]
Hi,
We are using LDAPCP in a SP19 environment and we have an issue with augmentation and AD group membership on "Nintex Workflow Tasks" And "Column/View Permission Boost solution".
Nintex Workflow:
When we assign task to group on nintex, the group find and pick, after run the workflow we get "Error in task. The user to assign the task to has resolved as blank text".
Column/View Permission Boost solution:
We can pick the group but it doesn't work.
My augmentation configuration:
![Argmentation](https://github.com/Yvand/LDAPCP/assets/74496805/af0ba439-d5b3-43a2-89c1-bbe186493aae)
and my Claim Type Configuration:
![ClaimTypeConfiguration](https://github.com/Yvand/LDAPCP/assets/74496805/7d93a81f-2c5d-4321-bfcb-7311b8b4d1fc)
we didn't get any error on log file about LDAPCP Area.
Thank You

**Comment by Yvand** [comment]
@EliNsr does it happen only when using Nintex?
Does it work fine if you grant access to a trusted group in a site, and try to access as a user member of this group (and with no epxlicit permissions)?

**Comment by EliNsr** [comment]
> @EliNsr does it happen only when using Nintex? Does it work fine if you grant access to a trusted group in a site, and try to access as a user member of this group (and with no epxlicit permissions)?

Hi
Yes it works.
When i grant permission to the group A in the site, the member of group A have permission ,if i use this group to assign task in nintex it doesn't work.

**Comment by Yvand** [comment]
@EliNsr I don't know how Nintex workflows run and I don't have it in a test environment to investigate this.
Do those workflows run in the SharePoint processes, or in a separate process?
If it is in a separate process, it may explain why the error and the absence of message in the logs
