### ISSUE TITLE
Searching by Name on samAccountName

### ISSUE THREAD

**Issue by weswilliams901** [Yvand/LDAPCP#196]
![claim](https://github.com/Yvand/LDAPCP/assets/138236731/131b1851-0bd8-4668-9486-0205e6c642d3)
Attached is our Claim Type Config.
We are authenticating via sAMAccountName to the IdP. The ID looks like jsmith. However, the user base doesn't know a person's lan ID, they know to search by Jane Smith to resolve her ID in People Picker. So the only way to resolve Jane Smith is by typing jsmith.

Is there a way for the user to type Jane Smith or Smith, Jane to resolve jsmith in People Picker. We still want the claim attribute to be sAMAccountName = jsmith.

Is there a way to accomplish this by searching by name or the user has to know the lan ID in order to be resolved?

**Comment by Yvand** [comment]
@weswilliams901 yes this is possible.
To clarify:
- In the green bold line: you must specify the LDAP attribute used by SharePoint to uniquely identify the user. It looks like it is the lan ID based on your description
- Then, you can define as many additional LDAP attributes (used for search) as needed, by creating a new item using the option "Add a mapping between a LDAP object and the main corresponding object type"

Does it answer your questions?
