### ISSUE TITLE
User Can't receive emails

### ISSUE THREAD

**Issue by weswilliams901** [Yvand/LDAPCP#197]
We are filtering AD for user via LAN(sAMAccount). Attached is the configuration. However, we are able to get alerts, request access, or anything email related. What are the steps to keep LAN as the main attribute but also be able to receive emails from the various events in SharePoint. Is this possible for the users to receive emails?
![email](https://github.com/Yvand/LDAPCP/assets/138236731/044d3afa-208d-4092-bf74-dffca93555fe)

![config](https://github.com/Yvand/LDAPCP/assets/138236731/b682cbc4-0917-4cef-911e-ae6919bd7c47)

**Comment by Yvand** [comment]
In the LDAPCP claims mapping configuration, you need to have a mapping for the email, similar to this:

![image](https://github.com/Yvand/LDAPCP/assets/8788631/7568a38e-cf9b-43c0-b85a-a2ff2873d380)
