### ISSUE TITLE
EntraCP claimprovider issue

### ISSUE THREAD

**Issue by subas-hub** [Yvand/LDAPCP#198]
Hi @Yvand ,
Please could you help me to fix this issue on EntraCP. I am not sure why EntraCP is looking for ldacp.

PS C:\Windows\system32> $adfs1 = Get-SPTrustedIdentityTokenIssuer "AzureADTrust"
$adfs1.ClaimProviderName = "EntraCP"
$adfs1.Update()
Exception setting "ClaimProviderName": "Could not load file or assembly 'ldapcp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=80be731bc1a1a740' or one of its dependencies. The system cannot find the file specified."
At line:2 char:1

$adfs1.ClaimProviderName = "EntraCP"
  + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
  + FullyQualifiedErrorId : ExceptionWhenSetting

Exception calling "Update" with "0" argument(s): "Could not load file or assembly 'ldapcp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=80be731bc1a1a740' or one of its dependencies. The system cannot find the file
specified."
At line:3 char:1

$adfs1.Update()
  + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  + FullyQualifiedErrorId : FileNotFoundException

**Comment by Yvand** [comment]
Hi @subas-hub, EntraCP does not need LDAPCP, but I assume that SharePoint finds LDAPCP when it parses the existing claims providers, and somehow it cannot load it

what is the output of this cmdlet:
`Get-SPClaimProvider`

is ldapcp.dll installed in the GAC of the machine where you run your commands?

**Comment by subas-hub** [comment]
Hi @Yvand 
thanks for your response. Yes, ldapcp.dll is still there in C:\Windows\Microsoft.NET\assembly\GAC_MSIL\ldapcp\v4.0_1.0.0.0__80be731bc1a1a740 as i have previously installed and seems like uninstallation not cleared out. 



DisplayName                 : LDAPCP
Description                 : LDAPCP
IsEnabled                   : True
IsUsedByDefault             : True
IsVisible                   : True
AssemblyName                : ldapcp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=80be731bc1a1a740
TypeName                    : ldapcp.LDAPCP
ClaimProvider               : ldapcp.LDAPCP
ClaimProviderType           : ldapcp.LDAPCP
IsValid                     : True
UpgradedPersistedProperties : {}

**Comment by Yvand** [comment]
Can you test if this command runs successfully:
`Add-Type -AssemblyName "ldapcp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=80be731bc1a1a740"`
