### ISSUE TITLE
error in LDAPCP configuration page

### ISSUE THREAD

**Issue by swanle** [Yvand/LDAPCP#20]
Hi Yvand

I edited some information in Claims mapping and now I see this error display whenever I open  Global Configuration page.  
I deleted the entry in http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role  in Claims mapping page

I see this error "There is no claim type associated with an entity type 'FormsRole' or 'SecurityGroup'  display on top of Global Configuration page.  I think may i need to recreate the entry again but I like to understand what I did and how to fix this.  

could you explain what happen and how i can fix it.

Thanks

Swanl

**Comment by Yvand** [comment]
Hi @swanle 
LDAPCP searches an entry with entity 'FormsRole' or 'SecurityGroup', and uses its claim type for the groups it creates if augmentation is enabled.
If there is none, augmentation does not happen.
By default claim type http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role is set with 'FormsRole', so (if LDACP augmentation is enabled), groups will be created with this claim type.
Does it make sense?
thanks,
Yvan

**Comment by Yvand** [comment]
@swanle any update on this?

**Comment by swanle** [comment]
Yvand

I apologize.   I didn't get an email alert of your reply on Sept 14.   I got one today 11/7.   Yes,  I got it back working now.

Thanks so much for the explanation.  Yes it make sense.

Swanl

**Comment by Yvand** [comment]
No worries, thank you for your feedback :)
