### ISSUE TITLE
LDAPCPSE An item with LDAP newAttribute 'userPrincipalName' and LDAP class 'user' already exists for the object type 'User'

### ISSUE THREAD

**Issue by Paconaut** [Yvand/LDAPCP#204]
Hi @Yvand

Appreciate if you can help me understand why I get the following error preventing me from opening Global configuration and Mapping of permissions under SharePoint Server 2019 central admin after installing LDAPCPSE v17.0.20240226.2:

"An item with LDAP newAttribute 'userPrincipalName' and LDAP class 'user' already exists for the object type 'User'"

LDAPCP Classic uninstalled by following the documentation.

Thanks in advance!

**Comment by Yvand** [comment]
@Paconaut to understand your scenario, can you please send the output of those commands:

```powershell
Add-Type -AssemblyName "Yvand.LDAPCPSE, Version=1.0.0.0, Culture=neutral, PublicKeyToken=80be731bc1a1a740"
$config = [Yvand.LdapClaimsProvider.LDAPCPSE]::GetConfiguration()
$config.Settings.ClaimTypes | ft LDAPAttribute, EntityType, ClaimType, UseMainClaimTypeOfDirectoryObject
```

```powershell
$trust = Get-SPTrustedIdentityTokenIssuer "YOUR_SPTRUST_NAME"
$trust.ClaimTypeInformation | fl MappedClaimType, IsIdentityClaim
```

**Comment by Paconaut** [comment]
@Yvand Thanks for your help!

[Yvand.LdapClaimsProvider.LDAPCPSE]::GetConfiguration() return nothing
[Yvand.LdapClaimsProvider.LDAPCPSE]::ClaimsProviderName return "LDAPCPSE"

MappedClaimType : http://schemas.xmlsoap.org/ws/2005/05/identity/claims/UPN
IsIdentityClaim : True

MappedClaimType : http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
IsIdentityClaim : False

MappedClaimType : http://schemas.microsoft.com/ws/2008/06/identity/claims/role
IsIdentityClaim : False

**Comment by Yvand** [comment]
Can you try to create the configuration using this command:

```powershell
[Yvand.LdapClaimsProvider.LDAPCPSE]::CreateConfiguration()
```

**Comment by Yvand** [comment]
Definitely looks like a bug, I will try to repro using the same claim types in the trust and come back to you, most likely next week.
In the meantime, if it is possible/acceptable for you, you can consider a workaround by removing the claim type `emailaddress` from the trust (I would totally understand you reject this test)

**Comment by Paconaut** [comment]
I excluded emailaddress but still the same error messages in central admin and PowerShell.

**Comment by Yvand** [comment]
@Paconaut FYI, I was able to repro exactly the same error, I'll investigate and report the progress in this thread

**Comment by Yvand** [comment]
I confirm this is a bug, fixed in https://github.com/Yvand/LDAPCP/pull/205
