### ISSUE TITLE
[LDAPCPSE] question about search result windows size in peoplepicker

### ISSUE THREAD

**Issue by dep-begj** [Yvand/LDAPCP#210]
Hi,

we have recently upgraded from the depricated old version to the ldapcp SE.
and things are working very well but we experience a small bug with the new version.

if we push share on the front page of a sharepoint site, the search result is a very small 2 results even if the total search result for that query  is 30 users/groups.
but if we enter site settings > permissions > choose feks owner group and push new. the search result windows shows 5 results.
In the old ldapcp it showed 5 result in both places, and that is what we would prefer.

do you have any insight into this issue?
is this something that could be configurable in ldapcpse? 

i hope my explanation is understandable.

(this is for an on-prem sharepoints server subscription edition enviroment with latest cu updates)

**Comment by Yvand** [comment]
@dssbegj I did a few tests and I think I am missing something.

- In a modern team site, on the homepage I click share: I get more than 2 results from LDAPCP (I got 5 but I'm sure I could get up to 30)
- When you get only 2 results, in LDAPCP logs, how many results does LDAPCP return to SharePoint?

**Comment by dssbegj** [comment]
good morning. i see now i failed to inform you that we mostly use clasic design on our sitecollections still. 

so if i search for a security group, it says on the bottom of the search result windows "showing 29 results" but the window size is showing only 2 so i have to scroll a lot to see trough the entire result.

i hope this is a more understandable explanation.

here is also a screenshot 
![image](https://github.com/Yvand/LDAPCP/assets/98583076/b437e966-032c-4aae-986f-2b1a15164938)

its not a huge issue, but i figured if there is a way to configure it it was worth it to ask.

**Comment by Yvand** [comment]
@dssbegj yes I understand now, and I can reproduce the same issue, but there is nothing LDAPCP can do about this:
It is SharePoint that decides to display only 2 results at a time and a claims provider cannot influence that

**Comment by dssbegj** [comment]
thank you for taking the time to reply.
