### ISSUE TITLE
Filter on Active user by default

### ISSUE THREAD

**Issue by SwissYann** [Yvand/LDAPCP#215]
Hi Yvand,

Very nice improvment about the second edition of LDAPCP !

During my testing, I discovered that by default, the ACTIVE user filter is added to every query
 - !(userAccountControl:1.2.840.113556.1.4.803:=2)

Even if i check/uncheck the "Exclude disabled users".
So some of my accounts are missing.

I don't know if I'm missing a configuration or if it's a bug but any help is appreciated.

Thanks,

Yann

**Comment by SwissYann** [comment]
I was able to fix it
![image](https://github.com/Yvand/LDAPCP/assets/160483053/1e04ecea-e49b-464f-9629-cb7866e5591a)

But for me it must be false by default because the box is not checked.

**Comment by Yvand** [comment]
Hi @SwissYann, latest release v18 fixes an issue where some properties, including FilterEnabledUsersOnly, were not initialized correctly, I believe this is the issue you noticed.
Did you update to v18 ?

**Comment by SwissYann** [comment]
Hi @Yvand, yes i took v18. FilterEnabledUsersOnly is set to true by default while the check box "Exclude disabled users" is not checked.

**Comment by Yvand** [comment]
I won't be able to test before 10 days.
Can you please clarify if it does the opposite of the setting displayed in global admin (even if you change it), or if FilterEnabledUsersOnly always remains set to true no matter what you set?

**Comment by SwissYann** [comment]
Hello @Yvand, this only works if you reinstall a new version of the wsp (without using Update-SPSolution in my case).
So I can Close, thank you :)
