### ISSUE TITLE
Security regrading the package

### ISSUE THREAD

**Issue by SuyogMahindrakar** [Yvand/LDAPCP#219]
HI Team,

We would like to use this package in our Organization, but we are getting security related queries regarding this package.

So do you have any source of proof to justify there is no data Leake by this package. 

This package is also recommended on Microsoft site, so do you have any proof (Blog or Article) justify security of this package.

**Comment by Yvand** [comment]
@SuyogMahindrakar I'm not sure what kind of proof you request?
This project is open source, you can review the code.
And it is compiled by GitHub itself through GitHub actions, so you can review the build pipeline to ensure it does not contain anything malicious. And if you don't trust that process, then you can easily compile it yourself.
