### ISSUE TITLE
Group Augmentation fails with email and AD

### ISSUE THREAD

**Issue by mrbubble62** [Yvand/LDAPCP#22]
When requestInfo.IncomingEntity.Value type is email

adUser = UserPrincipal.FindByIdentity(principalContext, requestInfo.IncomingEntity.Value)

FindByIdentity always returns null

**Comment by mrbubble62** [comment]
This solution works for email but will break every other type..

` using (PrincipalContext principalContext = new PrincipalContext(ContextType.Domain, directoryDomainFqdn))
                    {
                        using (UserPrincipal user_principal = new UserPrincipal(principalContext) { Enabled = true, EmailAddress = requestInfo.IncomingEntity.Value })
                        using (PrincipalSearcher user_searcher = new PrincipalSearcher(user_principal))
                        using (PrincipalSearchResult<Principal> results = user_searcher.FindAll())
                        {
                            UserPrincipal adUser = (UserPrincipal)results.First();
                            if (adUser == null) return groups;
`

**Comment by Yvand** [comment]
I will investigate this and let you know my findings

**Comment by mrbubble62** [comment]
I think you'll find UserPrincipal.FindByIdentity's IdentityType does not support email.

https://msdn.microsoft.com/en-us/library/bb356425%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396

**Comment by Yvand** [comment]
Thank you for your analysis, you are correct, current implementation doesn't work with emails.
I'm updating the code to check if current claim type is an email, and if so implement basically your solution.

**Comment by Yvand** [comment]
I published a new release (v2017-10) that fixes this bug. Can you please try it out?

**Comment by Yvand** [comment]
Closing as I got no feedback from @mrbubble62
