### ISSUE TITLE
Challenges with User Identification and Activity Logging in LDAPCP on SharePoint 2013

### ISSUE THREAD

**Issue by BrunaFortes** [Yvand/LDAPCP#220]
I'm using the old version of LDAPCP because our servers are running SharePoint 2013. Although I've installed LDAPCP, I'm encountering a few issues.

First, I can only select users by their email addresses, and any activity gets registered with the email instead of the user's name. For example, if I update a list item, it saves my email instead of my name. Is there a way to fix that?

The second issue is a bit more complicated. After installing LDAP, it created a new user ID for one of the users. Now, I can't filter correctly if the user is listed in a people column because the list item and the system have different user IDs for the same person. I'm still investigating this, but I'd like to know if anyone else has faced a similar problem before.

**Comment by Yvand** [comment]
@BrunaFortes I assume the identifier for the users is the email, so it is normal and expected that the user accounts in SharePoint appear with the email.
You may want to show the display name instead, like for Windows accounts. It is possible, but this is mainly the job of the User Profiles service. So you need to create the user profiles of the trusted users in the User Profiles service and set their display name. Then that will be propagated to the user accounts in the site collections.

Note that, in the User Profiles directory, you should NOT create 2 directory synchronizations (1 for Windows accounts and1 for  trusted accounts) for the same AD directory.
