### ISSUE TITLE
LDAPCPSE - Display attribute match in parenthesis

### ISSUE THREAD

**Issue by snooooowy** [Yvand/LDAPCP#226]
Hi, thank you for this amazing solution. 

We're performing an upgrade from LDAPCP to LDAPCPSE and would like to check if there's an equivalent of this option "If input matches an attribute linked to identity claim (typically the displayName) show its value in parenthesis." in LDAPCPSE. Or is there any other way to show the matched attribute in a parenthesis?

**Comment by Yvand** [comment]
Hi @snooooowy, thank you for your feedback.
LDAPCPSE always show the attribute that matched the inpt if you hover your mouse on the people picker entry. Does that fit your needs?

**Comment by Yvand** [comment]
No worries, no, this is not possible.
Do you have a special use-case that would make this display helpful?
