### ISSUE TITLE
Should Results Autocomplete Just as with NTML?

### ISSUE THREAD

**Issue by jshenderson** [Yvand/LDAPCP#24]
I'm a big fan of this tool. I'm using it to implement SSO in our organization via ADFS. I have have couple of questions that I'm not sure are issues, but could be miss configuration.

1. I'm having trouble with showing results in people pickers. It shows my result if I type it in exactly, but it does not auto populate results (ie. "Josh") - there are several Josh's, but not even mine pops up in results. I have to type in my full name as it is shown in Display Name, or my exact GID. Then it shows my 1 result.
![capture1](https://user-images.githubusercontent.com/6308291/31771795-fd8b0fd6-b4a2-11e7-9223-11d089a17ee0.PNG)
---------------------------
![capture](https://user-images.githubusercontent.com/6308291/31771763-e1f8693a-b4a2-11e7-9094-cc758a3d2314.PNG)

2. As you can see in the 2nd screenshot above, I'm not getting the Display Name where it should show. It's showing email instead. How can I change this to show the DisplayName?

**Comment by Yvand** [comment]
Hello, 
you should check LDAPCP configuration in central admin > security > LDAPCP global config:
- about the exact search, ensure that exact search is not enabled?
- about the display name, you can type which attribute you want to display in section "Display of permissions created with identity claim"
If config is not working as expected, you can check SharePoint logs and filter on Product/Area "LDAPCP"

**Comment by jshenderson** [comment]
Thank you for your response. 

1. This is not checked. However, it's not exactly "exact match" it's just that it's not showing results like with NTLM. Meaning, if i type Josh in CA, which uses NTLM, it gives me a list of Josh's even if their name is Joshua in AD. But with ADFS, and LDAPCP I get no results. Then with "Lucas" it pulls back several results. it's confusing as to why some will show and not others.

2. YES! This did it thank you.

**Comment by Yvand** [comment]
Good :)
For the user search, you should check ULS logs to get the LDAP request sent.
Then you can replay it on your own with PowerShell to understand why it doesn't return results you expect.
Check http://ldapcp.com/Troubleshoot-LDAPCP.html to see how to replay LDAP queries

**Comment by Yvand** [comment]
@jshenderson any news on issue 1?

**Comment by jshenderson** [comment]
@Yvand I'm still working this. However, I do not believe it is a LDAPCP issue. It's really strange. Any web app I connect to on the CA server I pull back full results in the people picker, but on both of my WFEs I get zero results. Have you ever seen this before? The only difference is the WFEs are load balanced with an F5.

**Comment by Yvand** [comment]
To clarify if LDAPCP plays a role in this issue, you should check SharePoint logs and filter on Product/Area "LDAPCP", it will show you if LDAPCP returns permissions correctly

**Comment by Yvand** [comment]
@jshenderson, any news on issue 1?
