### ISSUE TITLE
LDAPCP - EnsureUser issue

### ISSUE THREAD

**Issue by Albino1006** [Yvand/LDAPCP#27]
Hello Yvan,

We have a scenario where certain users have their ID which is a subset for other user's ID like the below example.

User with ID: dpatil

For this user when we search in people picker with LDAPCP we see multiple entries like dptail1, dpatil2, dpatil10. In other words dpatil is a subset for other login IDs as well.

Now we have a service url that pulls the data from a list in SharePoint. Below is the snippet of the code that runs while accessing the service URL.
*****************************************************************
public static string GetCurrentUserLoginName(string loginName, ClientContext clientContext)
        {

            var spUser = clientContext.Web.EnsureUser(loginName);
            clientContext.Load(spUser, user => user.LoginName);
            clientContext.ExecuteQuery();
            return ConvertUsernameToClaim(clientContext, spUser.LoginName);
        }
*****************************************************************
When such users (whose ID is a substring for other users ID as well in AD) try to access this service URL, they get error message “The specified user <userid> could not be found” in the browser.

However when we use the “Exact match” option in LDAPCP configuration page, this issue doesn’t occur for these users. But we cannot opt for this option for business reasons.

**Question**: Is there anything from LDAPCP side that can be done to tackle such scenarios when one user ID is a subset for other user IDs and accessing these service URLs?

Awaiting your reply. Thanks.

**Comment by Yvand** [comment]
Hi Albino,

LDAPCP does what it is asked by SharePoint: a lookup based on the input (supplied as a string) that should return all results found.
You are hitting a design limit of SharePoint implementation: input as a string always triggers a lookup that can return 1 to many results.

It's only when inputs is supplied as a SPClaim that (custom) claims provider must return exactly 1 result.

There is nothing that can be done in LDAPCP to mitigate that, except what you already found: force LDAPCP to always do an exact LDAP lookup. But even that may not work if the input (string) matches values of multiple LDAP attributes (e.g. sAMAccountName and givenname, or mail and userPrincipalName).
