### ISSUE TITLE
Modifying LDAPCP mapping with powershell

### ISSUE THREAD

**Issue by Albino1006** [Yvand/LDAPCP#28]
Hello Yvan,

Is it possible to modify LDAPCP Claim mapping with **powershell**, if yes can you share some example commands. We are basically trying to edit the current mappings of type **"Add a LDAP attribute to query and specify claim type of the permission"**. Awaiting your reply. Thanks.

**Comment by Yvand** [comment]
Hi Albino,
unfortunately it's currently not possible, it's something I would like to make but this represents a significant work.
