### ISSUE TITLE
Placeholder for images

### ISSUE THREAD

**Issue by Yvand** [Yvand/LDAPCP#3]
![ldapcp_ppicker](https://cloud.githubusercontent.com/assets/8788631/25440203/f57202f2-2a9e-11e7-819e-30e2f5361cb4.PNG)

**Comment by crossan007** [comment]
Images would be a great addition to the "search as you type" lookup box.

**Comment by Yvand** [comment]
![ldapcp_ppicker](https://cloud.githubusercontent.com/assets/8788631/25440961/3b8db40a-2aa1-11e7-9070-aee808950f38.PNG)

**Comment by Yvand** [comment]
@crossan007 I created this issue only to store some images that I plan to use in md files :)
I'm not sure I got your suggestion, can you please explain?

**Comment by crossan007** [comment]
Ah - I interpreted this as an idea to include the user's profile image within the LDAPCP result selection list to the left (or right) of the user name:

![image](https://cloud.githubusercontent.com/assets/11679900/25441265/b4ba9406-2a6f-11e7-8dc0-1673f74ea7ec.png)

**Comment by crossan007** [comment]
@Yvand for storing the images (for use in readme.md?) you could check them into a new branch in the project too...

**Comment by Yvand** [comment]
@crossan007 ah, yes, indeed, I could (and probably should) do that...
Regarding your suggestion, it is really great, but it's not something that can be implemented in a custom claims provider.
You should submit this idea in [SharePoint uservoice](https://sharepoint.uservoice.com/)

**Comment by crossan007** [comment]
Posted: https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration/suggestions/19057273-include-user-profile-photos-in-the-people-picker-r
