### ISSUE TITLE
Sharepoint Alert issue

### ISSUE THREAD

**Issue by EWAS-ANZ** [Yvand/LDAPCP#35]
Hi Team

We having issues in setting up an alert for groups in Sharepoint 2010 and when we were working with Microsoft they advised us to download and install the LDAPCP file available on your website but we aren't able to update or add the solution. Please advise if the software available for download is compatible with Sharepoint 2010 or is it of use only for Sharepoint 2013 and 2016.

If you could share the suitable file that would be compatible with Sharepoint 2010.

Thanks
Rohini

**Comment by Yvand** [comment]
Hello,
In this repo there is no version available for SharePoint 2010.
You have 2 options:
- Download the source code and compile it for SharePoint 2010
- Download the very old and outdated LDAPCP 2010 available here: https://ldapcp2010.codeplex.com/ Note that this version is completely outdated and has bugs that may be blocking for you

**Comment by EWAS-ANZ** [comment]
Hi 

We are actually working with Microsoft and they mentioned that for SP 2010 they aren't able to find the below settings in the file ClaimsTable.aspx as seen in SP 2013, so is there a way to add that settings? 

$('#rowClaimEntityType').hide('slow')
by this:
$('#rowClaimEntityType').show('slow')

**Comment by Yvand** [comment]
It is missing much more than that, all the logic in the code behind to handle this is also missing.
To fit your needs you have only the 2 options I mentioned above

**Comment by Yvand** [comment]
@EWAS-ANZ did you make any progress?
