### ISSUE TITLE
LDAPCP with SP16

### ISSUE THREAD

**Issue by alpachi** [Yvand/LDAPCP#37]
Hi, I am having trouble with configuration. I have configured as specified in the documentation and receiving some issues in the SharePoint logs with the following:

[LDAPCP] Got 0 result(s) in 2ms from "LDAP://domain.com/DC=domain,DC=com" with query "(| (&(objectclass=user)(userPrincipalName=user.name@domain.com)) )"

**Additional info:**
-My Claim Identifier is "userPrincipalName" which shows as the users email address, test.user@domain.com
-The user account login is similar to: tuser

Any help to get me over the hill here? Thanks!

**Comment by Yvand** [comment]
Hello, an easy way to troubleshoot this is to reply the LDAP query using PowerShell, so you can investigate why LDAP server returns nothing.
You can check [page Troubleshoot-LDAPCP](http://ldapcp.com/Troubleshoot-LDAPCP.html) to find how to do this

**Comment by alpachi** [comment]
Here is some additional info from troubleshooting, still no progress:
[LDAPCP] Got 0 result(s) in 2ms from "LDAP://domain.com/DC=domain,DC=com" with query "(| (&(objectclass=user)(userPrincipalName=user.name@domain.com)) )" 

My thought is, is there a way I can map the incoming claim for userPrincipalName to Email?
The authentication for SP16 only works when using UPN from the Trusted Claims Provider, but if i can tell LDAPCP to map to email, that may help me to resolve.

Any suggestions? much appreciated.

**Comment by Yvand** [comment]
Hi @alpachi, can you clarify what you mean exactly by mapping "the incoming claim for userPrincipalName to Email"?
Is it SharePoint or LDAPCP that should do some mapping?
In LDAPCP, you have the claims mapping page in central admin > security that lets you configure as you need the mapping between LDAP attribute and claim types. Isn't it what you are looking for?

**Comment by alpachi** [comment]
I was able to map out the configuration and narrow this down. Initially i thought to map the incoming claim from upn to mail, but thats incorrect. The way someone configured the Provider as it sends claims to SharePoint was incorrect. Once this was corrected, I reconfigured SharePoint to match the claim identifier and Namespaces, then things worked just fine. Thank you!
