### ISSUE TITLE
Help needed to unserstand our issue with the Filtering

### ISSUE THREAD

**Issue by eduralph** [Yvand/LDAPCP#39]
We've been having an issue in which the validation of a selected user from the people picker was filtered out by the system. The relevant log entries are

[LDAPCP] Got 1 result(s) from all LDAP server(s) with query "(| (&(objectclass=user)(userPrincipalName=******)) )"
[LDAPCP] 0 permission(s) to create after filtering

I looked at the code and honestly couldn't make out what the filter criteria were. Would you minde to share the list of all criteria which would lead to LDAPCP filtering out results?

Thanks!

**Comment by Yvand** [comment]
The filtering is done in LDAPCP.ProcessLdapResults() method.
There can be a lot of reasons why a result is removed by the filtering. 
If you want, you can clone the source code, download the 
symbols from [LDAPCP_Debug.zip](https://github.com/Yvand/LDAPCP/releases) and live debug to find out why it is excluded.
It's heavy but it will work...

**Comment by Yvand** [comment]
Hi @eduralph, did you figure out what was wrong?

**Comment by eduralph** [comment]
Hi Yvand,

thanks for following up. The issue was occuring in the production environment and we were hesitant to install a Debug version, so we couldn't drill as deep as we would have liked. Ultimately, it was an issue with a) the network connection to the AD Servers or b) the responses the AD Servers were bringing back. We could never really figure that one out as the issue vanished after a couple of days.
So, it wasn't LDAPCP but it would have been nice to be able to see the return responses and the specific filter which was applied in the logs (maybe verbose?) to understand the issues.

**Comment by Yvand** [comment]
Hi @eduralph, there are too many reasons to filter out a potential result to record that in SharePoint logs, even in Verbose(Ex):
LDAPCP parses each LDAP attribute of each LDAP result, and keep only relevant values (to transform in PickerEntity result) based on many criteria. 
In case you want to take a look, this logic is implemented in [method LDAPCP.ProcessLdapResults()](https://github.com/Yvand/LDAPCP/blob/0f18b52b898d4e832b4b91f3961d4afbfce9f857/LDAPCP/LDAPCP.cs#L735-L827)
