### ISSUE TITLE
People Picker showing disabled AD users

### ISSUE THREAD

**Issue by MiikkaLehtonen** [Yvand/LDAPCP#40]
We have users that still appear that have been  a) deactivated in AD, b) removed from the User Information List, c) user doesn't exist in UPA and d) deleted browser cookies and form data. In LDAPCP global configuration page ->  Exclude disabled users (as documented in KB 827754) is checked.

Any ideas?

Thanks,
Miikka Lehtonen

**Comment by Yvand** [comment]
Do you reproduce the same behavior in a new site collection?

**Comment by MiikkaLehtonen** [comment]
Yes, it's same behavior in the new site collection.

**Comment by Yvand** [comment]
Then you can use SharePoint logs and filter on Product/Area "LDAPCP" to understand why the disabled user is returned.
The log will show the LDAP query executed, and you can replay it using the PowerShell script [here](http://ldapcp.com/Troubleshoot-LDAPCP.html).

**Comment by ldapcphelp** [comment]
configured LDAPCP with AZURE AD, however people picker is showing blocked and disabled users. Is there anything that I am missing?

**Comment by MiikkaLehtonen** [comment]
Hi, thank you for your answer. It seems that the LDAP query is working (I used PowerShell script). The browsers Firefox and Chrome are working and I can’t see disabled users. For the users I searched before they were disabled I have to empty browser history and after that I can’t see them anymore. Strange thing is that with the Internet Explorer I can see disabled users whatever I try to do… Any ideas?

**Comment by Yvand** [comment]
People picker stores results in a local storage cache in the browser. 
I thought this was the reason why you got disabled users, and why I initially asked you to try in a new site collection (results are stored per site collection).
To clear it, you can use the developer's toolbar of the the browser (press F12) and run this in the console:
```javascript
localStorage.clear();
```
After that, old results should be gone
