### ISSUE TITLE
LDAPCP Solution deploy error 

### ISSUE THREAD

**Issue by MontanaMT** [Yvand/LDAPCP#41]
I have been trying to deploy the solution and I am getting an error after following your fix issues with the setup due to it not installing right.  The error on one server is The definition specifies a claim provider with a name already in use.  What did I miss cleaning up?

**Comment by Yvand** [comment]
It looks like SPClaimProvider object was not deleted, can you check if this commands returns it:
```powershell
Get-SPClaimProvider -Identity "LDAPCP"
```
If so, you can remove it:
```powershell
Get-SPClaimProvider -Identity "LDAPCP" | Remove-SPClaimProvider
```
Please let me knw if it worked, if so I'll add these steps to [Fix-setup-issues page](http://ldapcp.com/Fix-setup-issues.html)

**Comment by MontanaMT** [comment]
When I run the command it doesn't find any custom claims providers and I am on getting the error on one server.

**Comment by Yvand** [comment]
How do you reproduce the error, and what is the exact error message?

**Comment by MontanaMT** [comment]
The error happens when I redeploy the solution using Central admin.  One server errors with The definition specifies a claim provider with a name already in use.  I can force the solution to deploy but then the claimprovider never shows up.

**Comment by Yvand** [comment]
Solution deploys globally on all servers, it should not work on some and fail on others.
- How many SharePoint servers do you have?
- On how many servers do you have an error?
- On servers reporting the error:
  - Are those servers running SharePoint service “Microsoft SharePoint Foundation Web Application”?
  - Do they have "LDAPCP" folder created in folder C:\Program Files\Common Files\microsoft shared\Web Server Extensions\15\TEMPLATE\FEATURES ?

**Comment by MontanaMT** [comment]
I was finally able to get back into the test environment and I still can't get the $trust.claimprovidername to work.  I get an error of Claim provider with name LDAPCP does not exist.

**Comment by Yvand** [comment]
On the server that thows this error, can you run this
```powershell
Get-SPFeature -Identity "LDAPCP"
```
If it finds the feature, can you run this:
```powershell
Get-SPFeature -Identity "LDAPCP" | Enable-SPFeature
```
