### ISSUE TITLE
LDAPCP for Developers.zip

### ISSUE THREAD

**Issue by hippolascage** [Yvand/LDAPCP#42]
Hi

Is this "LDAPCP for Developers.zip" still available somewhere? It's referenced in the code and over at ldapcp.com but I can't seem to locate it anywhere.

**Comment by Yvand** [comment]
Hello, it is published with each release and you can find it in [releases page](https://github.com/Yvand/LDAPCP/releases)

**Comment by hippolascage** [comment]
Thanks!
