### ISSUE TITLE
[LDAPCP] Added permission: claim value: "System.Byte[]"

### ISSUE THREAD

**Issue by ricorocca** [Yvand/LDAPCP#43]
Hi,
We have an issue during pickup a user only for one webapplication (there is 5 webapplication):
Ldapcp return System.Byte[], and we have an error when we select it.

**Comment by Yvand** [comment]
I don't know how you got that error.
Can you filter SharePoint logs on Product/Area "LDAPCP" to get more information?

**Comment by Yvand** [comment]
Without a reliable repro it will be tough to troubleshoot.
- Does issue affect 1 claim type? Multiple/all?
- Do other results (in the same search) display correctly while you repro issue?
- Do you query AD servers?

**Comment by chrisgett** [comment]
We're using LDAPCP to query one active directory domain for ADFS-Claims. There is only one identity Claim (UPN) configured, some other possible claims (e.g. Name, mail, samaccountname) are mapped to this one. 
When the issue occurs all claims from this domain are shown with System.byte[]. Users from another domain using windows authentication (and therefore not LDAPCP) are displayed correctly. So in fact all LDAPCP results are broken.
Additional User Information such as the title is displayed as usual in the result.

I dont' know if this is relevant, but we're using exactly the same configuration in three different farms for over one year now. So far the only farm on which this is happening is the farm using Project Server (including Project Server permission mode).

**Comment by Yvand** [comment]
Thank you for the details, a couple more questions: 
- Is UPN claim type mapped to LDAP attribute "userPrincipalName"?
- When you repro this issue in a web app, can you repro it in central administration (e.g. in "change site collection administrators" page)?

**Comment by chrisgett** [comment]
•Is UPN claim type mapped to LDAP attribute "userPrincipalName"? => Yes
•When you repro this issue in a web app, can you repro it in central administration (e.g. in "change site collection administrators" page)? => I don't know as we're normally not using LDAPCP in the Central Administration  (All Admin-Accounts are in the other Domain). I will try this the next time the Issue occurs.

**Comment by micholus** [comment]
Hi.
We are facing exactly te same issue, but in our case IIS reset doesn't help :(
What is interesting we are using one provider for 2 web apps and on one of them everything is working fine, we are facing issues only on the second one (though it was working for sometime).
