### ISSUE TITLE
Augmented setting doesn't seem to work with check permissions

### ISSUE THREAD

**Issue by ldapcphelp** [Yvand/LDAPCP#45]
Enabled the augmentation setting under ldapcp configuration page. Did a refresh and clear cache. Unfortunately while doing a checkpermissions on a user that is part of a security group the group is not listed. 
Any additionally recommendations?

**Comment by Yvand** [comment]
"Check permission" feature relies on a special (called non-interactive) token that has a lifetime of 24h by default.
So after you enabled augmentation in LDAPCP, you need to wait at least 24h to be sure you use a non-interactive token that had a chance to be augmented by LDAPCP.
If you don't want to wait, here is how you can change its lifetime:
```powershell
$cs = [Microsoft.SharePoint.Administration.SPWebService]::ContentService
$cs.TokenTimeout = New-TimeSpan -Minutes 1
$cs.Update() 
```
It's default value is [1440 minutes](https://msdn.microsoft.com/en-us/library/office/microsoft.sharepoint.administration.spwebservice.tokentimeout.aspx?f=255&MSPPError=-2147217396).
You need to restart IIS on all servers after that.
