### ISSUE TITLE
Inquiry: LDAPCP Installation on more than Web Server

### ISSUE THREAD

**Issue by jrbelmonte** [Yvand/LDAPCP#47]
Hi,

Great component! Solves our issue on the people picker when using ADFS as the Auth Provider. However, I'd like to ask this one, we have another SP that is going to use this one, it has more than one Web Server and its behind a Load Balancer, that being said do we need to run the PS to install LDAPCP to all Web Servers? Appreciate if you can provide your thoughts on this. Thanks.

**Comment by Yvand** [comment]
Hi @jrbelmonte 
you need to run Add-SPSolution / Install-SPSolution only once, in 1 server.
But, as [documented here](http://ldapcp.com/Install-LDAPCP.html), you need to manually copy ldapcp.dll on the GAC of SharePoint servers that do not run SharePoint service “Microsoft SharePoint Foundation Web Application”

**Comment by jrbelmonte** [comment]
thanks will check it out
