### ISSUE TITLE
LDAPCP doesn’t work for multiple claims provider 

### ISSUE THREAD

**Issue by Albino1006** [Yvand/LDAPCP#48]
Hello @Yvand,

At present, we have a web application in SharePoint configured with an Identity Provider, with LDAPCP as a claim provider. Everything works as per the requirements in this case.

Now we have another web application in same SharePoint farm configured with a different Identity Provider. At this point, when tested the sites were accessible for this new second webapp. Now in this case when we try to map the same LDAPCP for the second webapp, the Claims mapping and the Global configuration page in Central Admin site loses it initial settings and the mapping values.

We had to remove the Identity Provider from the second webapp. After doing this, the Claims mapping and the Global configuration page in Central Admin site got its initial settings and mapping values restored back.

We would like to know how can we configure LDAPCP to work for multiple claims provider in the same SharePoint farm?

Awaiting your reply. Thanks.

**Comment by Yvand** [comment]
Hi @Albino1006, due to SharePoint API limitations, you cannot use LDAPCP for 2 different SPTrustedLoginProvider.
To workaround this, you can:
- use standard LDAPCP.wsp for 1 SPTrustedLoginProvider
- use a [custom LDAPCP](http://ldapcp.com/For-Developers.html) for the other SPTrustedLoginProvider

**Comment by Albino1006** [comment]
Hello @Yvand 

Thanks for your reply.

At the moment we have the LDAPCP [https://github.com/Yvand/LDAPCP/releases/download/v2017-10/LDAPCP.wsp](url) configured on one webapp (working as expected). I think this is the one you referred to as custom LDAPCP in your reply.

Note sure what standard LDAPCP is, can you share more details on this.

Awaiting your reply. Thanks.

**Comment by Yvand** [comment]
Hello @Albino1006, for [each release](https://github.com/Yvand/LDAPCP/releases) you have:
- LDAPCP.wsp: this is the standard LDAPCP package
- LDAPCP.Developers.zip: this is the custom LDAPCP, which developers can use to understand how to create a new claims provider from LDAPCP
