### ISSUE TITLE
Bypass lookup for NTLM accounts

### ISSUE THREAD

**Issue by steveareeno** [Yvand/LDAPCP#49]
Our environment is set up to use ADFS with LDAPCP. I set the people picker so it doesn't query our NTLM AD. I set a bypass lookup so we can add external users to SP. Everything is working good.

However, I realized we have a special circumstance where I need to be able to add an NTLM user to SP permissions. I thought I could use the bypass prefix to avoid name resolution but it adds the ADFS prefix to the account when I add the permissions:
 
 i:05.t|adfs|dmz\userName

I would like it to add it like so:

 dmz\userName
 
is this possible? Can I create a special claim in SP and set LDAPCP to do this?

**Comment by Yvand** [comment]
LDAPCP can only create Trusted accounts, SharePoint doesn't allow 3rd party claims providers to create WinClaims accounts.

**Comment by steveareeno** [comment]
Thanks.
