### ISSUE TITLE
Unexpected error in AugmentEntity

### ISSUE THREAD

**Issue by EdwinWUR** [Yvand/LDAPCP#58]
I'm getting the following error on one of my two frontends, tried updating to the LDAPCP v2017-10 version but still having the same issues. Any (easy) fixes I could try?

Unexpected error in AugmentEntity: System.Runtime.InteropServices.COMException: Creating an instance of the COM component with CLSID {080D0D78-F421-11D0-A36E-00C04FB950DC} from the IClassFactory failed due to the following error: 800401e4 Invalid syntax (Exception from HRESULT: 0x800401E4 (MK_E_SYNTAX))., Callstack:    at System.DirectoryServices.ActiveDirectory.DirectoryEntryManager..ctor(DirectoryContext context)     at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)     at ldapcp.LDAPCP.GetLDAPServers(RequestInformation requestInfo)     at ldapcp.LDAPCP.<>c__DisplayClass46_0.<AugmentEntity>b__0()	653e729e-ad54-00a4-8c3b-e676486ce57a

**Comment by Yvand** [comment]
What version is deployed now?
Does the people picker work?

**Comment by EdwinWUR** [comment]
I did an upgrade from a previous version to version LDAPCP v2017-10, so that’s my current version. Did a total reinstall of LDAPCP last Friday, seems to have solved the problem, seeing the augmented groups on that serveragain. Gonna let it run for a workday day and give you an update.

**Comment by Yvand** [comment]
No worries, but just to be sure: did you check that augmentation is enabled in LDAPCP global configuration page?
