### ISSUE TITLE
We are Seeing Same User Multiple Times in the people Picker after we installed the latest LDAPCP

### ISSUE THREAD

**Issue by jaipalgithub** [Yvand/LDAPCP#60]
We are seeing user name displayed with Login, Name and Email Address  as three rows in the People Picker when we search for a Unique User. Identifier claim is configured correctly

**Comment by Yvand** [comment]
Can you show the issue with a screenshot?

**Comment by jaipalgithub** [comment]
Below is the attached image of people picker

![peoplepicker](https://user-images.githubusercontent.com/1750440/43836884-c02799ce-9ae4-11e8-990e-348b1c1b98e1.jpg)

**Comment by Yvand** [comment]
This is expected. If you want just 1 result, you can remove the claim types you don't want in LDAPCP claim types configuration page, in central administration > Security

**Comment by jaipalgithub** [comment]
I think This was not the case in the previous versions. We have two environments on with the same claimtypes in the newer one we see claim types in peoplepicker where as in the old one we dont see the issue

**Comment by Yvand** [comment]
It's true you should not really see a difference if you never changed any setting in that list, but something to have in mind is that v10 has breaking changes and that list was reset during the upgrade, so somehow it might explain why results changed after.
