### ISSUE TITLE
LDAPCP, ADFS and external users? 

### ISSUE THREAD

**Issue by richjnsn** [Yvand/LDAPCP#61]
Hi,

I have installed a Sharepoint 2016 on-premise. I have intergrated ADFS to be able to invite external users. But as we all know, after a ADFS integration the people picker doesn't resolve users from the AD very well. LDAPCP do fix this.

But, I cannot invite external user, I only getting an error message telling me that... I cant. :) Is there a setting or a way to make this possible?

**Comment by Yvand** [comment]
Hi @richjnsn 
Yes, this is possible: the idea is that you define a keywork for a given claim type.
Then, when user types the keyword in the people picker, what is after will be validated as-is. E.g.:
- You set keyword "ext:" on claim type email
- In the people picker you type "ext:email@partner.com" and LDAPCP validates "email@partner.com"

To set the keyword, go to central admin > LDAPCP claim types configuration > Edit the claim type you want > Set the keyword in column "Prefix to bypass lookup"

**Comment by richjnsn** [comment]
@Yvand That's great news! Thank you for your quick answer!
