### ISSUE TITLE
LDAPCP with AD LDS

### ISSUE THREAD

**Issue by JasonHough75** [Yvand/LDAPCP#62]
Hi there, 

I have connected our AD LDS with LDAPCP and it works fine, but I can only see Users not UserProxy accounts. We are using UserProxy accounts so that the password is not known on this side. Can LDAPCP find accounts which are UserProy in AD LDS ?

**Comment by Yvand** [comment]
I don't have a AD LDS to verify this, but I think you need to update the LDAP object class to match the class of UserProxy accounts.
You can do this in central admin > Security > LDAPCP claim types configuration page

**Comment by JasonHough75** [comment]
perfect answer, cheers!
