### ISSUE TITLE
(emailAddress) claim only works

### ISSUE THREAD

**Issue by JasonHough75** [Yvand/LDAPCP#63]
Hi there, 
We are using Sharepoint 2013 with your fab product.. ADFS works fine and so does LDAPCP.. 
When I choose a user in the people picker all I can get is (email address) bob.builder@hardwork.co.uk to work.. if I add the user as UPN then it does add but the user cannot get their permission ? Have you heard of this before ? 

Thanks, Jason.

**Comment by Yvand** [comment]
Hi, you need to clarify what value you expect (what is issued in the SAML token by the 3rd party STS), and what value (LDAP attribute) you map in LDAPCP.
What you describe suggests that thoses values are not the same, which is why permission is not granted.
