### ISSUE TITLE
How to configure: "Set a keyword to bypass LDAP lookup"

### ISSUE THREAD

**Issue by bwar01** [Yvand/LDAPCP#64]
How to configure the following?

**Set a keyword to bypass LDAP lookup**. e.g. input "extuser:partner@contoso.com" directly creates permission "partner@contoso.com" on claim type set for this.

**Comment by Yvand** [comment]
Through UI:
Go to Central Administration > Security > LDAPCP Claim types configuration page > Edit the claim type where you want to set the prefix > Set the prefix in column "Prefix to bypass lookup"

Through PowerShell:
```powershell
Add-Type -AssemblyName "ldapcp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=80be731bc1a1a740"
$config = [ldapcp.LDAPCPConfig]::GetConfiguration("LDAPCPConfig")
$ctConfig = $config.ClaimTypes.GetByClaimType("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress")
$ctConfig.PrefixToBypassLookup = "ext:"
$config.Update()
```
