### ISSUE TITLE
preceded \ in roles since last fix

### ISSUE THREAD

**Issue by tollertenya** [Yvand/LDAPCP#66]
hello,
since you fixed issue 53 new issue occured that a "\" is before the role in Account. we use {fqdn}\ as claim value prefix.

![45023757-8a03e100-b037-11e8-8570-f2a4eb07cca0](https://user-images.githubusercontent.com/8003776/45083726-d6fdbb00-b0fc-11e8-9457-02460952cabd.png)

**Comment by Yvand** [comment]
I don't reproduce this issue, results are returned as expected:
group claim type is configured with prefix "{fqdn}\\" and if I type "group1", LDAPCP returns "xcontoso.local\group1" as expected:

![image](https://user-images.githubusercontent.com/8788631/45085242-8720f300-b100-11e8-9f4f-3a2e3a717fa6.png)

In ULS logs:
```
LDAPCP	Claims Picking	1337	Verbose	[LDAPCP] Added entity: display text: '(Role) xcontoso.local\group1', claim value: 'xcontoso.local\group1', claim type: 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role'	59b48b9e-e7ab-4061-2841-bb70bd4ba80a
```

Note: Sometimes the rendering of markdown removes the \ and you need to double it. Please pay attention about this as it makes the understanding of the issue difficult

**Comment by tollertenya** [comment]
here a extract of our ULSlog
we see correct encoded LDAP search with \5c - the queried server is ADLDS Server and filled in field is adminDisplayName.
![verboselog](https://user-images.githubusercontent.com/8003776/45100959-b77d8700-b12a-11e8-8288-ead754f8406f.png)

**Comment by Yvand** [comment]
Sorry it's not clear:
- What is the expected value?
- What is the actual value?

**Comment by tollertenya** [comment]
expected is: ftest\groupname xy
actual is: \ftest\groupname xy

**Comment by Yvand** [comment]
I cannot reproduce the behavior.
I created group "group\charTest" in domain "contoso.local"

My group claim type is configured with prefix "{fqdn}\\", as returned by this script:
```powershell
Add-Type -AssemblyName "ldapcp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=80be731bc1a1a740"
$config = [ldapcp.LDAPCPConfig]::GetConfiguration("LDAPCPConfig")
$config.ClaimTypes.GetByClaimType("http://schemas.microsoft.com/ws/2008/06/identity/claims/role").ClaimValuePrefix
# output: {fqdn}\
```

I search for it and I get the entity created with expected claim value, as shown in the logs:
```
LDAPCP	Claims Picking	1337	Verbose	[LDAPCP] Added entity: display text: '(Group) contoso.local\group\charTest', claim value: 'contoso.local\group\charTest', claim type: 'http://schemas.microsoft.com/ws/2008/06/identity/claims/role'	23ddc67c-4996-0003-f4d9-dd239649d401
```

What am I missing?

**Comment by tollertenya** [comment]
we found solution that is working when we using {domain} instead of {fqdn}
