### ISSUE TITLE
Augmentation with NetIQ eDirectory 9.1

### ISSUE THREAD

**Issue by U292124** [Yvand/LDAPCP#67]
Dear Yvan,

we would like to use augmentation with LDAPCP but our LDAP is using the attributes "member" and "equivalentToMe" attributes instead of "memberof" and "uniquememberof".
Is there a way to configure LDAPCP to use these attributes for augmentation?

Thanks,
Miklos

**Comment by U292124** [comment]
Sorry I forgot one part of the question: in which form is the query for groups run agains the LDAP? LDAP requires the user FDN which is not present, only the userid (cn). For example (&(objectClass=group)(Member= cn=V23456,ou=users,ou=myunit,o=mycompany,c=com)) provides a list of groups but the is no wildcard allowed (like member= V23456*).
Perhaps a postfix for the user identifier could help here, or if it could be specified which claim to use for the group query.

Thanks,
Miklos

**Comment by Yvand** [comment]
Hi Miklos,
currently it's not possible to specify what LDAP attribute to use instead of the "member" / "memberof", but it's definitely something that I can add in a future version.
LDAPCP uses the user identifier configuration to build the query that gets group membership, e.g. the sAMAccountName="userValue" or mail="userValue", it is not resolving the groups themselves.

**Comment by Yvand** [comment]
@U292124 I have good news, I just implemented the feature in the dev branch by adding property GroupMembershipAttributes to let you specify what LDAP attributes should be used.
It can be configured in PowerShell:
```powershell
Add-Type -AssemblyName "ldapcp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=80be731bc1a1a740"
$config = [ldapcp.LDAPCPConfig]::GetConfiguration("LDAPCPConfig")
foreach ($ldapServer in $config.LDAPConnectionsProp) {
    $ldapServer.GroupMembershipAttributes = @("member", "equivalentToMe")
}
$config.Update()
```
