### ISSUE TITLE
Custom LDAP Group Members Not Authenticating

### ISSUE THREAD

**Issue by salaradili** [Yvand/LDAPCP#68]
Hi there,

We are having a weird issue where our users are not getting recognized as part of the LDAP groups. We have a custom LDAP (non-AD), and our 2010 environment with the old version of the solution (which had no augmentation) seems to be working just fine. However after upgrading to 2016 and using the new version of the LDAPCP with augmentation, we're no longer able to either Check Permission for user in an LDAP group or have the user login (receiving access denied). I have installed ClaimsViewer and confirmed that I see the http://schemas.microsoft.com/ws/2008/06/identity/claims/role showing all the memberOf attribute values including the group name that is added to SharePoint. Here is my configuration:
![image](https://user-images.githubusercontent.com/25240501/46883378-e240b680-ce1f-11e8-9126-86f35691e556.png)

![image](https://user-images.githubusercontent.com/25240501/46883392-f4225980-ce1f-11e8-8b8e-79ec781d9da7.png)

This is the error we see in the ULS logs when the user receives access denied:

[LDAPCP] No LDAP server is enabled for augmentation
--

--

e

**Comment by Yvand** [comment]
In LDAPCP global config page, in section "Augmentation", you should have a list of LDAP servers just after your screenshot where you can select 1 by 1 which ones to query for the augmentation

**Comment by salaradili** [comment]
Wanted to add two things (not sure if they are of any significance):

1- The memberOf value for our users return the group's distinguishedName as value and not the sAMAccountName. When i search for a group in Check Permission, the (Role) would show but not the users that are members of it.

2- Weirdly, when I $objSearcher to findall() based on my filter, i can find the user and see its memberOf values, however doing a $user.Properties.memberOf (capital O for memberOf) does not return anything. But $user.Properties.memberof does (lower case O for memberof). Not sure if that matters when LDAPCP searches for the memberOf value of the user.

**Comment by Yvand** [comment]
Can you follow the section "Troubleshoot augmentation" in https://ldapcp.com/Troubleshoot-LDAPCP.html ?
Then you can compare the groups returned by LDAPCP (by looking at the logs) with the groups sent by the 3rd party STS (e.g. ADFS).

**Comment by salaradili** [comment]
Okay I think i found the problem!! The mapping was happening with the sAMAccountName which was different than the output that LDAPCP was putting forth when found the groups for the user (it was a different attribute). I chose another attribute in the claims mapping (cn in my case) to exactly match that. Then I had to remove and re-add all those users and make sure the tokens are expired and are re-issued. Then voila! Thanks you can close this issue
