### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by micholus** [Yvand/LDAPCP#70]
Hi,
We are trying to deploy the latest version and after configuring we are getting an error in system logs:
An exception occurred in LDAPCP claim provider when calling SPClaimProvider.FillUserKeyForEntity(): Object reference not set to an instance of an object..

An exception occurred when trying to issue security token: Object reference not set to an instance of an object..

Please advise how can I troubleshoot this.

Thanks,
Michal

**Comment by Yvand** [comment]
Hi @micholus can you check SharePoint logs, filter on Product/Area "LDAPCP" and see if there is any exception or error?

**Comment by micholus** [comment]
> Hi @micholus can you check SharePoint logs, filter on Product/Area "LDAPCP" and see if there is any exception or error?

Hi Yvand,
The issue was resolved by doing a cleanup of the solution on all servers in the SharePoint farm and then clean installation.

Thanks!
Michal
