### ISSUE TITLE
LDAPCP compatibility with SharePoint 2019

### ISSUE THREAD

**Issue by Albino1006** [Yvand/LDAPCP#71]
Hello @Yvand,

Is LDAPCP compatible with SharePoint 2019? Can you confirm on this? Thanks.

**Comment by Yvand** [comment]
Hi @Albino1006 I couldn't find any issue during my tests, although I didn't have time to make many, so I'm confident it works just fine with SharePoint 2019.
My plans is to make complete tests with the next version of LDAPCP (currently in dev) and explicitely mention compatibility of the project with SharePoint 2019 when I release it.
