### ISSUE TITLE
FBA users DisplayName

### ISSUE THREAD

**Issue by pensphreak** [Yvand/LDAPCP#72]
I've been using LDAPCP in SP2013 for a long time and this one thing has always bothered me.  Now I'm using it in SP2016 and I thought I'd try to figure out how to fix it.  I have ADFS and FBA setup as authentication methods and when I search for a user I get the following results back

If I search for "smith", I may get:

Smith, John @ Company
smithj

The first one is the user in ADFS, and it shows their DisplayName properly.  The second is from FBA.  No matter where I set the DisplayName (UserInfo list or their User Profile), I always just get their username back.  

Is there any way to setup FBA to return a better formatted DisplayName instead of just the username?

**Comment by Yvand** [comment]
hi @pensphreak FBA has its own dedicated claims provider that talks with the FBA membership provider / role manager.
as far as I remember, membership provider can only return the actual value, and not additional metedata like a display name. This is why the display for FBA users is like you observed.
And just in case you ask, the FBA membership provider cannot be replaced
