### ISSUE TITLE
Exclude NTLM domain users from People Picker

### ISSUE THREAD

**Issue by Anagirl921** [Yvand/LDAPCP#76]
We have SharePoint 2016 on Prem. We have both NTLM and ADFS on the Default zone because of the search issue. the People picker is now showing both the ADFS user and the NTLM user. Is there a way to exclude the NTLM user name?

**Comment by Yvand** [comment]
@Anagirl921sorry for my late reply, yes it's possible with some SharePoint configuration, but LDAPCP can do nothing about this.
A good way is to set property SPPeoplePickerSettings.ActiveDirectoryCustomFilter with a fake filter, for example : 

```powershell
$wa = Get-SPWebApplication "http://sp16/"
# Some users like super user / super reader / crawl account should have this value in AD, so they can be resolved when SharePoint uses them
$wa.PeoplePickerSettings.ActiveDirectoryCustomFilter = " (&(telephoneNumber=00110011)) "
$wa.Update() 
```

As the comment says, it's very important that super user / super reader / crawl account have this value in AD, so they can be resolved when SharePoint uses them
