### ISSUE TITLE
External users in AD and 2 way Trust users not in People Picker

### ISSUE THREAD

**Issue by Anagirl921** [Yvand/LDAPCP#77]
SharePoint 2016 on prem - ADFS and NTLM on default zone. We have external users in our AD that do not have a outlook mailbox. they do not show up in the people picker unless they are given a mailbox. What am I missing? I am sure it is a setting but cant wrap my head around it. 

Somewhat related. we have external users that we have a 2 way trust with (so they can use their own log in to get into our domain). in our 2010 environment we were able to just add their AD\Domain users and they had access but with the LDAPCP on this new 2016 environment they do not show up in the people picker (i ran the same powershell we ran in 2010 to add their forest).

**Comment by Yvand** [comment]
@Anagirl921 what is the identity claim type used for trusted users? If it's the email, then it's expected that users who don't have an email are not returned by LDAPCP

About the trusted domain, I think you may need to add a LDAP connection to query. You can do that in central admin > security > LDAPCP global configuration
