### ISSUE TITLE
Augmentation problem

### ISSUE THREAD

**Issue by micholus** [Yvand/LDAPCP#78]
Hi.
I have configured LDAPCP with our SharePoint and everything looks fine except the groups augmentation. I can query for the AD group, give it permissions on SP sites but users can not access the sites based on group membership.
What I found in the logs is:
      Starting augmentation for user 'user'.
	Verbose	[LDAPCP] LDAP queries to get group membership on all servers completed in 0ms	
	Medium	[LDAPCP] No group found for user 'user' during augmentation	

Does it mean that the group membership query failed ?

Regards,
Michal

**Comment by micholus** [comment]
Hi,
I'm still facing the issue, any clues what can I check ?

Regards,
Michal

**Comment by Yvand** [comment]
Hi @micholus based on the logs output, I suspect you didn't check the box "Query this server" on any server in the "Augmentation" section in LDAPCP global configuration page. Can you check this?
