### ISSUE TITLE
Usernames not showing with displayname

### ISSUE THREAD

**Issue by savila202501** [Yvand/LDAPCP#79]
Hi,
I am facing 2 issues that I think are related, one for some time now when new users are created the show with their email address when they login instead of their Display Name. 
The second part of my problem is related to Nintex as we assign tasks to users and it appears that a new user can't be assigned when using the claims user, I can assign it using the AD username (domain\username) and the person gets an email with notifications but because the login process uses the claims ID task can't be processed. Is there a way to check the account I select in Nintex is the same used by the new user?
Thanks,
Stephan

**Comment by Yvand** [comment]
@savila202501 sorry for the late reply
The best way to ensure what account is actually selected is to check the SharePoint logs.
LDAPCP records all its activity in Product/Area "LDAPCP"
