### ISSUE TITLE
[QUESTION] Where are Global Configuration stored

### ISSUE THREAD

**Issue by domsen123** [Yvand/LDAPCP#81]
Can you please tell me, where are the global configuration informations are stored? Cause I need to update the LDAP user password automaticly.

Thanks

**Comment by Yvand** [comment]
@domsen123 LDAPCP stores all its configuration in a SharePoint persisted object, in the configuration database. You can view it by running this SQL command:

```sql
SELECT Id, Name, cast (properties as xml) AS XMLProps FROM Objects WHERE Name = 'LdapcpConfig'
```

To update its configuration, such as the password, I strongly recommend that you use PowerShell, as described in https://ldapcp.com/Configure-LDAPCP.html

**Comment by domsen123** [comment]
Hi Yvand... thanks for your response...
Unfortunately I cant set the LDAP user & password with powershell, right?!
So maybe I have to do it directly over SQL... I dont like this method, too :/

**Comment by Yvand** [comment]
@domsen123 You can update it with PowerShell like this:

```powershell
Add-Type -AssemblyName "ldapcp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=80be731bc1a1a740"
$config = [ldapcp.LDAPCPConfig]::GetConfiguration("LDAPCPConfig")
$config.LDAPConnectionsProp[1].Password = "newpassword"
$config.Update()
```

**Comment by domsen123** [comment]
@Yvand ahh... awesome! thank you very much!
