### ISSUE TITLE
LDAPCP - Sorry, we're having trouble reaching the server.

### ISSUE THREAD

**Issue by haoadam** [Yvand/LDAPCP#82]
LDAPCP behave so weird that it only able to resolve if key in full Email Address(some time get the sorry message as well)...
It shows "Sorry, we're having trouble reaching the server.", while i tried to key in a few letters and i found that the log did return some entities

Picture below shows then i try again to search again my previous resolved email address by enter just 4 letters. it took quite long to loading and the message shows.. sharepoint log attached as well
![image](https://user-images.githubusercontent.com/16855300/55465843-8e759400-5630-11e9-87c9-b4d848e47b78.png)

Please help...

**Comment by Yvand** [comment]
Error message suggests something takes too long. It may or may not be due to LDAPCP, it's impossible to say based on the extract you sent.
Can you extract the full log for the correlation ID of the request and check what takes too long?
For your information, LDAPCP uses monitored scopes to monitor all operations that may take time (LDAP requests). You can find them by filtering logs on "Message" contains "[LDAPCP]"

**Comment by haoadam** [comment]
[log.txt](https://github.com/Yvand/LDAPCP/files/3041306/log.txt)

Attached log file that i tried to filter based on Message contain "LDAPCP" and "resolving user"
which i found there is an exceptional message.. It mentions "The server is not operational", may I know is it related to LDAPCP as well?

**Comment by Yvand** [comment]
@haoadam  the callstack shows that error is caused by SPActiveDirectoryClaimProvider (Windows authN mode), LDAPCP is not involved in this issue

**Comment by haoadam** [comment]
is that mean my people picker still trying to resolve in window authn mode which blocked LDAPCP from showing the result? is there any setting people picker for LDAPCP i missed out?

**Comment by haoadam** [comment]
@Yvand i found the root cause, it is because my secondary AD is blocked 389 port, firewall open n it works now! Million thanks!

However, i have another question, may I know why LDAPCP is showing two selection for an account?
One is UPN, another one is mail.. may I know where to change this setting to let LDAPCP to show only one?
![image](https://user-images.githubusercontent.com/16855300/55536108-89c1e600-56eb-11e9-845c-837a6ab36850.png)

**Comment by Yvand** [comment]
@haoadam you can remove the claim types you don't want to see in the people picker from LDAPCP claims mapping page in central administration > security

**Comment by haoadam** [comment]
Thanks! but I still can remove whatever from "Active Directory".. any idea?
![image](https://user-images.githubusercontent.com/16855300/55539070-66e70000-56f2-11e9-91b4-22f4257ce328.png)
"

**Comment by haoadam** [comment]
I figure this out :), thanks for all your help, btw, your LDAPCP is really a life saver. you are a hero we don deserve bro!
$cpm = Get-SPClaimProviderManager
$ad = get-spclaimprovider -identity "AD"
$ad.IsVisible = $false
$cpm.Update()
