### ISSUE TITLE
Client certificate authentication on LDAP

### ISSUE THREAD

**Issue by RKSelvi** [Yvand/LDAPCP#83]
Hello, 

LDAPCP works great. The one question I had is that to make it work over port 636 with Secured Sockets Layer. To make this work for user profile synchronization we had to use a client certificate. I don't see that implementation in the LDAPCP code base. Is that something implemented differently or coming down the pipeline? Or should we branch/fork and add our custom implementation. Please advice.

Thanks!

**Comment by Yvand** [comment]
Hello,
I understand you want to use a client certificate to authenticate on a LDAP server, instead of a username/password. Indeed, LDAPCP doesn't support that currently.
But the need for this is not clear to me. Are you saying this is because of user profile synchronization that you need this? Can you explain why?

**Comment by RKSelvi** [comment]
Thank you for your response. 
No, not just with certificate, there will be username/password. I believe current implementation of LDAPCP communicates to LDAP via port 389. As it will send username/password as clear text we need to use port 636. To use via port 636 we need to package certificate with the request. So that was the question if LDAPCP has that implementation or coming down the pipeline. We are going with custom solution, if needed at this moment.

**Comment by Yvand** [comment]
@RKSelvi when you create the LDAP connection in LDAPCP configuration page, you can check the options "Secure", "Signing" and "Sealing", this will establish a secure connection with the LDAP server.

**Comment by RKSelvi** [comment]
The ldap repository is set up over ssl and requires certificate to be sent as part of request.

**Comment by Yvand** [comment]
@RKSelvi can you provide a sample code that does such authentication?

**Comment by RKSelvi** [comment]
We are still in planning and working for feasibility etc. So no code yet. Will follow up once the approach solidifies. Thank you.
