### ISSUE TITLE
LDAP connection gets expire

### ISSUE THREAD

**Issue by samir07** [Yvand/LDAPCP#84]
Hello Yvand - Your solution is a life saver for most of us, thanks for this:)

SP 2016 - LDAP connection gets expire for some reason since it works for a day or two and suddenly stops working, then I re-add the connection and it starts working again perefectly, please help me on how to resolve this? The secod question I have is, I just want to display emailadress and role type in people picker and not other properties, if this is possible please suggest me how.

Thanks!

**Comment by Yvand** [comment]
Hi @samir07, thank you for your feedback :)
Can you please explain what you mean exactly by "expire"? Does it get deleted?
Can you check SharePoint logs, filter on Product/Area "LDAPCP", and see if you find useful information?

**Comment by samir07** [comment]
Hi @Yvand - Thanks for your response. 

I'll check the SharePoint logs first and then let you know more on it. I had just guessed on the LDAP connection expires since LDAPCP works inconsistently for me, and the only work around I follow is re-add the LDAP connection. Thanks!

**Comment by samir07** [comment]
Hi @Yvand - I cannot see anything in logs, its seems to be working good now and I'm monitoring it, if anything goes wrong again will let you know. 

A very imortant question - Since we are planning to deploy it to production, just wants to know do I need to deploy the LDAPCP solution to all the servers or to only wfe's servers? thanks!

**Comment by Yvand** [comment]
You need to run cmdlet Install-SPSolution just one time, to deploy LDAPCP on all servers.
However, as I mentioned in [the documentation](https://ldapcp.com/Install-LDAPCP.html): You must manually install ldapcp.dll in the GAC of SharePoint servers that do not run SharePoint service “Microsoft SharePoint Foundation Web Application”.

**Comment by samir07** [comment]
Thank you so much, this helps alot. :-)

**Comment by Yvand** [comment]
@samir07, do both web applications run with the same application pool account?

**Comment by samir07** [comment]
Hi @Yvand  - Yes, they both work on the same application pool account.

**Comment by Yvand** [comment]
It does not make sense that 1 web app works fine and the other one throws this error, if they both use the same application pool account.
Can you try to repro using the PowerShell script below:

```powershell
Add-Type -AssemblyName System.DirectoryServices.AccountManagement
$ldapUser = "contoso\svcAccount"
$ldapPassword = Read-Host "Enter the password (will appear in clear text)"
$ldapPath = "LDAP://contoso.local/CN=Users,DC=contoso,DC=local"
#$contextOptions = [System.DirectoryServices.AuthenticationTypes] "Negotiate, Signing, Sealing" # Encrypted connection, traffic unreadable in network analyzer
$contextOptions = [System.DirectoryServices.AuthenticationTypes] "None" # LDAP traffic is in clear text

$de = New-Object System.DirectoryServices.DirectoryEntry ($ldapPath, $ldapUser, $ldapPassword, $contextOptions)
$de.Properties["distinguishedName"].Value.ToString()
```

For the test to be valid, you need to use the same settings for the LDAP connection as you used in LDAPCP, and run it as the application pool account.

**Comment by Yvand** [comment]
@samir07 additionally, what version of LDAPCP are you using?

**Comment by samir07** [comment]
Hi @Yvand - I'm using the version - **LDAPCP 12.0.20190321.770** , thanks.

**Comment by Yvand** [comment]
@samir07, did you visit the LDAPCP central administration pages to create a LDAPCP config in the database?
I noticed I also get this issue when there is no existing configuration

**Comment by samir07** [comment]
Hi @Yvand - I'm not sure how to do it. Please help with the steps, thanks.

**Comment by Yvand** [comment]
LDAPCP provisions its own administration in central administration, to allow you to configure it.
You can visit them in central administration > Security.
If you never visited them, then you did not actually create a configuration that is stored as a persisted object in configuration database. Can you do so and let me know if the error message persists after that?

**Comment by samir07** [comment]
Ohhh that setting. Yes, I knew about that and configured it as well as per the need. I have removed the solution now and still sees the issue if I authenticate the second web application through LDAP. Any idea why it's happening?

**Comment by samir07** [comment]
Hi @Yvand - I had figured out redirect issue, it was due to ProviderRealms was not added for the second web application. I have installed back the LDAPCP solution and everything just seems to work great except augmentation, Following is the configuration I have done for augmentation -


Enable augmentation check box is checked.

Select what claim type LDAPCP will use to create claims with the group membership of users: 
http://schemas.microsoft.com/ws/2008/06/identity/claims/role


LDAP Server "Connect to SharePoint domain": 
Checked :Query this server

Can you please check if these are correct?

I have check the logs and all look goods to me, it says -
[LDAPCP] User 'sansari-a@****.com' was augmented with 1 groups.
[LDAPCP] Got 1 group(s) for sansari-a@****.com in 33 ms from LDAP server "LDAP://****.***.com" with LDAP filter "(&(ObjectClass=user) (mail=sansari-a@****.com))".

**Comment by Yvand** [comment]
hi @samir07 I cannot explain why the exact same LDAP connection work in a web app and not in the other one, if both web apps run with the same application pool, it just doesn't make sense.
Is this error random? 
Does it occur all the time on a web app, and never on the other one?

**Comment by samir07** [comment]
Thanks Yvand, I don't have this issue any more and hence closing this issue, thanks:)
