### ISSUE TITLE
[LDAPCP] unexpected error in fillsearch: object reference not set to an instance of an object

### ISSUE THREAD

**Issue by SaboorQuadri** [Yvand/LDAPCP#88]
I have configured LDAPCP and ADFS with SharePoint. 

I have set SPTrustedIdentityTokenIssuer - ClaimProviderName as LDAPCP
I have added all SPClaimtypes required
I have no error in Claim mapping page

However, while looking for user in people picker no user is lookedup, and in ULS logs I am getting an error
Product: LDAPCP
Category: ClaimPicking
EventID:1337
Message: [LDAPCP] unexpected error in fillsearch: object reference not set to an instance of an object

**Comment by Yvand** [comment]
Can you check SharePoint logs and filter on Product/Area "LDAPCP"?

**Comment by SaboorQuadri** [comment]
Hi Yvand, Thank you for your response. this is fixed by cleaning LDAPCP and reinstalling from scratch. I believe something might have gone wrong. The sequence I followed was to install LDAPCP, configured UPSA and Sync connection. however, there was an issue with LDAP port. when that fixed, the above issue appeared. So, it seems there was something went wrong and fixed after fresh installation
