### ISSUE TITLE
Problems adding claim provider users as term store administrators in central admin

### ISSUE THREAD

**Issue by gojo119** [Yvand/LDAPCP#90]
Hello,
is it possible to add SAML users with the ldapcp in central administration as term store administrator? Somehow i cannot get this work. The peoplepicker does not resolve any ldapcp users there. Adding a ldapcp user in the web application user policy settings dialog for expample works without any problem. A user can only be added as term store administrator within the term store management dialog in the sitecollection itself.
Is this behavior by design as i can reproduce this issue with the AzureCP?
best regards
Gottfried

**Comment by Yvand** [comment]
Hi @gojo119 
Yes this is the expected SharePoint design: since a trusted user will never be able to sign-in to central administration, SharePoint does not call LDAPCP/AzureCP in termstore page in central administration

**Comment by gojo119** [comment]
Hello @Yvand,
thanks for clarifying this point. I already expected that this is by design.
best regards

**Comment by kalervojankko** [comment]
Don't if this is fixed already or am I doing something differently, but I can add SAML users as term store administrators from central admin.

**Comment by Yvand** [comment]
@kalervojankko what version of SharePoint / LDAPCP are you using?

**Comment by kalervojankko** [comment]
> @kalervojankko what version of SharePoint / LDAPCP are you using?

SharePoint: 16.0.4822.1000 (March 2019 CU)
LDAPCP: 14.1.20191007.981 (Latest stable version)

**Comment by Yvand** [comment]
@kalervojankko indeed, I just tested that we can add them, but it's not really useful since you cannot sign-in to central admin with those accounts

**Comment by Yvand** [comment]
@kalervojankko understood, thanks for contributing!
