### ISSUE TITLE
LDAPCP with SP19 and people picker matching issue

### ISSUE THREAD

**Issue by tah78** [Yvand/LDAPCP#94]
Hi,

I use LDAPCP and ADFS with SharePoint Server 2019. I added two LDAP connections to two different ADs. Everything is working so far. That means I can add users and roles to site collection admins and sharepoint groups and so on. Also logging in with ADFS works as aspected.

I can also add an user to a people picker field in a list and save the list item without errors. But when I try to open that item in "modern" UI mode to edit it, I get the following error (see screenshots below): "Multiple entries matched, please click to resolve". When I click on the user to resolve, it shows up one entry with an empty user picture. Normally there is an icon with two persons shown, after people picker resolves the entered string and matches an user.

When I edit the same list entry in "classic" mode, everything is fine. Has this something to do with my config, is this a known behaviour or an issue?

Adding user in "modern" UI mode:
<img width="362" alt="list item in edit mode in modern ui after adding user" src="https://user-images.githubusercontent.com/45661849/62973255-055c3e00-be16-11e9-83eb-8981952b22a5.png">

Editing the item in "modern" UI mode:
<img width="402" alt="list item in edit mode after opening" src="https://user-images.githubusercontent.com/45661849/62973330-2886ed80-be16-11e9-92c7-fc8e1911b0a4.png">

List item in "classic" UI mode
<img width="327" alt="list item in claasic ui" src="https://user-images.githubusercontent.com/45661849/62973193-e65dac00-be15-11e9-903c-aa4246f847fd.png">

Editing the item in "classic" UI mode
<img width="273" alt="list item in edit mode in claasic ui" src="https://user-images.githubusercontent.com/45661849/62973462-62f08a80-be16-11e9-9f8f-ae5295913cd7.png">

Is there an active forum or a blog where I can ask further questions, how to configure different szenarios with LDAPCP? 

Thanks a lot.

**Comment by tah78** [comment]
Hi,

I found the reason for the described issue above. It only appears with users that have more than on account with the same e-mail-address (for example normal user and admin account) and only in modern ui edit mode.

As workaround I deleted the e-mail-address from the admin accounts. But why does it work in classic ui mode? Is it configurable that the people picker uses the upn to verify the user, instead of verifying it with the e-mail address?

Best regards.

**Comment by Yvand** [comment]
@tah78 I need to investigate this. Can you tell me:

- The build number of your farm?
- The output of this script (just replace the URL with your own):

```powershell
Add-PSSnapin "Microsoft.SharePoint.PowerShell"
$wa = Get-SPWebApplication "http://spsites/"
$wa.AlternateUrls
foreach ($zone in [System.Enum]::GetNames( [Microsoft.SharePoint.Administration.SPUrlZone] )){
    Write-Host "Get settings for zone $zone :"
    $wa.IisSettings[$zone].ClaimsAuthenticationProviders
}
```

**Comment by tah78** [comment]
@Yvand the build number of my farm is: 

```
Major  Minor  Build  Revision
-----  -----  -----  --------
16     0      10348  12104   

```

The output of your script is:

```
IncomingUrl                              Zone            PublicUrl                               
-----------                              ----            ---------                               
https://teamportal-test       		Default         https://teamportal-test      
Get settings for zone Default :

DisplayName                        : Windows Authentication
ClaimProviderName                  : AD
AllowAnonymous                     : False
UseBasicAuthentication             : False
DisableKerberos                    : True
UseWindowsIntegratedAuthentication : True
AuthenticationRedirectionUrl       : /_windows/default.aspx
UpgradedPersistedProperties        : 


DisplayName                  : ADFS
LoginProviderName            : ADFS
ClaimProviderName            : LDAPCP
AuthenticationRedirectionUrl : /_trust/default.aspx?trust=ADFS
UpgradedPersistedProperties  : 

Get settings for zone Intranet :
Get settings for zone Internet :
Get settings for zone Custom :
Get settings for zone Extranet :
```

**Comment by Yvand** [comment]
@tah78 I'm closing this as this is not an issue in LDAPCP as far as I can see. If you believe I'm wrong, feel free to reopen this issue.
If you wish to see this issue fixed, I suggest you open a ticket at Microsoft Support and request a hotfix
