### ISSUE TITLE
Sharepoint 2016 on Prem external user sharing issue

### ISSUE THREAD

**Issue by samir07** [Yvand/LDAPCP#98]
Hi @Yvand - We are observing issue in sharing site with external user, it gives us a below error.

**Sorry, you are not allowed to share this with external users.**

I have checked logs and couldn't find anything with regards to this. 
For internal user it works seamlessly, just an issue with external user sharing - Can you please help? Thanks in advance!

![image](https://user-images.githubusercontent.com/20821391/65508578-28d2d800-deee-11e9-99eb-b9390f95180f.png)

**Comment by Yvand** [comment]
@samir07 what are the messages recorded by LDAPCP in SharePoint logs when you repro this?

**Comment by samir07** [comment]
Hi @Yvand - I did check the logs and it says - 

**No match in user info list. Input : ch*****g@r***.com.**

**Comment by Yvand** [comment]
is it a message from LDAPCP or SharePoint? What does LDAPCP record?

**Comment by samir07** [comment]
Thanks for your prompt reply.

But I think LDAPCP doesn't record anything.., when I search with filter applied as LDAPCP and external user name, nothing comes up.

**Comment by samir07** [comment]
Just to give you more details here. Before LDAPCP, both users' accounts used to work I mean internal and external as well. After LDAPCP deployed only internal account works now, can you please help or direct me where I can look for?

This story is on high priority for us. You're quick help would be much appreciated.

**Comment by samir07** [comment]
Hi, There is this setting in LDAPCP Global Configuration, **Bypass LDAP lookup** and if I check in this setting sharing access with external users works but here is the thing it doesn't resolve the user and takes any input value as valid one, which then make everything worthless. 

and now I'm just so confused on how to proceed further.

**Comment by Yvand** [comment]
How did you create the SPTrustedIdentityTokenIssuer?
Did you migrate users from Windows to trusted?

**Comment by samir07** [comment]
We have configured it and not migrated. We have both windows as well as trusted login options.

**Comment by Yvand** [comment]
Did you run New-SPTrustedIdentityTokenIssuer with switch UseDefaultConfiguration?
Do you reproduce the issue in a new site collection?

**Comment by samir07** [comment]
Yes, we did it through **New-SPTrustedIdentityTokenIssuer** but without switch UseDefaultConfiguration. Following are the things included - 

$ap = New-SPTrustedIdentityTokenIssuer -Name "****" -Description "********" -realm $realm -ImportTrustCertificate $root -ClaimsMappings $emailClaimMap -SignInUrl $signInURL -IdentifierClaim $emailClaimmap.InputClaimType.

Yes, the issue is reproducible in different site collection as well.

**Comment by Yvand** [comment]
Using switch UseDefaultConfiguration causes a lot of issues, so it's great that you did not.

About your issue, does it happen while searching a user or while validating it?
If LDAPCP truly records nothing in the SharePoint logs, then it cannot cause the issue, but it definitely should.
Can you run this:
"LDAPCP:*"| Set-SPLogLevel -TraceSeverity VerboseEx

Then reproduce your issue and use [ULS viewer](https://www.microsoft.com/en-us/download/details.aspx?id=44020) to filter logs on Product/Area "LDAPCP"

Hopefully it will help

**Comment by samir07** [comment]
Yes, after setting SPLogLevel it does shows traces, below is what it says - 

[LDAPCP] Got 0 result(s) in 7ms from all servers with query "(| (&(objectclass=user)(mail=ch$$$$$$.com*)) (&(objectclass=group)(sAMAccountName=ch$$$$$$.com*)) (&(objectclass=user)(displayName=ch$$$$$$.com*)) (&(objectclass=user)(cn=ch$$$$$$.com*)(!(objectClass=computer))) (&(objectclass=user)(sn=ch$$$$$$.com*)) (&(objectclass=user)(givenName=ch$$$$$$.com*)) (&(objectclass=group)(displayName=ch$$$$$$.com*)) )"

**Comment by Yvand** [comment]
So, clearly, the LDAP server doesn't find any user starting with "ch$$$$$$.com"
Can you try to replay it using this command:
Get-ADUser -LDAPFilter "<filter as is from ldapcp log>" -Server DC

**Comment by samir07** [comment]
Thank you so very much @Yvand . You're just unbelievable, everything works just perfect now.

Here what I missed, actually I had added AD connection where only internal users are present, now adding LDAP connection worked for me, really a silly mistake but I was unaware of that it was AD connection string and not the LDAP connection string.
